// packages/material-tailwind-react/src/components/Stepper/index.tsx
import React from "react";

// @floating-ui
import { useMergeRefs } from "@floating-ui/react";

// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// components
import Step from "./Step";

// types
import {
  isFirstStep,
  isLastStep,
  activeStep,
  className,
  children,
  propTypesActiveStep,
  propTypesIsFirstStep,
  propTypesIsLastStep,
  propTypesClassName,
  propTypesChildren,
} from "../../types/components/stepper";

export interface StepperProps extends React.ComponentProps<"div"> {
  activeStep?: activeStep;
  isFirstStep?: isFirstStep;
  isLastStep?: isLastStep;
  className?: className;
  lineClassName?: className;
  activeLineClassName?: className;
  children: children;
}

const Stepper = React.forwardRef<HTMLDivElement, StepperProps>(
  (
    {
      activeStep,
      isFirstStep,
      isLastStep,
      className,
      lineClassName,
      activeLineClassName,
      children,
      ...rest
    },
    ref,
  ) => {
    // 1. init
    const { stepper, step } = useTheme();
    const {
      styles: { base },
    } = stepper;
    const {
      styles: { base: stepBase },
    } = step;
    const containerRef = React.useRef(null);

    const [widthPerStep, setWidthPerStep] = React.useState(0);
    const isFirstStepValue = activeStep === 0;
    const isLastStepValue = Array.isArray(children) && activeStep === children.length - 1;
    const isReachEnd = Array.isArray(children) && activeStep > children.length - 1;

    React.useEffect(() => {
      if (containerRef.current) {
        const childrenInstance: any = children;
        const { width } = containerRef.current.getBoundingClientRect();
        const widthPerStepCalc = width / (childrenInstance.length - 1);

        setWidthPerStep(widthPerStepCalc);
      }
    }, [children]);

    const width = React.useMemo(() => {
      if (!isReachEnd) {
        return widthPerStep * activeStep;
      }
    }, [activeStep, isReachEnd, widthPerStep]);

    const mergedRef = useMergeRefs([ref, containerRef]);

    // 3. set styles
    const stepperClasses = twMerge(objectsToString(base.stepper), className);
    const lineClasses = twMerge(objectsToString(base.line.initial), lineClassName);
    const activeLineClasses = twMerge(
      lineClasses,
      objectsToString(base.line.active),
      activeLineClassName,
    );
    const activeStepClasses = objectsToString(stepBase.active);
    const completedStepClasses = objectsToString(stepBase.completed);

    React.useEffect(() => {
      isLastStep && typeof isLastStep === "function" && isLastStep(isLastStepValue);
      isFirstStep && typeof isFirstStep === "function" && isFirstStep(isFirstStepValue);
    }, [isFirstStep, isFirstStepValue, isLastStep, isLastStepValue]);

    // 4. return
    return (
      <div {...rest} ref={containerRef} className={stepperClasses}>
        <div className={lineClasses} />
        <div
          className={activeLineClasses}
          style={{
            width: `${width}px`,
          }}
        />
        {Array.isArray(children)
          ? children.map((child: any, index) => {
              return React.cloneElement(child, {
                key: index,
                ...child.props,
                className: twMerge(
                  child.props.className,
                  index === activeStep
                    ? twMerge(activeStepClasses, child.props?.activeClassName)
                    : index < activeStep
                    ? twMerge(completedStepClasses, child.props?.completedClassName)
                    : "",
                ),
              });
            })
          : children}
      </div>
    );
  },
);

Stepper.propTypes = {
  activeStep: propTypesActiveStep,
  isFirstStep: propTypesIsFirstStep,
  isLastStep: propTypesIsLastStep,
  className: propTypesClassName,
  lineClassName: propTypesClassName,
  activeLineClassName: propTypesClassName,
  children: propTypesChildren,
};

Stepper.displayName = "MaterialTailwind.Stepper";

export { Stepper, Step };
export default Object.assign(Stepper, {
  Step,
});

// packages/material-tailwind-solid/src/components/Stepper/index.tsx
// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// components
import Step from "./Step";

// types
import { mergeRefs } from "@solid-primitives/refs";
import type { JSX, ParentComponent } from "solid-js";
import { createMemo, createSignal, splitProps } from "solid-js";
import type { children } from "../../types/components/stepper";
import type { activeStep, isFirstStep, isLastStep } from "../../types/components/stepper";
import { StepperContext } from "./StepperContext";

export interface StepperProps {
  activeStep?: activeStep;
  isFirstStep?: isFirstStep;
  isLastStep?: isLastStep;
  class?: string;
  lineClassName?: string;
  activeLineClassName?: string;
  children: children;
}

const Stepper: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & StepperProps> = (props) => {
  // 1. init
  const theme = useTheme();
  const [stepperProps, rest] = splitProps(props, [
    "class",
    "lineClassName",
    "activeLineClassName",
    "children",
    "activeStep",
    "isFirstStep",
    "isLastStep",
    "ref",
  ]);
  const [containerRef, setcontainerRef] = createSignal<HTMLDivElement | null>(null);
  const [tree, setTree] = createSignal<HTMLDivElement[]>([]);
  // 2. caluclate values and styles
  const cProps = createMemo(() => {
    const {
      styles: { base },
    } = theme().stepper;
    const {
      styles: { base: stepBase },
    } = theme().step;

    const containerRefRect = containerRef()?.getBoundingClientRect();
    const steps = tree().length === 1 ? 1 : tree().length - 1;
    const widthPerStepCalc = (containerRefRect?.width || 0) / steps;

    const isFirstStepValue = stepperProps.activeStep === 0;
    const isLastStepValue = stepperProps.activeStep === tree().length - 1;
    const isReachEnd = !stepperProps.activeStep || stepperProps.activeStep > tree().length - 1;

    // 3. set styles
    const stepperClasses = twMerge(objectsToString(base.stepper), stepperProps.class);
    const lineClasses = twMerge(objectsToString(base.line.initial), stepperProps.lineClassName);
    const activeLineClasses = twMerge(
      lineClasses,
      objectsToString(base.line.active),
      stepperProps.activeLineClassName,
    );
    const activeStepClasses = objectsToString(stepBase.active);
    const completedStepClasses = objectsToString(stepBase.completed);
    const activeElement =
      (stepperProps.activeStep !== undefined && tree()[stepperProps.activeStep]) || undefined;
    return {
      width: widthPerStepCalc * (stepperProps.activeStep || 0),
      isFirstStepValue,
      isLastStepValue,
      isReachEnd,
      stepperClasses,
      lineClasses,
      activeLineClasses,
      activeStepClasses,
      completedStepClasses,
      activeElement,
    };
  });

  const ctx = createMemo(() => ({
    stepperProps,
    tree,
    addToTree: (el: HTMLDivElement) => setTree((prev) => [...prev, el]),
    removeFromTree: (id: string) => setTree((prev) => prev.filter((el) => el.id !== id)),
    cProps,
  }));

  // 4. return
  return (
    <div
      {...rest}
      ref={mergeRefs(
        (el) => setcontainerRef(el),
        (el) => (typeof stepperProps.ref === "function" ? stepperProps.ref(el) : stepperProps.ref),
      )}
      class={cProps().stepperClasses}
    >
      {
        (stepperProps.isLastStep &&
          typeof stepperProps.isLastStep === "function" &&
          stepperProps.isLastStep(cProps().isLastStepValue)) as any
      }
      {
        (stepperProps.isFirstStep &&
          typeof stepperProps.isFirstStep === "function" &&
          stepperProps.isFirstStep(cProps().isFirstStepValue)) as any
      }
      <div class={cProps().lineClasses} />
      <div
        class={cProps().activeLineClasses}
        style={{
          width: `${cProps().width}px`,
        }}
      />
      <StepperContext.Provider value={ctx}>{props.children}</StepperContext.Provider>
    </div>
  );
};

export { Stepper, Step };
export default Object.assign(Stepper, {
  Step,
});
