// packages/material-tailwind-react/src/context/theme/index.js
const merge = require("deepmerge");

import { createContext } from "react";
import PropTypes from "prop-types";

import theme from "@material-tailwind/react/theme";

export const MaterialTailwindTheme = createContext(theme);
MaterialTailwindTheme.displayName = "MaterialTailwindThemeProvider";

export function ThemeProvider({ value, children }) {
  return (
    <MaterialTailwindTheme.Provider value={merge(theme, value)}>
      {children}
    </MaterialTailwindTheme.Provider>
  );
}

ThemeProvider.defaultProps = {
  value: theme,
};

ThemeProvider.propTypes = {
  value: PropTypes.object,
  children: PropTypes.node.isRequired,
};

// packages/material-tailwind-solid/src/context/theme.tsx
import { createContext, useContext, createMemo } from "solid-js";
import type { ParentComponent } from "solid-js";
import { deepmerge } from "deepmerge-ts";
import defaultTheme from "../theme/index";
import type { Theme } from "../theme/index";
import type { DeepPartial } from "ts-essentials";

const MaterialTailwindTheme = createContext(() => defaultTheme);

const ThemeProvider: ParentComponent<IThemeProvider> = (props) => {
  const theme = createMemo(() => deepmerge(defaultTheme, props.defaultValue) as Theme);

  return (
    <MaterialTailwindTheme.Provider value={theme}>{props.children}</MaterialTailwindTheme.Provider>
  );
};

const useTheme = () => useContext(MaterialTailwindTheme);

interface IThemeProvider {
  defaultValue?: DeepPartial<Theme>;
}

export { MaterialTailwindTheme, ThemeProvider, useTheme };
