// packages/material-tailwind-solid/src/components/Tooltip/index.tsx
// @floating-ui

// framer-motion

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import { autoUpdate, flip, offset as fuiOffset, shift } from "@floating-ui/dom";
import { Motion } from "@motionone/solid";
import { useFloating } from "solid-floating-ui";
import type { JSX, JSXElement, ParentComponent } from "solid-js";
import { Show, createMemo, createSignal, mergeProps, splitProps } from "solid-js";
import type {
  animate,
  content,
  dismiss,
  handler,
  interactive,
  offset,
  open,
  placement,
} from "../../types/components/popover";

export interface TooltipProps {
  open?: open;
  handler?: handler;
  content?: content;
  interactive?: interactive;
  placement?: placement;
  offset?: offset;
  dismiss?: dismiss;
  animate?: animate;
  children: JSXElement;
}

export const Tooltip: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & TooltipProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();
  const [internalOpen, setInternalOpen] = createSignal(false);
  const [reference, setReference] = createSignal<HTMLElement>();
  const [floating, setFloating] = createSignal<HTMLElement>();

  // 2. set animation
  const defaultAnimation = {
    unmount: {
      opacity: 0,
    },
    mount: {
      opacity: 1,
    },
  };

  // 3. set default props
  const mergedProps = mergeProps(
    () => theme().popover.defaultProps,
    { animate: defaultAnimation, handler: setInternalOpen, open: internalOpen },
    props,
  );

  const [tooltipProps, rest] = splitProps(mergedProps, [
    "open",
    "handler",
    "content",
    "interactive",
    "placement",
    "offset",
    "dismiss",
    "animate",
    "children",
    "class",
  ]);

  // 3. set styles
  const styles = createMemo(() => {
    const {
      styles: { base },
    } = theme().tooltip;
    const tooltipClasses = twMerge(classnames(objectsToString(base)), tooltipProps.class);
    return { tooltipClasses };
  });

  // 5. set @floating-ui
  const position = useFloating(reference, floating, {
    placement: mergedProps.placement,
    strategy: "absolute",
    whileElementsMounted: autoUpdate,
    middleware: [flip(), shift(), fuiOffset(mergedProps.offset)],
  });

  // const { x, y, reference, floating, strategy, refs, update, context } = useFloating({
  //   open,
  //   onOpenChange: handler,
  //   middleware: [fuiOffset(offset), flip(), shift()],
  //   placement,
  // });

  // const { getReferenceProps, getFloatingProps } = useInteractions([
  //   useClick(context, {
  //     enabled: interactive,
  //   }),
  //   useFocus(context),
  //   useHover(context),
  //   useRole(context, { role: "tooltip" }),
  //   useDismiss(context, dismiss),
  // ]);

  // React.useEffect(() => {
  //   if (refs.reference.current && refs.floating.current && open) {
  //     return autoUpdate(refs.reference.current, refs.floating.current, update);
  //   }
  // }, [open, update, refs.reference, refs.floating]);

  // const mergedRef = useMergeRefs([ref, floating]);
  // const childMergedRef = useMergeRefs([ref, reference]);

  // 6. Create an instance of AnimatePresence because of the types issue with the children
  const animate = createMemo(() =>
    tooltipProps.open() ? mergedProps.animate.mount : mergedProps.animate.unmount,
  );

  // 7. return
  return (
    <>
      <span
        ref={setReference}
        onMouseEnter={() => tooltipProps.handler(true)}
        onMouseLeave={() => tooltipProps.handler(false)}
        //toDo add Close on keydown
      >
        {tooltipProps.children}
      </span>

      <Show when={tooltipProps.open()}>
        <Motion.div
          {...rest}
          ref={setFloating}
          style={{
            position: position?.strategy,
            width: "max-content",
            top: position?.y + "px" ?? 0,
            left: position?.x + "px" ?? 0,
            "z-index": 9999,
          }}
          class={styles().tooltipClasses}
          initial={tooltipProps.animate.unmount}
          exit={tooltipProps.animate.unmount}
          animate={animate()}
        >
          {tooltipProps.content}
        </Motion.div>
      </Show>
    </>
  );
};
export default Tooltip;

// packages/material-tailwind-react/src/components/Tooltip/index.js
import { forwardRef, cloneElement, useEffect, useMemo } from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  offset as fuiOffset,
  flip,
  shift,
  autoUpdate,
  useFloating,
  useInteractions,
  useRole,
  useDismiss,
  useClick,
  useHover,
  useFocus,
  FloatingPortal,
} from "@floating-ui/react-dom-interactions";

// framer-motion
import { AnimatePresence, motion } from "framer-motion";

// utils
import mergeRefs from "react-merge-refs";
import classnames from "classnames";
import merge from "deepmerge";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const Tooltip = forwardRef(
  (
    { open, handler, content, placement, offset, dismiss, animate, className, children, ...rest },
    ref,
  ) => {
    // 1. init
    const { tooltip } = useTheme();
    const {
      defaultProps,
      styles: { base },
    } = tooltip;

    // 2. set default props
    placement = placement ?? defaultProps.placement;
    offset = offset ?? defaultProps.offset;
    dismiss = dismiss ?? defaultProps.dismiss;
    animate = animate ?? defaultProps.animate;
    className = className ?? defaultProps.className;

    // 3. set styles
    const tooltipClasses = classnames(objectsToString(base), className);

    // 4. set animation
    const animation = {
      unmount: {
        opacity: 0,
      },
      mount: {
        opacity: 1,
      },
    };
    const appliedAnimation = merge(animation, animate);

    // 5. set @floating-ui
    const { x, y, reference, floating, strategy, refs, update, context } = useFloating({
      open,
      onOpenChange: handler,
      middleware: [fuiOffset(offset), flip(), shift()],
      placement,
    });

    const { getReferenceProps, getFloatingProps } = useInteractions([
      useClick(context),
      useHover(context),
      useFocus(context),
      useRole(context, { role: "tooltip" }),
      useDismiss(context, dismiss),
    ]);

    useEffect(() => {
      if (refs.reference.current && refs.floating.current && open) {
        return autoUpdate(refs.reference.current, refs.floating.current, update);
      }

      return null;
    }, [open, update, refs.reference, refs.floating]);

    const mergedRef = useMemo(() => mergeRefs([ref, floating]), [floating, ref]);
    const childMergedRef = useMemo(() => mergeRefs([ref, reference]), [reference, ref]);

    // 6. return
    return (
      <>
        {typeof children === "string" ? (
          <span
            {...getReferenceProps({
              ref: childMergedRef,
            })}
          >
            {children}
          </span>
        ) : (
          cloneElement(children, {
            ...getReferenceProps({
              ...children?.props,
              ref: childMergedRef,
            }),
          })
        )}
        <FloatingPortal>
          <AnimatePresence>
            {open && (
              <motion.div
                {...getFloatingProps({
                  ...rest,
                  ref: mergedRef,
                  className: tooltipClasses,
                  style: {
                    position: strategy,
                    top: y ?? "",
                    left: x ?? "",
                  },
                  initial: "unmount",
                  exit: "unmount",
                  animate: open ? "mount" : "unmount",
                  variants: appliedAnimation,
                })}
              >
                {content}
              </motion.div>
            )}
          </AnimatePresence>
        </FloatingPortal>
      </>
    );
  },
);

Tooltip.propTypes = {
  open: PropTypes.bool.isRequired,
  handler: PropTypes.func.isRequired,
  content: PropTypes.node.isRequired,
  placement: PropTypes.oneOf([
    "top-start",
    "top",
    "top-end",
    "right-start",
    "right",
    "right-end",
    "bottom-start",
    "bottom",
    "bottom-end",
    "left-start",
    "left",
    "left-end",
  ]),
  offset: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.shape({
      mainAxis: PropTypes.number,
      crossAxis: PropTypes.number,
      alignmentAxis: PropTypes.number,
    }),
  ]),
  dismiss: PropTypes.shape({
    enabled: PropTypes.bool,
    escapeKey: PropTypes.bool,
    referencePointerDown: PropTypes.bool,
    outsidePointerDown: PropTypes.bool,
    ancestorScroll: PropTypes.bool,
    bubbles: PropTypes.bool,
  }),
  animate: PropTypes.shape({
    mount: PropTypes.instanceOf(Object),
    unmount: PropTypes.instanceOf(Object),
  }),
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Tooltip.displayName = "Tooltip";

export default Tooltip;
