// packages/material-tailwind-react/src/components/Accordion/AccordionBody.js
import React, { forwardRef, useRef } from "react";
import PropTypes from "prop-types";

// framer-motion
import { motion } from "framer-motion";

// utils
import classnames from "classnames";
import merge from "deepmerge";
import objectsToString from "../../utils/objectsToString";

// context
import { useAccordion } from "./AccordionContext";
import { useTheme } from "../../context/theme";

const AccordionBody = forwardRef(({ className, children, ...rest }, ref) => {
  // 1. init
  const { open, animate } = useAccordion();
  const { accordion } = useTheme();
  const {
    styles: { base },
  } = accordion;

  const bodyEl = useRef(null);

  // 2. set default props
  className = className ?? "";

  // 3. set styles
  const bodyClasses = classnames(objectsToString(base.body), className);

  // 4. set animation
  const heightAnimation = {
    unmount: {
      height: "0px",
      transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
    },
    mount: {
      height: `${bodyEl.current?.scrollHeight}px`,
      transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
    },
  };

  const mainAnimation = {
    unmount: {
      opacity: 0,
      transition: { duration: 0.3, ease: "linear" },
    },
    mount: {
      opacity: 1,
      transition: { duration: 0.3, ease: "linear" },
    },
  };

  const appliedAnimation = merge(mainAnimation, animate);

  // 5. return
  return (
    <motion.div
      className="overflow-hidden"
      ref={bodyEl}
      initial="unmount"
      exit="unmount"
      animate={open ? "mount" : "unmount"}
      variants={heightAnimation}
    >
      <motion.div
        {...rest}
        ref={ref}
        className={bodyClasses}
        initial="unmount"
        exit="unmount"
        animate={open ? "mount" : "unmount"}
        variants={appliedAnimation}
      >
        {children}
      </motion.div>
    </motion.div>
  );
});

AccordionBody.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

AccordionBody.displayName = "AccordionBody";

export default AccordionBody;

// packages/material-tailwind-solid/src/components/Accordion/AccordionBody.tsx
//Solid
import { createMemo } from "solid-js";
import type { JSX, ParentComponent } from "solid-js";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { Motion } from "@motionone/solid";
import { deepmerge } from "deepmerge-ts";
import { useTheme } from "../../context/theme";
import { useAccordion } from "./AccordionContext";

export interface AccordionBodyProps {
  [key: string]: any;
}

export const AccordionBody: ParentComponent<
  AccordionBodyProps & JSX.HTMLAttributes<HTMLDivElement>
> = (props) => {
  let contentRef!: HTMLDivElement;
  // 1. init
  const context = useAccordion();
  const theme = useTheme();

  // 2. set styles
  const bodyClasses = createMemo(() =>
    twMerge(classnames(objectsToString(theme().accordion.styles.base.body)), props.class),
  );

  // 3. animation
  const animate = createMemo(() => {
    return deepmerge(theme().accordion.defaultProps.animate.mount, {
      height: context().open ? contentRef?.clientHeight + "px" : "0px",
    });
  });
  //
  return (
    <Motion.div
      class="overflow-hidden"
      initial={theme().accordion.defaultProps.animate.initial}
      exit={theme().accordion.defaultProps.animate.unmount}
      animate={animate()}
    >
      <div ref={contentRef}>
        <div class={bodyClasses()} {...props}>
          {props.children}
        </div>
      </div>
    </Motion.div>
  );
};

export default AccordionBody;
