// packages/material-tailwind-react/src/components/Accordion/index.js
import React, { forwardRef, useMemo } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { AccordionContextProvider } from "./AccordionContext";

// accordion components
import AccordionHeader from "./AccordionHeader";
import AccordionBody from "./AccordionBody";

const Accordion = forwardRef(
  ({ open, icon, animate, className, disabled, children, ...rest }, ref) => {
    // 1. init
    const { accordion } = useTheme();
    const {
      defaultProps,
      styles: { base },
    } = accordion;

    // 2. set default props
    icon = icon ?? defaultProps.icon;
    animate = animate ?? defaultProps.animate;
    className = className ?? defaultProps.className;
    disabled = disabled ?? defaultProps.disabled;

    // 3. set styles
    const accordionClasses = classnames(
      objectsToString(base.container),
      { [objectsToString(base.disabled)]: disabled },
      className,
    );

    // 4. memoize context value
    const contextValue = useMemo(() => ({ open, icon, animate }), [open, icon, animate]);

    // 5. return
    return (
      <AccordionContextProvider value={contextValue}>
        <div {...rest} ref={ref} className={accordionClasses} disabled={disabled}>
          {children}
        </div>
      </AccordionContextProvider>
    );
  },
);

Accordion.propTypes = {
  open: PropTypes.bool.isRequired,
  icon: PropTypes.node,
  animate: PropTypes.shape({
    mount: PropTypes.instanceOf(Object),
    unmount: PropTypes.instanceOf(Object),
  }),
  disabled: PropTypes.bool,
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Accordion.displayName = "Accordion";

export { Accordion, AccordionHeader, AccordionBody };
export default Object.assign(Accordion, { Header: AccordionHeader, Body: AccordionBody });

// packages/material-tailwind-solid/src/components/Accordion/index.tsx
import { createMemo, mergeProps, splitProps } from "solid-js";
import type { JSX, ParentComponent } from "solid-js";
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { AccordionContext, useAccordion } from "./AccordionContext";

// types
import type { animate, disabled, icon, open } from "../../types/components/accordion";

// accordion components
import type { AccordionBodyProps } from "./AccordionBody";
import { AccordionBody } from "./AccordionBody";
// import type { AccordionHeaderProps } from "./AccordionHeader";
import { AccordionHeader } from "./AccordionHeader";

export interface AccordionProps extends JSX.HTMLAttributes<HTMLDivElement> {
  open: open;
  icon?: icon;
  animate?: animate;
  disabled?: disabled;
}

const Accordion: ParentComponent<AccordionProps> = (props) => {
  // 1. init
  const theme = useTheme();
  const [contextProps, rest] = splitProps(props, ["open", "icon", "animate", "disabled"]);

  // 2. set default props
  const contextValue = mergeProps(() => theme().accordion.defaultProps, contextProps);

  // 3. set styles
  const accordionClasses = createMemo(() => {
    return twMerge(
      classnames(objectsToString(theme().accordion.styles.base.container), {
        [objectsToString(theme().accordion.styles.base.disabled)]: contextProps.disabled,
      }),
      theme().accordion.defaultProps?.class,
      rest.class,
    );
  });

  // 5. return
  return (
    //@ts-ignore type of icons are incompatible !?
    <AccordionContext.Provider value={() => contextValue}>
      <div {...rest} class={accordionClasses()}>
        {props.children}
      </div>
    </AccordionContext.Provider>
  );
};

// Accordion.propTypes = {
//   open: propTypesOpen,
//   icon: propTypesIcon,
//   animate: propTypesAnimate,
//   disabled: propTypesDisabled,
//   className: propTypesClassName,
//   children: propTypesChildren,
// };

// Accordion.displayName = "MaterialTailwind.Accordion";

export type { AccordionBodyProps };
export { Accordion, AccordionHeader, AccordionBody, useAccordion };
export default Object.assign(Accordion, {
  Header: AccordionHeader,
  Body: AccordionBody,
});
