// legacy/material-tailwind-react/src/components/List/ListItemPrefix.tsx
import React from "react";

// context
import { useTheme } from "../../context/theme";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// types
import type { className, children } from "../../types/components/list";
import { propTypesClassName, propTypesChildren } from "../../types/components/list";

export interface ListItemPrefixProps extends React.ComponentProps<"div"> {
  className?: className;
  children: children;
}

export const ListItemPrefix = React.forwardRef<HTMLDivElement, ListItemPrefixProps>(
  ({ className, children, ...rest }, ref) => {
    // 1. init
    const { list } = useTheme();
    const {
      styles: { base },
    } = list;

    // 3. set styles
    const listItemPrefixClasses = twMerge(
      classnames(objectsToString(base.itemPrefix)),
      className,
    );

    return (
      <div {...rest} ref={ref} className={listItemPrefixClasses}>
        {children}
      </div>
    );
  },
);

ListItemPrefix.propTypes = {
  className: propTypesClassName,
  children: propTypesChildren,
};

ListItemPrefix.displayName = "MaterialTailwind.ListItemPrefix";

export default ListItemPrefix;

// packages/material-tailwind-solid/src/components/List/ListItemPrefix.tsx
// context
import { useTheme } from "../../context/theme";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// types
import type { JSX, ParentComponent } from "solid-js";
import { createMemo } from "solid-js";

export interface ListItemPrefixProps {
  children: JSX.Element;
}

export const ListItemPrefix: ParentComponent<
  JSX.HTMLAttributes<HTMLDivElement> & ListItemPrefixProps
> = (props) => {
  // 1. init
  const theme = useTheme();

  // 3. set styles
  const listItemPrefixClasses = createMemo(() =>
    twMerge(classnames(objectsToString(theme().list.styles.base.itemPrefix)), props.class),
  );

  return (
    <div {...props} class={listItemPrefixClasses()}>
      {props.children}
    </div>
  );
};

export default ListItemPrefix;
