// packages/material-tailwind-react/src/components/ButtonGroup/index.tsx
import React from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type {
  variant,
  size,
  color,
  fullWidth,
  ripple,
  className,
  children,
} from "../../types/components/button";
import {
  propTypesVariant,
  propTypesSize,
  propTypesColor,
  propTypesFullWidth,
  propTypesRipple,
  propTypesClassName,
  propTypesChildren,
} from "../../types/components/button";

export interface ButtonGroupProps extends React.ComponentProps<"div"> {
  variant?: variant;
  size?: size;
  color?: color;
  fullWidth?: fullWidth;
  ripple?: ripple;
  className?: className;
  children: children;
}

export const ButtonGroup = React.forwardRef<HTMLDivElement, ButtonGroupProps>(
  ({ variant, size, color, fullWidth, ripple, className, children, ...rest }, ref) => {
    // 1. init
    const { buttonGroup } = useTheme();
    const { defaultProps, styles, valid } = buttonGroup;
    const { base, dividerColor } = styles;

    // 2. set default props
    variant = variant ?? defaultProps.variant;
    size = size ?? defaultProps.size;
    color = color ?? defaultProps.color;
    ripple = ripple ?? defaultProps.ripple;
    fullWidth = fullWidth ?? defaultProps.fullWidth;
    className = className ?? defaultProps.className;

    // 4. set styles
    const classes = twMerge(
      classnames(objectsToString(base.initial), {
        [objectsToString(base.fullWidth)]: fullWidth,
        "divide-x": variant !== "outlined",
        [objectsToString(dividerColor[findMatch(valid.colors, color, "blue")])]:
          variant !== "outlined",
      }),
      className,
    );

    // 5. return
    return (
      <div {...rest} ref={ref} className={classes}>
        {React.Children.map(
          children,
          (child, index) =>
            React.isValidElement(child) &&
            React.cloneElement(child, {
              variant,
              size,
              color,
              ripple,
              fullWidth,
              className: classnames({
                "rounded-r-none": index !== React.Children.count(children) - 1,
                "border-r-0": index !== React.Children.count(children) - 1,
                "rounded-l-none": index !== 0,
              }),
            } as any),
        )}
      </div>
    );
  },
);

ButtonGroup.propTypes = {
  variant: PropTypes.oneOf(propTypesVariant),
  size: PropTypes.oneOf(propTypesSize),
  color: PropTypes.oneOf(propTypesColor),
  fullWidth: propTypesFullWidth,
  ripple: propTypesRipple,
  className: propTypesClassName,
  children: propTypesChildren,
};

ButtonGroup.displayName = "MaterialTailwind.ButtonGroup";

export default ButtonGroup;

// packages/material-tailwind-solid/src/components/ButtonGroup/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { Accessor, JSX, ParentComponent } from "solid-js";
import { createContext, createMemo, mergeProps, splitProps, useContext } from "solid-js";
import type { color, fullWidth, ripple, size, variant } from "../../types/components/button";

export interface ButtonGroupProps {
  variant?: variant;
  size?: size;
  color?: color;
  fullWidth?: fullWidth;
  ripple?: ripple;
  class?: string;
}

/**
 * Context
 */
export const ButtonGroupContext = createContext<Accessor<ButtonGroupProps | undefined>>(
  () => undefined,
);
export const useButtonGroupContext = () => useContext(ButtonGroupContext);

/**
 * ButtonGroupComponent
 */
export const ButtonGroup: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & ButtonGroupProps> = (
  props,
) => {
  // ({ variant, size, color, fullWidth, ripple, class, children, ...rest }, ref) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().buttonGroup.defaultProps, props);
  const [buttonGroupProps, rest] = splitProps(
    mergedProps,

    ["variant", "size", "color", "fullWidth", "ripple"],
  );

  // 4. set styles
  const classes = createMemo(() => {
    return twMerge(
      classnames(objectsToString(theme().buttonGroup.styles.base.initial), {
        [objectsToString(theme().buttonGroup.styles.base.fullWidth)]: mergedProps.fullWidth,
        "divide-x": mergedProps.variant !== "outlined",
        [objectsToString(
          theme().buttonGroup.styles.dividerColor[
            findMatch(theme().buttonGroup.valid.colors, mergedProps.color, "blue")
          ],
        )]: mergedProps.variant !== "outlined",
      }),
      mergedProps.class,
    );
  });

  // 5. return
  return (
    <div
      {...rest}
      class={twMerge(
        classnames(
          classes(),
          "[&>*:not(:last-child)]:rounded-r-none",
          "[&>*:not(:last-child)]:border-r-0",
          "[&>*:not(:first-child)]:rounded-l-none",
        ),
      )}
    >
      <ButtonGroupContext.Provider value={() => buttonGroupProps}>
        {props.children}
      </ButtonGroupContext.Provider>
    </div>
  );
};

export default ButtonGroup;
