// packages/material-tailwind-react/src/components/Timeline/TimelineItem.tsx
import React from "react";

// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import {
  className,
  children,
  propTypeChildren,
  propTypeClassName,
} from "../../types/components/timeline";

const TimelineItemContext = React.createContext<any>(0);
TimelineItemContext.displayName = "MaterialTailwind.TimelineItemContext";

export function useTimelineItem() {
  const context = React.useContext(TimelineItemContext);
  if (!context) {
    throw new Error(
      "useTimelineItemContext() must be used within a TimelineItem. It happens when you use TimelineIcon, TimelineConnector or TimelineBody components outside the TimelineItem component.",
    );
  }

  return context;
}

// component
export interface TimelineItemProps extends React.HTMLAttributes<HTMLLIElement> {
  className?: className;
  children?: children;
}

export const TimelineItem = React.forwardRef<HTMLLIElement, TimelineItemProps>(
  ({ className, children, ...rest }, ref) => {
    // 1. init
    const { timelineItem } = useTheme();
    const { styles } = timelineItem;
    const { base } = styles;
    const [width, setWidth] = React.useState(0);
    const contextValue = React.useMemo(() => [width, setWidth], [width, setWidth]);

    // 3. set styles
    const classes = twMerge(objectsToString(base), className);

    // 4. return
    return (
      <TimelineItemContext.Provider value={contextValue}>
        <li ref={ref} {...rest} className={classes}>
          {children}
        </li>
      </TimelineItemContext.Provider>
    );
  },
);

TimelineItem.propTypes = {
  className: propTypeClassName,
  children: propTypeChildren.isRequired,
};

TimelineItem.displayName = "MaterialTailwind.TimelineItem";

export default TimelineItem;

// packages/material-tailwind-solid/src/components/Timeline/TimelineItem.tsx
// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { Accessor, JSX, ParentComponent, Setter } from "solid-js";
import { createContext, createSignal, useContext } from "solid-js";

const TimelineItemContext = createContext<[width: Accessor<number>, setWidth: Setter<number>] | 0>(
  0,
);

export function useTimelineItem() {
  const context = useContext(TimelineItemContext);
  if (!context) {
    throw new Error(
      "useTimelineItemContext() must be used within a TimelineItem. It happens when you use TimelineIcon, TimelineConnector or TimelineBody components outside the TimelineItem component.",
    );
  }

  return context;
}

export const TimelineItem: ParentComponent<JSX.LiHTMLAttributes<HTMLLIElement>> = (props) => {
  // 1. init
  const theme = useTheme();
  const [width, setWidth] = createSignal(0);

  // 4. return
  return (
    <TimelineItemContext.Provider value={[width, setWidth]}>
      <li
        {...props}
        class={twMerge(objectsToString(theme().timelineItem.styles.base), props.class)}
      >
        {props.children}
      </li>
    </TimelineItemContext.Provider>
  );
};

export default TimelineItem;
