// packages/material-tailwind-react/src/components/Dialog/DialogHeader.js
import { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const DialogHeader = forwardRef(({ className, children, ...rest }, ref) => {
  // 1. init
  const { dialogHeader } = useTheme();
  const {
    defaultProps,
    styles: { base },
  } = dialogHeader;

  // 2. set default props
  className = className ?? defaultProps.className;

  // 3. set styles
  const dialogHeaderClasses = classnames(objectsToString(base), className);

  // 4. return
  return (
    <div {...rest} ref={ref} className={dialogHeaderClasses}>
      {children}
    </div>
  );
});

DialogHeader.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

DialogHeader.displayName = "DialogHeader";

export default DialogHeader;

// packages/material-tailwind-solid/src/components/Dialog/DialogHeader.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import type { ParentComponent, JSX } from "solid-js";
import { createMemo } from "solid-js";

// types

export const DialogHeader: ParentComponent<JSX.HTMLAttributes<HTMLDivElement>> = (props) => {
  // 1. init
  const theme = useTheme();
  const dialogHeaderClasses = createMemo(() => {
    const {
      styles: { base },
    } = theme().dialogHeader;
    return twMerge(
      classnames(objectsToString(base)),
      theme().dialogHeader.defaultProps.class,
      props.class,
    );
  });

  // 4. return
  return (
    <div {...props} class={dialogHeaderClasses()}>
      {props.children}
    </div>
  );
};

export default DialogHeader;
