// packages/material-tailwind-react/src/components/Dialog/index.tsx
import React from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  useFloating,
  useInteractions,
  useClick,
  useRole,
  useDismiss,
  useId,
  FloatingPortal,
  FloatingOverlay,
  FloatingFocusManager,
  useMergeRefs,
} from "@floating-ui/react";

// framer-motion
import { AnimatePresence, motion } from "framer-motion";

// utils
import classnames from "classnames";
import merge from "deepmerge";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { NewAnimatePresenceProps } from "../../types/generic";
import type {
  open,
  handler,
  size,
  dismiss,
  animate,
  className,
  children,
} from "../../types/components/dialog";
import {
  propTypesOpen,
  propTypesHandler,
  propTypesSize,
  propTypesDismiss,
  propTypesAnimate,
  propTypesClassName,
  propTypesChildren,
} from "../../types/components/dialog";

// dialog components
import { DialogHeader, DialogHeaderProps } from "./DialogHeader";
import { DialogBody, DialogBodyProps } from "./DialogBody";
import { DialogFooter, DialogFooterProps } from "./DialogFooter";

export interface DialogProps extends React.ComponentProps<"div"> {
  open: open;
  handler: handler;
  size?: size;
  dismiss?: dismiss;
  animate?: animate;
  className?: className;
  children: children;
}

const Dialog = React.forwardRef<HTMLDivElement, DialogProps>(
  ({ open, handler, size, dismiss, animate, className, children, ...rest }, ref) => {
    // 1. init
    const { dialog } = useTheme();
    const {
      defaultProps,
      valid,
      styles: { base, sizes },
    } = dialog;

    // 2. set default props
    handler = handler ?? undefined;
    size = size ?? defaultProps.size;
    dismiss = dismiss ?? defaultProps.dismiss;
    animate = animate ?? defaultProps.animate;
    className = className ?? defaultProps.className;

    // 3. set styles
    const backdropClasses = classnames(objectsToString(base.backdrop));
    const dialogClasses = twMerge(
      classnames(
        objectsToString(base.container),
        objectsToString(sizes[findMatch(valid.sizes, size, "md")]),
      ),
      className,
    );

    // 4. set animation
    const animation = {
      unmount: {
        opacity: 0,
        y: -50,
        transition: {
          duration: 0.3,
        },
      },
      mount: {
        opacity: 1,
        y: 0,
        transition: {
          duration: 0.3,
        },
      },
    };
    const backdropAnimation = {
      unmount: {
        opacity: 0,
        transition: {
          delay: 0.2,
        },
      },
      mount: {
        opacity: 1,
      },
    };
    const appliedAnimation = merge(animation, animate);

    // 5. set @floating-ui
    const { floating, context } = useFloating({
      open,
      onOpenChange: handler,
    });

    const id = useId();
    const labelId = `${id}-label`;
    const descriptionId = `${id}-description`;

    const { getFloatingProps } = useInteractions([
      useClick(context),
      useRole(context),
      useDismiss(context, dismiss),
    ]);

    const mergedRef = useMergeRefs([ref, floating]);

    // 6. Create an instance of AnimatePresence because of the types issue with the children
    const NewAnimatePresence: React.FC<NewAnimatePresenceProps> = AnimatePresence;

    // 7. return
    return (
      <FloatingPortal>
        <NewAnimatePresence>
          {open && (
            <FloatingOverlay
              style={{
                zIndex: 9999,
              }}
              lockScroll
            >
              <FloatingFocusManager context={context}>
                <motion.div
                  className={size === "xxl" ? "" : backdropClasses}
                  initial="unmount"
                  exit="unmount"
                  animate={open ? "mount" : "unmount"}
                  variants={backdropAnimation}
                  transition={{ duration: 0.2 }}
                >
                  <motion.div
                    {...getFloatingProps({
                      ...rest,
                      ref: mergedRef,
                      className: dialogClasses,
                      "aria-labelledby": labelId,
                      "aria-describedby": descriptionId,
                    })}
                    initial="unmount"
                    exit="unmount"
                    animate={open ? "mount" : "unmount"}
                    variants={appliedAnimation}
                  >
                    {children}
                  </motion.div>
                </motion.div>
              </FloatingFocusManager>
            </FloatingOverlay>
          )}
        </NewAnimatePresence>
      </FloatingPortal>
    );
  },
);

Dialog.propTypes = {
  open: propTypesOpen,
  handler: propTypesHandler,
  size: PropTypes.oneOf(propTypesSize),
  dismiss: propTypesDismiss,
  animate: propTypesAnimate,
  className: propTypesClassName,
  children: propTypesChildren,
};

Dialog.displayName = "MaterialTailwind.Dialog";

export type { DialogHeaderProps, DialogBodyProps, DialogFooterProps };
export { Dialog, DialogHeader, DialogBody, DialogFooter };
export default Object.assign(Dialog, {
  Header: DialogHeader,
  Body: DialogBody,
  Footer: DialogFooter,
});

// packages/material-tailwind-solid/src/components/Dialog/index.tsx
import { Motion, Presence } from "@motionone/solid";
import type { JSX, ParentComponent } from "solid-js";
import { Show } from "solid-js";
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { animate, dismiss, handler, open, size } from "../../types/components/dialog";
import type {} from "../../types/generic";

// dialog components
import { createMemo, createUniqueId, mergeProps, splitProps } from "solid-js";
import type { DialogBodyProps } from "./DialogBody";
import { DialogBody } from "./DialogBody";
import { DialogFooter } from "./DialogFooter";
import { DialogHeader } from "./DialogHeader";

export interface DialogProps {
  open: open;
  handler: handler;
  size?: size;
  dismiss?: dismiss;
  animate?: animate;
}

const Dialog: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & DialogProps> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props

  const mergedProps = mergeProps(() => theme().dialog.defaultProps, { animate: animation }, props);
  const [dialogProps, rest] = splitProps(mergedProps, [
    "open",
    "handler",
    "size",
    "dismiss",
    "animate",
    "class",
  ]);
  const id = createUniqueId();
  const labelId = `${id}-label`;
  const descriptionId = `${id}-description`;
  // 3. set styles
  const cProps = createMemo(() => {
    const {
      valid,
      styles: { base, sizes },
    } = theme().dialog;
    const backdropClasses = classnames(objectsToString(base.backdrop));

    const dialogClasses = twMerge(
      classnames(
        objectsToString(base.container),
        objectsToString(sizes[findMatch(valid.sizes, dialogProps.size, "md")]),
      ),
      dialogProps.class,
    );
    return { backdropClasses, dialogClasses };
  });

  // 7. return
  return (
    <Presence exitBeforeEnter>
      <Show when={dialogProps.open}>
        <Motion.div
          class={mergedProps.size === "xxl" ? "" : cProps().backdropClasses}
          initial={backdropAnimation.unmount}
          exit={backdropAnimation.unmount}
          animate={mergedProps.open ? backdropAnimation.mount : backdropAnimation.unmount}
          transition={{ duration: 0.2 }}
          onClick={dialogProps.handler}
        >
          <Motion.div
            {...rest}
            class={cProps().dialogClasses}
            aria-labelledby={labelId}
            aria-describedby={descriptionId}
            initial={mergedProps.animate.unmount}
            exit={mergedProps.animate.unmount}
            animate={mergedProps.open ? mergedProps.animate.mount : mergedProps.animate.unmount}
          >
            {props.children}
          </Motion.div>
        </Motion.div>
      </Show>
    </Presence>
  );
};

export type { DialogBodyProps };
export { Dialog, DialogHeader, DialogBody, DialogFooter };
export default Object.assign(Dialog, {
  Header: DialogHeader,
  Body: DialogBody,
  Footer: DialogFooter,
});

const animation = {
  unmount: {
    opacity: 0,
    y: -50,
    transition: {
      duration: 0.3,
    },
  },
  mount: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.3,
    },
  },
};

const backdropAnimation = {
  unmount: {
    opacity: 0,
    transition: {
      delay: 0.2,
    },
  },
  mount: {
    opacity: 1,
  },
};
