// packages/material-tailwind-react/src/components/Dialog/index.js
import React, { forwardRef, cloneElement, useMemo } from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  useFloating,
  useInteractions,
  useClick,
  useFocusTrap,
  useRole,
  useDismiss,
  useId,
  FloatingPortal,
  FloatingOverlay,
} from "@floating-ui/react-dom-interactions";

// framer-motion
import { AnimatePresence, motion } from "framer-motion";

// utils
import mergeRefs from "react-merge-refs";
import classnames from "classnames";
import merge from "deepmerge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// dialog components
import DialogHeader from "./DialogHeader";
import DialogBody from "./DialogBody";
import DialogFooter from "./DialogFooter";

const Dialog = forwardRef(
  ({ open, handler, node, size, dismiss, animate, className, children, ...rest }, ref) => {
    // 1. init
    const { dialog } = useTheme();
    const {
      defaultProps,
      valid,
      styles: { base, sizes },
    } = dialog;

    // 2. set default props
    size = size ?? defaultProps.size;
    dismiss = dismiss ?? defaultProps.dismiss;
    animate = animate ?? defaultProps.animate;
    className = className ?? defaultProps.className;

    // 3. set styles
    const backdropClasses = classnames(objectsToString(base.backdrop));
    const dialogClasses = classnames(
      objectsToString(base.container),
      objectsToString(sizes[findMatch(valid.sizes, size, "md")]),
      className,
    );

    // 4. set animation
    const animation = {
      unmount: {
        opacity: 0,
        y: -50,
        transition: {
          duration: 0.3,
        },
      },
      mount: {
        opacity: 1,
        y: 0,
        transition: {
          duration: 0.3,
        },
      },
    };
    const backdropAnimation = {
      unmount: {
        opacity: 0,
        transition: {
          delay: 0.2,
        },
      },
      mount: {
        opacity: 1,
      },
    };
    const appliedAnimation = merge(animation, animate);

    // 5. set @floating-ui
    const { reference, floating, context } = useFloating({
      open,
      onOpenChange: handler,
    });

    const id = useId();
    const labelId = `${id}-label`;
    const descriptionId = `${id}-description`;

    const { getReferenceProps, getFloatingProps } = useInteractions([
      useClick(context),
      useFocusTrap(context),
      useRole(context),
      useDismiss(context, dismiss),
    ]);

    const mergedRef = useMemo(() => mergeRefs([ref, floating]), [floating, ref]);
    const nodeMergedRef = useMemo(() => mergeRefs([node?.ref, reference]), [reference, node]);

    // 6. return
    return (
      <>
        {typeof node === "string" ? (
          <span
            {...getReferenceProps({
              ref: nodeMergedRef,
            })}
          >
            {node}
          </span>
        ) : (
          cloneElement(node, {
            ...getReferenceProps({
              ...node?.props,
              ref: nodeMergedRef,
            }),
          })
        )}
        <FloatingPortal>
          <AnimatePresence>
            {open && (
              <FloatingOverlay lockScroll>
                <motion.div
                  className={size === "xxl" ? "" : backdropClasses}
                  initial="unmount"
                  exit="unmount"
                  animate={open ? "mount" : "unmount"}
                  variants={backdropAnimation}
                  transition={{ duration: 0.2 }}
                >
                  <motion.div
                    {...getFloatingProps({
                      ...rest,
                      ref: mergedRef,
                      className: dialogClasses,
                      initial: "unmount",
                      exit: "unmount",
                      animate: open ? "mount" : "unmount",
                      variants: appliedAnimation,
                      "aria-labelledby": labelId,
                      "aria-describedby": descriptionId,
                    })}
                  >
                    {children}
                  </motion.div>
                </motion.div>
              </FloatingOverlay>
            )}
          </AnimatePresence>
        </FloatingPortal>
      </>
    );
  },
);

Dialog.propTypes = {
  open: PropTypes.bool.isRequired,
  handler: PropTypes.func.isRequired,
  node: PropTypes.node.isRequired,
  size: PropTypes.oneOf(["xs", "sm", "md", "lg", "xl", "xxl"]),
  dismiss: PropTypes.shape({
    enabled: PropTypes.bool,
    escapeKey: PropTypes.bool,
    referencePointerDown: PropTypes.bool,
    outsidePointerDown: PropTypes.bool,
    ancestorScroll: PropTypes.bool,
    bubbles: PropTypes.bool,
  }),
  animate: PropTypes.shape({
    mount: PropTypes.instanceOf(Object),
    unmount: PropTypes.instanceOf(Object),
  }),
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Dialog.Header = DialogHeader;
Dialog.Body = DialogBody;
Dialog.Footer = DialogFooter;

Dialog.displayName = "Dialog";

export { Dialog, DialogHeader, DialogBody, DialogFooter };
export default Object.assign(Dialog, {
  Header: DialogHeader,
  Body: DialogBody,
  Footer: DialogFooter,
});

// packages/material-tailwind-solid/src/components/Dialog/index.tsx
import { Motion, Presence } from "@motionone/solid";
import type { JSX, ParentComponent } from "solid-js";
import { Show } from "solid-js";
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { animate, dismiss, handler, open, size } from "../../types/components/dialog";
import type {} from "../../types/generic";

// dialog components
import { createMemo, createUniqueId, mergeProps, splitProps } from "solid-js";
import type { DialogBodyProps } from "./DialogBody";
import { DialogBody } from "./DialogBody";
import { DialogFooter } from "./DialogFooter";
import { DialogHeader } from "./DialogHeader";

export interface DialogProps {
  open: open;
  handler: handler;
  size?: size;
  dismiss?: dismiss;
  animate?: animate;
}

const Dialog: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & DialogProps> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props

  const mergedProps = mergeProps(() => theme().dialog.defaultProps, { animate: animation }, props);
  const [dialogProps, rest] = splitProps(mergedProps, [
    "open",
    "handler",
    "size",
    "dismiss",
    "animate",
    "class",
  ]);
  const id = createUniqueId();
  const labelId = `${id}-label`;
  const descriptionId = `${id}-description`;
  // 3. set styles
  const cProps = createMemo(() => {
    const {
      valid,
      styles: { base, sizes },
    } = theme().dialog;
    const backdropClasses = classnames(objectsToString(base.backdrop));

    const dialogClasses = twMerge(
      classnames(
        objectsToString(base.container),
        objectsToString(sizes[findMatch(valid.sizes, dialogProps.size, "md")]),
      ),
      dialogProps.class,
    );
    return { backdropClasses, dialogClasses };
  });

  // 7. return
  return (
    <Presence exitBeforeEnter>
      <Show when={dialogProps.open}>
        <Motion.div
          class={mergedProps.size === "xxl" ? "" : cProps().backdropClasses}
          initial={backdropAnimation.unmount}
          exit={backdropAnimation.unmount}
          animate={mergedProps.open ? backdropAnimation.mount : backdropAnimation.unmount}
          transition={{ duration: 0.2 }}
          onClick={dialogProps.handler}
        >
          <Motion.div
            {...rest}
            class={cProps().dialogClasses}
            aria-labelledby={labelId}
            aria-describedby={descriptionId}
            initial={mergedProps.animate.unmount}
            exit={mergedProps.animate.unmount}
            animate={mergedProps.open ? mergedProps.animate.mount : mergedProps.animate.unmount}
          >
            {props.children}
          </Motion.div>
        </Motion.div>
      </Show>
    </Presence>
  );
};

export type { DialogBodyProps };
export { Dialog, DialogHeader, DialogBody, DialogFooter };
export default Object.assign(Dialog, {
  Header: DialogHeader,
  Body: DialogBody,
  Footer: DialogFooter,
});

const animation = {
  unmount: {
    opacity: 0,
    y: -50,
    transition: {
      duration: 0.3,
    },
  },
  mount: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.3,
    },
  },
};

const backdropAnimation = {
  unmount: {
    opacity: 0,
    transition: {
      delay: 0.2,
    },
  },
  mount: {
    opacity: 1,
  },
};
