// packages/material-tailwind-react/src/components/Alert/index.tsx
import React from "react";
import PropTypes from "prop-types";

// framer-motion
import { AnimatePresence, motion, MotionProps } from "framer-motion";

// utils
import Ripple from "material-ripple-effects";
import classnames from "classnames";
import merge from "deepmerge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { NewAnimatePresenceProps } from "../../types/generic";
import type {
  variant,
  color,
  icon,
  show,
  dismissible,
  animate,
  className,
  children,
} from "../../types/components/alert";
import {
  propTypesVariant,
  propTypesColor,
  propTypesIcon,
  propTypesShow,
  propTypesDismissible,
  propTypesAnimate,
  propTypesClassName,
  propTypesChildren,
} from "../../types/components/alert";

export interface AlertProps extends Omit<MotionProps, "animate"> {
  variant?: variant;
  color?: color;
  icon?: icon;
  show?: show;
  dismissible?: dismissible;
  animate?: animate;
  className?: className;
  children: children;
}

export const Alert = React.forwardRef<HTMLDivElement, AlertProps>(
  ({ variant, color, icon, show, dismissible, animate, className, children, ...rest }, ref) => {
    // 1. init
    const { alert } = useTheme();
    const { defaultProps, valid, styles } = alert;
    const { base, variants } = styles;
    const rippleEffect = new Ripple();

    // 2. set default props
    variant = variant ?? defaultProps.variant;
    color = color ?? defaultProps.color;
    className = className ?? defaultProps.className;
    animate = animate ?? defaultProps.animate;
    show = show ?? defaultProps.show;

    // 3. set styles
    const alertBase = objectsToString(base);
    const alertVariant = objectsToString(
      variants[findMatch(valid.variants, variant, "filled")][
        findMatch(valid.colors, color, "blue")
      ],
    );
    const classes = classnames(alertBase, alertVariant, className);

    // 4. set animation
    const mainAnimation = {
      unmount: {
        opacity: 0,
      },
      mount: {
        opacity: 1,
      },
    };
    const appliedAnimation = merge(mainAnimation, animate);

    // 5. icon template
    const iconTemplate = <div className="absolute top-4 left-4">{icon}</div>;

    // 6. Create an instance of AnimatePresence because of the types issue with the children
    const NewAnimatePresence: React.FC<NewAnimatePresenceProps> = AnimatePresence;

    // 7. return
    return (
      <NewAnimatePresence>
        {show && (
          <motion.div
            {...rest}
            ref={ref}
            role="alert"
            className={classes}
            initial="unmount"
            exit="unmount"
            animate={show ? "mount" : "unmount"}
            variants={appliedAnimation}
          >
            {icon && iconTemplate}
            <div className={`${icon ? "ml-8" : ""} mr-12`}>{children}</div>
            {dismissible && (
              <div className="absolute top-3 right-3 w-max rounded-lg hover:bg-white hover:bg-opacity-20 transition-all">
                <div
                  role="button"
                  onClick={dismissible.onClose}
                  onMouseDown={(e) => !dismissible.action && rippleEffect.create(e, "light")}
                  className={`w-max ${dismissible.action ? "" : "p-1 rounded-lg"}`}
                >
                  {dismissible.action || (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  )}
                </div>
              </div>
            )}
          </motion.div>
        )}
      </NewAnimatePresence>
    );
  },
);

Alert.propTypes = {
  variant: PropTypes.oneOf(propTypesVariant),
  color: PropTypes.oneOf(propTypesColor),
  icon: propTypesIcon,
  show: propTypesShow,
  dismissible: propTypesDismissible,
  animate: propTypesAnimate,
  className: propTypesClassName,
  children: propTypesChildren,
};

Alert.displayName = "MaterialTailwind.Alert";

export default Alert;

// packages/material-tailwind-solid/src/components/Alert/index.tsx
import type { JSX, ParentComponent } from "solid-js";
import { Show, createMemo, mergeProps, splitProps } from "solid-js";
import { Motion, Presence } from "@motionone/solid";

// utils
import classnames from "classnames";
import Ripple from "material-ripple-effects";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type {
  animate,
  color,
  dismissible,
  icon,
  show,
  variant,
} from "../../types/components/alert";

export interface AlertProps {
  // PropTypes
  variant?: variant;
  color?: color;
  icon?: icon;
  show?: show;
  dismissible?: dismissible;
  animate?: animate;
}
// Omit<MotionProps, "animate"> {

export const Alert: ParentComponent<AlertProps & JSX.HTMLAttributes<HTMLDivElement>> = (p) => {
  // ({ variant, color, icon, show, dismissible, animate, className, children, ...rest }, ref) => {
  // 1. init
  const theme = useTheme();
  const [alertProps, props] = splitProps(p, [
    "variant",
    "color",
    "show",
    "animate",
    "class",
    "dismissible",
    "icon",
  ]);
  // const { defaultProps, valid, styles } = theme().alert;
  // const { base, variants } = styles;

  const rippleEffect = new Ripple();

  // 2. set default props
  const defaultProps = mergeProps(() => theme().alert.defaultProps, alertProps);

  // 3. set styles

  const alertVariant = createMemo(() => {
    const variants = theme().alert.styles.variants;
    const variant = findMatch(theme().alert.valid.variants, defaultProps.variant, "filled");
    const color = findMatch(theme().alert.valid.colors, defaultProps.color, "blue");

    return objectsToString(variants[variant][color]);
  });
  const classes = createMemo(() =>
    twMerge(
      classnames(objectsToString(theme().alert.styles.base), alertVariant()),
      defaultProps.class,
    ),
  );

  // 7. return
  return (
    <Presence exitBeforeEnter>
      <Show when={defaultProps.show}>
        <Motion.div
          {...props}
          role="alert"
          class={classes()}
          initial={defaultProps.animate.unmount}
          exit={defaultProps.animate.unmount}
          animate={defaultProps.animate.mount}
          transition={{ duration: 0.5 }}
        >
          <Show when={!!defaultProps.icon}>
            {/* @ts-ignore   */}
            <div class="absolute top-4 left-4">{defaultProps.icon}</div>
          </Show>
          <div
            classList={{
              "ml-8": !!defaultProps.icon,
              "mr-12": true,
            }}
          >
            {props.children}
          </div>
          <Show when={defaultProps.dismissible}>
            <div class="absolute transition-all rounded-lg top-3 right-3 w-max hover:bg-white hover:bg-opacity-20">
              <div
                role="button"
                onClick={() => defaultProps?.dismissible?.onClose()}
                onMouseDown={(e) =>
                  !defaultProps?.dismissible?.action && rippleEffect.create(e, "light")
                }
                classList={{
                  "w-max": true,
                  "p-1 rounded-lg": !defaultProps?.dismissible?.action,
                }}
              >
                <Show
                  when={!!defaultProps?.dismissible?.action}
                  fallback={
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="w-6 h-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      stroke-width={2}
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M6 18L18 6M6 6l12 12"
                      />
                    </svg>
                  }
                >
                  {/* @ts-ignore */}
                  {defaultProps?.dismissible?.action}
                </Show>
              </div>
            </div>
          </Show>
        </Motion.div>
      </Show>
    </Presence>
  );
};

export default Alert;
