// packages/material-tailwind-solid/src/components/Dialog/DialogFooter.tsx
// utils
import classnames from "classnames";
import { createMemo } from "solid-js";

import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
// types
import type { ParentComponent, JSX } from "solid-js";

export const DialogFooter: ParentComponent<JSX.HTMLAttributes<HTMLDivElement>> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props

  // 3. set styles
  const dialogFooterClasses = createMemo(() => {
    const {
      styles: { base },
    } = theme().dialogFooter;
    return twMerge(
      classnames(objectsToString(base)),
      theme().dialogFooter.defaultProps.class,
      props.class,
    );
  });

  // 4. return
  return (
    <div {...props} class={dialogFooterClasses()}>
      {props.children}
    </div>
  );
};
export default DialogFooter;

// packages/material-tailwind-react/src/components/Dialog/DialogFooter.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const DialogFooter = forwardRef(({ className, children, ...rest }, ref) => {
  // 1. init
  const { dialogFooter } = useTheme();
  const {
    defaultProps,
    styles: { base },
  } = dialogFooter;

  // 2. set default props
  className = className ?? defaultProps.className;

  // 3. set styles
  const dialogFooterClasses = classnames(objectsToString(base), className);

  // 4. return
  return (
    <div {...rest} ref={ref} className={dialogFooterClasses}>
      {children}
    </div>
  );
});

DialogFooter.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

DialogFooter.displayName = "DialogFooter";

export default DialogFooter;
