// packages/material-tailwind-react/src/types/components/menu.ts
import type { ReactNode } from "react";
import PropTypes from "prop-types";

// @floating-ui types
import type {
  Placement,
  Strategy,
  FloatingContext,
  ReferenceType,
  FloatingTreeType,
} from "@floating-ui/react";

// generic types
import type { dismissType, animation, offsetType } from "../generic";
import {
  propTypesOffsetType,
  propTypesDismissType,
  propTypesAnimation,
  propTypesPlacements,
} from "../generic";

/**
 * This file contains the types and prop-types for Menu and Menu, MenuCore, MenuHandler, MenuList, MenuItem and MenuContext components.
 */

// typescript types
export type open = boolean;
export type handler = React.Dispatch<React.SetStateAction<any>>;
export type placement = Placement;
export type offset = offsetType;
export interface dismiss extends dismissType {
  itemPress?: boolean;
}
export type animate = animation;
export type lockScroll = boolean;
export type disabled = boolean;
export type className = string;
export type children = ReactNode;
export type contextValue = {
  open: open;
  handler: handler;
  setInternalOpen: handler;
  strategy: Strategy;
  x: number;
  y: number;
  reference: (instance: HTMLButtonElement) => void;
  floating: (node: HTMLElement) => void;
  listItemsRef: React.MutableRefObject<any[]>;
  getReferenceProps: (userProps?: React.HTMLProps<Element>) => any;
  getFloatingProps: (userProps?: React.HTMLProps<HTMLElement>) => any;
  getItemProps: (userProps?: React.HTMLProps<HTMLElement>) => any;
  appliedAnimation: animate;
  lockScroll: boolean;
  context: FloatingContext<ReferenceType>;
  tree: FloatingTreeType<ReferenceType>;
  allowHover: boolean;
  internalAllowHover: boolean;
  activeIndex: number;
  setActiveIndex: React.Dispatch<React.SetStateAction<number>>;
  nested: boolean;
};

// javascript prop-types
export const propTypesOpen: any = PropTypes.bool;
export const propTypesHandler: any = PropTypes.func;
export const propTypesPlacement: any = propTypesPlacements;
export const propTypesOffset: any = propTypesOffsetType;
export const propTypesDismiss: any = PropTypes.shape({
  ...propTypesDismissType,
  itemPress: PropTypes.bool,
});
export const propTypesAnimate: any = propTypesAnimation;
export const propTypesLockScroll: any = PropTypes.bool;
export const propTypesDisabled: any = PropTypes.bool;
export const propTypesClassName: any = PropTypes.string;
export const propTypesChildren: any = PropTypes.node.isRequired;
export const propTypesContextValue: any = PropTypes.shape({
  open: PropTypes.bool.isRequired,
  handler: PropTypes.func.isRequired,
  setInternalOpen: PropTypes.func.isRequired,
  strategy: PropTypes.oneOf(["fixed", "absolute"]).isRequired,
  x: PropTypes.number.isRequired,
  y: PropTypes.number.isRequired,
  reference: PropTypes.func.isRequired,
  floating: PropTypes.func.isRequired,
  listItemsRef: PropTypes.instanceOf(Object).isRequired,
  getReferenceProps: PropTypes.func.isRequired,
  getFloatingProps: PropTypes.func.isRequired,
  getItemProps: PropTypes.func.isRequired,
  appliedAnimation: propTypesAnimate.isRequired,
  lockScroll: PropTypes.bool.isRequired,
  context: PropTypes.instanceOf(Object).isRequired,
  tree: PropTypes.any.isRequired,
  allowHover: PropTypes.bool.isRequired,
  activeIndex: PropTypes.number.isRequired,
  setActiveIndex: PropTypes.func.isRequired,
  nested: PropTypes.bool.isRequired,
});

// packages/material-tailwind-solid/src/types/components/menu.ts
// @floating-ui types
// import type {
//   FloatingContext,
//   FloatingTreeType,
//   Placement,
//   ReferenceType,
//   Strategy,
// } from "@floating-ui/react";

// generic types
import { UseFloatingResult } from "solid-floating-ui";
import type { animation, dismissType, offsetType, placements } from "../generic";
import type { Accessor, JSXElement, Setter } from "solid-js";

/**
 * This file contains the types and prop-types for Menu and Menu, MenuCore, MenuHandler, MenuList, MenuItem and MenuContext components.
 */

// typescript types
export type open = boolean;
export type handler = Setter<boolean>;
export type placement = placements;
export type offset = offsetType;
export interface dismiss extends dismissType {
  itemPress?: boolean;
}
export type animate = animation;
export type lockScroll = boolean;
export type disabled = boolean;
export type className = string;
export type children = JSXElement;

export type treeRefType = {
  id: string;
  ref: HTMLButtonElement;
};
export type ParentContext = (() => undefined) | Accessor<contextValue | null>;
export type contextValue = {
  open: Accessor<boolean>;
  handler: handler;
  parentID: string;
  setReference: Setter<HTMLElement | undefined>;
  setFloating: Setter<HTMLElement | undefined>;
  // setInternalOpen: handler;
  reference: Accessor<HTMLElement | undefined>;
  // floating: (node: HTMLElement) => void;
  position?: UseFloatingResult;
  parentRef: Accessor<HTMLElement | undefined>;
  // parentActiveItem: Accessor<string> | (() => string);
  // setParentActiveItem: Setter<string> | (() => void);
  tree: Accessor<treeRefType[]>;
  addToTree: (el: treeRefType) => treeRefType[];
  // parentTree: Accessor<treeRefType[]>;
  // addToParentTree: (el: treeRefType) => treeRefType[] | undefined;
  menuHandlerId: Accessor<string | undefined>;
  setMenuHandlerId: Setter<string | undefined>;
  removeFromTree: (id: string) => treeRefType[] | undefined;
  // removeFromParentTree: (id: string) => treeRefType[] | undefined;
  // parentHandler: handler | (() => undefined);
  // parentMenuHandlerId: Accessor<string | undefined>;
  // childRef: HTMLUListElement;
  // getReferenceProps: (userProps?: any) => any;
  // getFloatingProps: (userProps?: any) => any;
  // getItemProps: (userProps?: any) => any;
  // appliedAnimation: animate;
  // lockScroll: boolean;
  // context: FloatingContext<ReferenceType>;
  // tree: FloatingTreeType<ReferenceType>;
  allowHover: boolean;
  // internalAllowHover: boolean;
  activeItem: Accessor<string>;
  setActiveItem: Setter<string>;
  nested: boolean;
  parentContext: ParentContext;
};
