// packages/material-tailwind-react/src/components/Card/CardFooter.tsx
import React from "react";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { divider, className, children } from "../../types/components/card";
import {
  propTypesDivider,
  propTypesClassName,
  propTypesChildren,
} from "../../types/components/card";

export interface CardFooterProps extends React.ComponentProps<"div"> {
  divider?: divider;
  className?: className;
  children: children;
}

export const CardFooter = React.forwardRef<HTMLDivElement, CardFooterProps>(
  ({ divider, className, children, ...rest }, ref) => {
    // 1. init
    const { cardFooter } = useTheme();
    const {
      defaultProps,
      styles: { base },
    } = cardFooter;

    // 2. set default props
    divider = divider ?? defaultProps.divider;
    className = twMerge(defaultProps.className || "", className);

    // 3. set styles
    const cardFooterClasses = twMerge(
      classnames(objectsToString(base.initial), { [objectsToString(base.divider)]: divider }),
      className,
    );

    // 4. return
    return (
      <div {...rest} ref={ref} className={cardFooterClasses}>
        {children}
      </div>
    );
  },
);

CardFooter.propTypes = {
  divider: propTypesDivider,
  className: propTypesClassName,
  children: propTypesChildren,
};

CardFooter.displayName = "MaterialTailwind.CardFooter";

export default CardFooter;

// packages/material-tailwind-solid/src/components/Card/CardFooter.tsx
import { mergeProps, createMemo } from "solid-js";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { divider } from "../../types/components/card";
import type { ParentComponent, JSX } from "solid-js";

export interface CardFooterProps {
  divider?: divider;
  children?: JSX.Element;
}

export const CardFooter: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & CardFooterProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();

  const mergedProps = mergeProps(() => theme().cardFooter.defaultProps, props);

  // 3. set styles
  const cardFooterClasses = createMemo(() =>
    twMerge(
      classnames(objectsToString(theme().cardFooter.styles.base.initial), {
        [objectsToString(theme().cardFooter.styles.base.divider)]: mergedProps.divider,
      }),
      mergedProps.class,
    ),
  );

  // 4. return
  return (
    <div {...mergedProps} class={cardFooterClasses()}>
      {props.children}
    </div>
  );
};
// CardFooter.propTypes = {
//   divider: propTypesDivider,
//   className: propTypesClassName,
//   children: propTypesChildren,
// };

// CardFooter.displayName = "MaterialTailwind.CardFooter";

export default CardFooter;
