// packages/material-tailwind-react/src/components/Card/CardFooter.js
import { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const CardFooter = forwardRef(({ divider, className, children, ...rest }, ref) => {
  // 1. init
  const { cardFooter } = useTheme();
  const {
    defaultProps,
    styles: { base },
  } = cardFooter;

  // 2. set default props
  className = className ?? defaultProps.className;
  divider = divider ?? defaultProps.divider;

  // 3. set styles
  const cardFooterClasses = classnames(
    objectsToString(base.initial),
    { [objectsToString(base.divider)]: divider },
    className,
  );

  // 4. return
  return (
    <div {...rest} ref={ref} className={cardFooterClasses}>
      {children}
    </div>
  );
});

CardFooter.propTypes = {
  divider: PropTypes.bool,
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

CardFooter.displayName = "CardFooter";

export default CardFooter;

// packages/material-tailwind-solid/src/components/Card/CardFooter.tsx
import { mergeProps, createMemo } from "solid-js";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { divider } from "../../types/components/card";
import type { ParentComponent, JSX } from "solid-js";

export interface CardFooterProps {
  divider?: divider;
  children?: JSX.Element;
}

export const CardFooter: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & CardFooterProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();

  const mergedProps = mergeProps(() => theme().cardFooter.defaultProps, props);

  // 3. set styles
  const cardFooterClasses = createMemo(() =>
    twMerge(
      classnames(objectsToString(theme().cardFooter.styles.base.initial), {
        [objectsToString(theme().cardFooter.styles.base.divider)]: mergedProps.divider,
      }),
      mergedProps.class,
    ),
  );

  // 4. return
  return (
    <div {...mergedProps} class={cardFooterClasses()}>
      {props.children}
    </div>
  );
};
// CardFooter.propTypes = {
//   divider: propTypesDivider,
//   className: propTypesClassName,
//   children: propTypesChildren,
// };

// CardFooter.displayName = "MaterialTailwind.CardFooter";

export default CardFooter;
