// packages/material-tailwind-react/src/components/Card/index.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import findMatch from "utils/findMatch";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

// card components
import CardHeader from "components/Card/CardHeader";
import CardBody from "components/Card/CardBody";
import CardFooter from "components/Card/CardFooter";

const Card = forwardRef(({ variant, color, shadow, className, children, ...rest }, ref) => {
  // 1. init
  const { card } = useTheme();
  const { defaultProps, styles, valid } = card;
  const { base, variants } = styles;

  // 2. set default props
  variant = variant ?? defaultProps.variant;
  color = color ?? defaultProps.color;
  shadow = shadow ?? defaultProps.shadow;
  className = className ?? defaultProps.className;

  // 3. set styles
  const cardRoot = objectsToString(base.initial);
  const cardVariant = objectsToString(
    variants[findMatch(valid.variants, variant, "filled")][findMatch(valid.colors, color, "white")],
  );
  const classes = classnames(
    cardRoot,
    cardVariant,
    { [objectsToString(base.shadow)]: shadow },
    className,
  );

  // 4. return
  return (
    <div {...rest} ref={ref} className={classes}>
      {children}
    </div>
  );
});

Card.propTypes = {
  variant: PropTypes.oneOf(["filled", "gradient"]),
  color: PropTypes.oneOf([
    "transparent",
    "white",
    "blue-grey",
    "grey",
    "brown",
    "deep-orange",
    "orange",
    "amber",
    "yellow",
    "lime",
    "light-green",
    "green",
    "teal",
    "cyan",
    "light-blue",
    "blue",
    "indigo",
    "deep-purple",
    "purple",
    "pink",
    "red",
  ]),
  shadow: PropTypes.bool,
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Card.displayName = "Card";

export { Card, CardHeader, CardBody, CardFooter };
export default Object.assign(Card, {
  Header: CardHeader,
  Body: CardBody,
  Footer: CardFooter,
});

// packages/material-tailwind-solid/src/components/Card/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// card components
import type { CardHeaderProps } from "./CardHeader";
import { CardHeader } from "./CardHeader";
import { CardBody } from "./CardBody";
import type { CardFooterProps } from "./CardFooter";
import { CardFooter } from "./CardFooter";

// types
import type { variant, color, shadow } from "../../types/components/card";
import type { ParentComponent, JSX } from "solid-js";
import { mergeProps, createMemo } from "solid-js";

export interface CardProps {
  variant?: variant;
  color?: color;
  shadow?: shadow;
}

const Card: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & CardProps> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().card.defaultProps, props);

  // 3. set styles
  const classes = createMemo(() => {
    const cardRoot = objectsToString(theme().card.styles.base.initial);
    const color = findMatch(theme().card.valid.colors, mergedProps.color, "white");
    const variant = findMatch(theme().card.valid.variants, mergedProps.variant, "filled");
    const variants = theme().card.styles.variants;
    const cardVariant = objectsToString(variants[variant][color]);

    return twMerge(
      classnames(cardRoot, cardVariant, {
        [objectsToString(theme().card.styles.base.shadow)]: mergedProps.shadow,
      }),
      mergedProps.class,
    );
  });

  // 4. return
  return (
    <div {...mergedProps} class={classes()}>
      {props.children}
    </div>
  );
};

// Card.propTypes = {
//   variant: PropTypes.oneOf(propTypesVariant),
//   color: PropTypes.oneOf(propTypesColor),
//   shadow: propTypesShadow,
//   className: propTypesClassName,
//   children: propTypesChildren,
// };

// Card.displayName = "MaterialTailwind.Card";

export type { CardHeaderProps, CardFooterProps };
export { Card, CardHeader, CardBody, CardFooter };
export default Object.assign(Card, {
  Header: CardHeader,
  Body: CardBody,
  Footer: CardFooter,
});
