// packages/material-tailwind-react/src/components/Popover/index.js
import React, { forwardRef, cloneElement, useEffect, useMemo } from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  offset as fuiOffset,
  flip,
  shift,
  autoUpdate,
  useFloating,
  useInteractions,
  useRole,
  useDismiss,
  useId,
  useClick,
  useFocusTrap,
  FloatingPortal,
} from "@floating-ui/react-dom-interactions";

// framer-motion
import { AnimatePresence, motion } from "framer-motion";

// utils
import mergeRefs from "react-merge-refs";
import classnames from "classnames";
import merge from "deepmerge";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const Popover = forwardRef(
  (
    { open, handler, node, placement, offset, dismiss, animate, className, children, ...rest },
    ref,
  ) => {
    // 1. init
    const { popover } = useTheme();
    const {
      defaultProps,
      styles: { base },
    } = popover;

    // 2. set default props
    placement = placement ?? defaultProps.placement;
    offset = offset ?? defaultProps.offset;
    dismiss = dismiss ?? defaultProps.dismiss;
    animate = animate ?? defaultProps.animate;
    className = className ?? defaultProps.className;

    // 3. set styles
    const popoverClasses = classnames(objectsToString(base), className);

    // 4. set animation
    const animation = {
      unmount: {
        opacity: 0,
      },
      mount: {
        opacity: 1,
      },
    };
    const appliedAnimation = merge(animation, animate);

    // 5. set @floating-ui
    const { x, y, reference, floating, strategy, refs, update, context } = useFloating({
      open,
      onOpenChange: handler,
      middleware: [fuiOffset(offset), flip(), shift()],
      placement,
    });

    const id = useId();
    const labelId = `${id}-label`;
    const descriptionId = `${id}-description`;

    const { getReferenceProps, getFloatingProps } = useInteractions([
      useClick(context),
      useRole(context),
      useDismiss(context, dismiss),
      useFocusTrap(context),
    ]);

    useEffect(() => {
      if (refs.reference.current && refs.floating.current && open) {
        return autoUpdate(refs.reference.current, refs.floating.current, update);
      }
    }, [open, update, refs.reference, refs.floating]);

    const mergedRef = useMemo(() => mergeRefs([ref, floating]), [floating, ref]);
    const nodeMergedRef = useMemo(() => mergeRefs([node?.ref, reference]), [reference, node]);

    // 6. return
    return (
      <>
        {typeof node === "string" ? (
          <span
            {...getReferenceProps({
              ref: nodeMergedRef,
            })}
          >
            {node}
          </span>
        ) : (
          cloneElement(node, {
            ...getReferenceProps({
              ...node?.props,
              ref: nodeMergedRef,
            }),
          })
        )}
        <FloatingPortal>
          <AnimatePresence>
            {open && (
              <motion.div
                {...getFloatingProps({
                  ...rest,
                  ref: mergedRef,
                  className: popoverClasses,
                  style: {
                    position: strategy,
                    top: y ?? "",
                    left: x ?? "",
                  },
                  initial: "unmount",
                  exit: "unmount",
                  animate: open ? "mount" : "unmount",
                  variants: appliedAnimation,
                  "aria-labelledby": labelId,
                  "aria-describedby": descriptionId,
                })}
              >
                {children}
              </motion.div>
            )}
          </AnimatePresence>
        </FloatingPortal>
      </>
    );
  },
);

Popover.propTypes = {
  open: PropTypes.bool.isRequired,
  handler: PropTypes.func.isRequired,
  node: PropTypes.node.isRequired,
  placement: PropTypes.oneOf([
    "top-start",
    "top",
    "top-end",
    "right-start",
    "right",
    "right-end",
    "bottom-start",
    "bottom",
    "bottom-end",
    "left-start",
    "left",
    "left-end",
  ]),
  offset: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.shape({
      mainAxis: PropTypes.number,
      crossAxis: PropTypes.number,
      alignmentAxis: PropTypes.number,
    }),
  ]),
  dismiss: PropTypes.shape({
    enabled: PropTypes.bool,
    escapeKey: PropTypes.bool,
    referencePointerDown: PropTypes.bool,
    outsidePointerDown: PropTypes.bool,
    ancestorScroll: PropTypes.bool,
    bubbles: PropTypes.bool,
  }),
  animate: PropTypes.shape({
    mount: PropTypes.instanceOf(Object),
    unmount: PropTypes.instanceOf(Object),
  }),
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Popover.displayName = "Popover";

export { Popover };
export default Popover;

// packages/material-tailwind-solid/src/components/Popover/index.tsx
// @floating-ui
// import {
//   autoUpdate,
//   flip,
//   offset as fuiOffset,
//   shift,
//   useClick,
//   useDismiss,
//   useFloating,
//   useId,
//   useInteractions,
//   useRole,
// } from "@floating-ui/react";

// utils

// context
import { useTheme } from "../../context/theme";
import { PopoverContextProvider, usePopover } from "./PopoverContext";

// types
import type {
  animate,
  children,
  dismiss,
  handler,
  offset as offsetType,
  open,
  placement,
} from "../../types/components/popover";

// popover components
import { autoUpdate, flip, offset, shift } from "@floating-ui/dom";
import { useFloating } from "solid-floating-ui";
import type { ParentComponent } from "solid-js";
import { createMemo, createSignal, createUniqueId, mergeProps } from "solid-js";
import type { PopoverContentProps } from "./PopoverContent";
import { PopoverContent } from "./PopoverContent";
import type { PopoverHandlerProps } from "./PopoverHandler";
import { PopoverHandler } from "./PopoverHandler";

export interface PopoverProps {
  open?: open;
  handler?: handler;
  placement?: placement;
  offset?: offsetType;
  dismiss?: dismiss;
  animate?: animate;
  children: children;
}

const Popover: ParentComponent<PopoverProps> = (props) => {
  // = ({
  //   open,
  //   handler,
  //   placement,
  //   offset,
  //   dismiss,
  //   animate,
  //   children,
  // }: PopoverProps) => {
  // 1. init
  const theme = useTheme();

  const [internalOpen, setInternalOpen] = createSignal(false);
  const [reference, setReference] = createSignal<HTMLElement>();
  const [floating, setFloating] = createSignal<HTMLElement>();

  const defaultAnimation = {
    unmount: {
      opacity: 0,
    },
    mount: {
      opacity: 1,
    },
  };
  const mergedProps = mergeProps(
    () => theme().popover.defaultProps,
    { animate: defaultAnimation, handler: setInternalOpen, open: internalOpen },
    props,
  );

  // 5. set @floating-ui
  const position = useFloating(reference, floating, {
    placement: mergedProps.placement,
    strategy: "absolute",
    whileElementsMounted: autoUpdate,
    middleware: [flip(), shift(), offset(mergedProps.offset)],
  });

  const id = createUniqueId();

  const contextValue = createMemo(() => ({
    open: mergedProps.open,
    handler: mergedProps.handler,
    position,
    reference,
    setReference,
    floating,
    setFloating,
    appliedAnimation: mergedProps.animate,
    labelId: `${id}-label`,
    descriptionId: `${id}-description`,
  }));

  // 6. return
  return (
    <PopoverContextProvider value={contextValue}>{mergedProps.children}</PopoverContextProvider>
  );
};

export type { PopoverHandlerProps, PopoverContentProps };
export { Popover, PopoverHandler, PopoverContent, usePopover };
export default Object.assign(Popover, { Handler: PopoverHandler, Content: PopoverContent });
