// packages/material-tailwind-react/src/components/Popover/PopoverHandler.tsx
import React from "react";

// utils
import mergeRefs from "react-merge-refs";

// context
import { usePopover } from "./PopoverContext";

// types
import { children, propTypesChildren } from "../../types/components/popover";

export interface PopoverHandlerProps extends React.ComponentProps<any> {
  children: children | React.ComponentProps<any>;
}

export const PopoverHandler = React.forwardRef<HTMLDivElement, PopoverHandlerProps>(
  ({ children, ...rest }, ref) => {
    const { getReferenceProps, reference } = usePopover();

    const mergedRef = React.useMemo(() => mergeRefs([ref, reference]), [ref, reference]);

    return React.cloneElement(children, {
      ...getReferenceProps({
        ...rest,
        ref: mergedRef,
      }),
    });
  },
);

PopoverHandler.propTypes = {
  children: propTypesChildren,
};

PopoverHandler.displayName = "MaterialTailwind.PopoverHandler";

export default PopoverHandler;

// packages/material-tailwind-solid/src/components/Popover/PopoverHandler.tsx
// @floating-ui

// context
import { usePopover } from "./PopoverContext";

// types
import { mergeRefs } from "@solid-primitives/refs";
import type { JSX, ParentComponent } from "solid-js";
import type { children } from "../../types/components/popover";

export interface PopoverHandlerProps {
  children: children;
}

export const PopoverHandler: ParentComponent<
  PopoverHandlerProps & JSX.HTMLAttributes<HTMLElement>
> = (props) => {
  const context = usePopover();

  return (
    <button
      ref={mergeRefs(props.ref, (el) => context()?.setReference(el))}
      onClick={(e) => {
        context()?.handler(!context()?.open());
        typeof props.onClick === "function" && props.onClick(e);
      }}
    >
      {props.children}
    </button>
  );
};

export default PopoverHandler;
