// packages/material-tailwind-react/src/components/Popover/PopoverContext.tsx
import React from "react";

// types
import type { contextValue, children } from "../../types/components/popover";
import { propTypesContextValue, propTypesChildren } from "../../types/components/popover";

export interface PopoverContextProviderProps {
  value: contextValue;
  children: children;
}

export const PopoverContext = React.createContext<contextValue | null>(null);
PopoverContext.displayName = "MaterialTailwind.PopoverContext";

export function usePopover() {
  const context = React.useContext(PopoverContext);

  if (!context) {
    throw new Error(
      "usePopover() must be used within a Popover. It happens when you use PopoverHandler or PopoverContent components outside the Popover component.",
    );
  }

  return context;
}

export function PopoverContextProvider({ value, children }: PopoverContextProviderProps) {
  return <PopoverContext.Provider value={value}>{children}</PopoverContext.Provider>;
}

PopoverContextProvider.propTypes = {
  value: propTypesContextValue,
  children: propTypesChildren,
};

// packages/material-tailwind-solid/src/components/Popover/PopoverContext.tsx
// types
import type { contextValue, children } from "../../types/components/popover";
import type { Accessor } from "solid-js";
import { createContext, useContext } from "solid-js";
type TContext = Accessor<contextValue | null>;
export interface PopoverContextProviderProps {
  value: TContext;
  children: children;
}

export const PopoverContext = createContext<TContext>(() => null);

export function usePopover() {
  const context = useContext(PopoverContext);

  if (!context) {
    throw new Error(
      "usePopover() must be used within a Popover. It happens when you use PopoverHandler or PopoverContent components outside the Popover component.",
    );
  }

  return context;
}

export const PopoverContextProvider = (props: PopoverContextProviderProps) => {
  return <PopoverContext.Provider {...props}>{props.children}</PopoverContext.Provider>;
};
