// packages/material-tailwind-solid/src/components/SpeedDial/SpeedDialContent.tsx
// framer-motion

// @floating-ui

// context
import { useTheme } from "../../context/theme";
import { useSpeedDial } from "./SpeedDialContext";

// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// types
import { Motion } from "@motionone/solid";
import { mergeRefs } from "@solid-primitives/refs";
import type { JSX, ParentComponent } from "solid-js";
import { For, Show, children, createMemo, splitProps } from "solid-js";

export const SpeedDialContent: ParentComponent<JSX.HTMLAttributes<HTMLDivElement>> = (props) => {
  // 1. init
  const theme = useTheme();
  const context = useSpeedDial();

  const [dialProps, rest] = splitProps(props, ["class"]);

  // 2. set styles
  const classes = createMemo(() =>
    twMerge(
      objectsToString(() => theme().speedDialContent.styles),
      dialProps?.class,
    ),
  );

  const getChildren = children(() => props.children);
  // 4. return
  return (
    <Show when={context()?.open()}>
      <div
        {...rest}
        ref={mergeRefs(props.ref, (el) => context()?.setFloating(el))}
        class={classes()}
        style={{
          position: context()?.position.strategy,
          top: context()?.position.y + "px" ?? 0,
          left: context()?.position.x + "px" ?? 0,
          display:
            context()?.position.placement.includes("right") ||
            context()?.position.placement.includes("left")
              ? "flex"
              : "block",
        }}
      >
        {/* <Presence> */}
        <For each={getChildren.toArray()}>
          {(child) => (
            <Motion.div
              initial={context()?.animation.unmount}
              exit={context()?.animation.unmount}
              animate={
                context()?.open() ? context()?.animation.mount : context()?.animation.unmount
              }
            >
              {child}
            </Motion.div>
          )}
        </For>
        {/* </Presence> */}
      </div>
    </Show>
  );
};

export default SpeedDialContent;

// packages/material-tailwind-react/src/components/SpeedDial/SpeedDialContent.tsx
import React from "react";

// framer-motion
import { AnimatePresence, motion } from "framer-motion";

// @floating-ui
import { useMergeRefs } from "@floating-ui/react";

// context
import { useSpeedDial } from "./index";
import { useTheme } from "../../context/theme";

// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// types
import { propTypesChildren, propTypesClassName } from "../../types/components/speedDial";
import type { NewAnimatePresenceProps } from "../../types/generic";

export interface SpeedDialContentProps extends React.ComponentProps<"div"> {}

export const SpeedDialContent = React.forwardRef<HTMLDivElement, SpeedDialContentProps>(
  ({ children, className, ...rest }, ref) => {
    // 1. init
    const {
      speedDialContent: { styles },
    } = useTheme();
    const { x, y, refs, open, strategy, getFloatingProps, animation } = useSpeedDial();
    const mergedRefs = useMergeRefs([ref, refs.setFloating]);

    // 2. set styles
    const classes = twMerge(objectsToString(styles), className);

    // 3. create an instance of AnimatePresence because of the types issue with the children
    const NewAnimatePresence: React.FC<NewAnimatePresenceProps> = AnimatePresence;

    // 4. return
    return (
      <NewAnimatePresence>
        {open && (
          <div
            {...rest}
            ref={mergedRefs}
            className={classes}
            style={{
              position: strategy,
              top: y ?? 0,
              left: x ?? 0,
            }}
            {...getFloatingProps()}
          >
            {React.Children.map(children, (child: React.ReactElement) => (
              <motion.div
                initial="unmount"
                exit="unmount"
                animate={open ? "mount" : "unmount"}
                variants={animation}
              >
                {child}
              </motion.div>
            ))}
          </div>
        )}
      </NewAnimatePresence>
    );
  },
);

SpeedDialContent.propTypes = {
  children: propTypesChildren,
  className: propTypesClassName,
};

SpeedDialContent.displayName = "MaterialTailwind.SpeedDialContent";

export default SpeedDialContent;
