// packages/material-tailwind-solid/src/components/SpeedDial/SpeedDialAction.tsx
// context
import { useTheme } from "../../context/theme";

// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// types
import { createMemo } from "solid-js";
import type { JSX, ParentComponent } from "solid-js";

export const SpeedDialAction: ParentComponent<JSX.ButtonHTMLAttributes<HTMLButtonElement>> = (
  props,
) => {
  // 1. init
  const theme = useTheme();
  const classes = createMemo(() =>
    twMerge(objectsToString(theme().speedDialAction.styles), props.class),
  );
  // 3. return
  return (
    <button {...props} class={classes()}>
      {props.children}
    </button>
  );
};

export default SpeedDialAction;

// packages/material-tailwind-react/src/components/SpeedDial/SpeedDialAction.tsx
import React from "react";

// context
import { useTheme } from "../../context/theme";

// utils
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// types
import { propTypesChildren, propTypesClassName } from "../../types/components/speedDial";

export interface SpeedDialActionProps extends React.ComponentProps<"button"> {}

export const SpeedDialAction = React.forwardRef<HTMLButtonElement, SpeedDialActionProps>(
  ({ className, children }, ref) => {
    // 1. init
    const {
      speedDialAction: { styles },
    } = useTheme();

    // 2. set styles
    const classes = twMerge(objectsToString(styles), className);

    // 3. return
    return (
      <button ref={ref} className={classes}>
        {children}
      </button>
    );
  },
);

SpeedDialAction.propTypes = {
  children: propTypesChildren,
  className: propTypesClassName,
};

SpeedDialAction.displayName = "SpeedDialAction";

export default SpeedDialAction;
