// packages/material-tailwind-solid/src/components/Tabs/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { TabsContextProvider, useTabs } from "./TabsContext";

// tabs components
import type { TabProps } from "./Tab";
import { Tab } from "./Tab";
import type { TabPanelProps } from "./TabPanel";
import { TabPanel } from "./TabPanel";
import type { TabsBodyProps } from "./TabsBody";
import { TabsBody } from "./TabsBody";
import type { TabsHeaderProps } from "./TabsHeader";
import { TabsHeader } from "./TabsHeader";

// types
import type { JSX, ParentComponent } from "solid-js";
import { createMemo, mergeProps, splitProps } from "solid-js";
import type { children, id, orientation, value } from "../../types/components/tabs";

export interface TabsProps {
  id: id;
  value: value;
  orientation?: orientation;
  children: children;
}

const Tabs: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & TabsProps> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().tabs.defaultProps, props);
  const [tabProps, rest] = splitProps(mergedProps, [
    "id",
    "value",
    "orientation",
    "children",
    "class",
  ]);

  // 3. set styles
  const styles = createMemo(() => {
    const { styles } = theme().tabs;
    const tabsClasses = twMerge(
      classnames(objectsToString(styles.base), {
        [styles[tabProps.orientation] && objectsToString(styles[tabProps.orientation])]:
          tabProps.orientation,
      }),
      tabProps.class,
    );
    return { tabsClasses };
  });

  // 4. return
  return (
    <TabsContextProvider
      id={tabProps.id}
      defaultValue={tabProps.value}
      orientation={tabProps.orientation}
    >
      <div {...rest} class={styles().tabsClasses}>
        {tabProps.children}
      </div>
    </TabsContextProvider>
  );
};

export type { TabProps, TabsBodyProps, TabsHeaderProps, TabPanelProps };
export { Tabs, Tab, TabsBody, TabsHeader, TabPanel, useTabs };
export default Object.assign(Tabs, { Tab, Body: TabsBody, Header: TabsHeader, Panel: TabPanel });

// packages/material-tailwind-react/src/components/Tabs/index.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";
import { TabsContextProvider } from "components/Tabs/TabsContext";

// tabs components
import Tab from "components/Tabs/Tab";
import TabsBody from "components/Tabs/TabsBody";
import TabsHeader from "components/Tabs/TabsHeader";
import TabPanel from "components/Tabs/TabPanel";

const Tabs = forwardRef(({ value, className, children, ...rest }, ref) => {
  // 1. init
  const { tabs } = useTheme();
  const {
    defaultProps,
    styles: { base },
  } = tabs;

  // 2. set default props
  className = className ?? defaultProps.className;

  // 3. set styles
  const tabsClasses = classnames(objectsToString(base), className);

  return (
    <TabsContextProvider value={value}>
      <div {...rest} ref={ref} className={tabsClasses}>
        {children}
      </div>
    </TabsContextProvider>
  );
});

Tabs.propTypes = {
  value: PropTypes.string.isRequired,
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Tabs.displayName = "Tabs";
Tabs.Tab = Tab;
Tabs.Body = TabsBody;
Tabs.Header = TabsHeader;
Tabs.Panel = TabPanel;

export { Tabs, Tab, TabsBody, TabsHeader, TabPanel };
export default Object.assign(Tabs, { Tab, Body: TabsBody, Header: TabsHeader, Panel: TabPanel });
