// packages/material-tailwind-solid/src/components/Tabs/TabPanel.tsx
// framer-motion

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { useTabs } from "./TabsContext";

// types
import { Motion, Presence } from "@motionone/solid";
import type { JSX, ParentComponent } from "solid-js";
import { createMemo, mergeProps, splitProps } from "solid-js";
import type { children, value } from "../../types/components/tabs";

export interface TabPanelProps {
  value: value;
  children: children;
}

export const TabPanel: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & TabPanelProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();
  const [state] = useTabs();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().tabPanel.defaultProps, props);
  const [tabProps, rest] = splitProps(mergedProps, ["value", "class", "children"]);

  // 3. set styles
  const styles = createMemo(() => {
    const {
      styles: { base },
    } = theme().tabPanel;

    const tabPanelClasses = twMerge(classnames(objectsToString(base)), tabProps.class);
    return { tabPanelClasses };
  });

  const animate = createMemo(() => {
    if (state.active === tabProps.value) return state.appliedAnimation.mount;
    if (state.isInitial) return state.appliedAnimation.initial || state.appliedAnimation.unmount;
    return state.appliedAnimation.unmount;
  });

  // 5. return
  return (
    <Presence exitBeforeEnter>
      <Motion.div
        {...rest}
        role="tabpanel"
        class={styles().tabPanelClasses}
        initial={state.appliedAnimation.initial}
        exit={state.appliedAnimation.unmount}
        animate={animate()}
        data-value={tabProps.value}
        data-active={state.active}
      >
        {tabProps.children}
      </Motion.div>
    </Presence>
  );
};

export default TabPanel;

// packages/material-tailwind-react/src/components/Tabs/TabPanel.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// framer-motion
import { motion, AnimatePresence } from "framer-motion";

// utils
import merge from "deepmerge";
import classnames from "classnames";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";
import { useTabs } from "components/Tabs/TabsContext";

const TabPanel = forwardRef(({ value, animate, className, children, ...rest }, ref) => {
  // 1. init
  const { tabPanel } = useTheme();
  const {
    defaultProps,
    styles: { base },
  } = tabPanel;
  const [active] = useTabs();

  // 2. set default props
  className = className ?? defaultProps.className;
  animate = animate ?? defaultProps.animate;

  // 3. set styles
  const tabPanelClasses = classnames(objectsToString(base), className);

  // 4. set animation
  const mainAnimation = {
    unmount: {
      opacity: 0,
      position: "absolute",
      top: "0",
      left: "0",
      transition: { duration: 0.5, times: [0.4, 0, 0.2, 1] },
    },
    mount: {
      opacity: 1,
      position: "relative",
      transition: { duration: 0.5, times: [0.4, 0, 0.2, 1] },
    },
  };
  const appliedAnimation = merge(mainAnimation, animate);

  // 5. return
  return (
    <AnimatePresence exitBeforeEnter>
      {active === value && (
        <motion.div
          {...rest}
          ref={ref}
          role="tabpanel"
          className={tabPanelClasses}
          initial="unmount"
          exit="unmount"
          animate={active === value ? "mount" : "unmount"}
          variants={appliedAnimation}
          data-value={value}
        >
          {children}
        </motion.div>
      )}
    </AnimatePresence>
  );
});

TabPanel.propTypes = {
  value: PropTypes.string.isRequired,
  animate: PropTypes.shape({
    mount: PropTypes.instanceOf(Object),
    unmount: PropTypes.instanceOf(Object),
  }),
  className: PropTypes.string,
  disabled: PropTypes.bool,
  children: PropTypes.node.isRequired,
};

TabPanel.displayName = "TabPanel";

export default TabPanel;
