// packages/material-tailwind-solid/src/components/Tabs/TabsContext.tsx
// types
import type { ParentComponent } from "solid-js";
import { createContext, useContext } from "solid-js";
import { createStore } from "solid-js/store";
import type {
  animate,
  indicatorProps,
  isInitial,
  value as valueType,
} from "../../types/components/tabs";
import type { children, id, orientation } from "../../types/components/tabs";

export interface TabsContextValue {
  id: id;
  active: valueType;
  isInitial: isInitial;
  orientation: orientation;
  appliedAnimation: animate;
  indicatorProps: indicatorProps;
}
interface TabsContextSetter {
  setId(value: id): void;
  setActive(value: valueType): void;
  setAnimation(value: animate): void;
  setIndicator(value: indicatorProps): void;
  setIsInitial(value: isInitial): void;
  setOrientation(value: orientation): void;
}
export type TabsContextType = readonly [TabsContextValue, TabsContextSetter];
// dispatch: React.Dispatch<{
//   id: id;
//   active: valueType;
//   isInitial: isInitial;
//   orientation: orientation;
//   appliedAnimation: animate;
//   indicatorProps: indicatorProps;
// }>;

export interface TabsContextProviderProps {
  id?: id;
  defaultValue: valueType;
  orientation?: orientation;
  children: children;
}

export const TabsContext = createContext<TabsContextType | null>(null);

export function useTabs() {
  const context = useContext(TabsContext);

  if (!context) {
    throw new Error(
      "useTabs() must be used within a Tabs. It happens when you use TabsHeader, TabsBody, Tab or TabPanel outside the Tabs component.",
    );
  }

  return context;
}

export const TabsContextProvider: ParentComponent<TabsContextProviderProps> = (props) => {
  const [state, setState] = createStore<TabsContextValue>({
    // eslint-disable-next-line solid/reactivity
    id: props.id ?? "indicator",
    active: props.defaultValue,
    // eslint-disable-next-line solid/reactivity
    orientation: props.orientation || "horizontal",
    isInitial: true,
    appliedAnimation: {
      initial: {},
      unmount: {},
      mount: {},
    },
    indicatorProps: undefined,
  });
  const ctx = [
    state,
    {
      setId(value: id): void {
        setState("id", value);
      },
      setActive(value: valueType): void {
        setState("active", value);
      },
      setAnimation(value: animate): void {
        setState("appliedAnimation", value);
      },
      setIndicator(value: indicatorProps): void {
        setState("indicatorProps", value);
      },
      setIsInitial(value: isInitial): void {
        setState("isInitial", value);
      },
      setOrientation(value: orientation): void {
        setState("orientation", value);
      },
    },
  ] as const;

  return <TabsContext.Provider value={ctx}>{props.children}</TabsContext.Provider>;
};

// packages/material-tailwind-react/src/components/Tabs/TabsContext.tsx
import React from "react";

// types
import {
  id,
  value as valueType,
  animate,
  children,
  propTypesValue,
  indicatorProps,
  isInitial,
  orientation,
  propTypesId,
  propTypesOrientation,
} from "../../types/components/tabs";
import { propTypesChildren } from "../../types/components/tabs";

export interface TabsContextType {
  state: {
    id: id;
    active: valueType;
    isInitial: isInitial;
    orientation: orientation;
    appliedAnimation: animate;
    indicatorProps: indicatorProps;
  };
  dispatch: React.Dispatch<{
    id: id;
    active: valueType;
    isInitial: isInitial;
    orientation: orientation;
    appliedAnimation: animate;
    indicatorProps: indicatorProps;
  }>;
}

export interface TabsContextProviderProps {
  id?: id;
  value: valueType;
  orientation?: orientation;
  children: children;
}

function reducer(state, action) {
  switch (action.type) {
    case "SET_ID": {
      return { ...state, id: action.value };
    }
    case "SET_ACTIVE": {
      return { ...state, active: action.value };
    }
    case "SET_ANIMATION": {
      return { ...state, appliedAnimation: action.value };
    }
    case "SET_INDICATOR": {
      return { ...state, indicatorProps: action.value };
    }
    case "SET_IS_INITIAL": {
      return { ...state, isInitial: action.value };
    }
    case "SET_ORIENTATION": {
      return { ...state, orientation: action.value };
    }
    default: {
      throw new Error(`Unhandled action type: ${action.type}`);
    }
  }
}

export const TabsContext = React.createContext<TabsContextType | null>(null);
TabsContext.displayName = "MaterialTailwind.TabsContext";

export function useTabs() {
  const context = React.useContext(TabsContext);

  if (!context) {
    throw new Error(
      "useTabs() must be used within a Tabs. It happens when you use TabsHeader, TabsBody, Tab or TabPanel outside the Tabs component.",
    );
  }

  return context;
}

export const TabsContextProvider = ({
  id,
  value,
  orientation,
  children,
}: TabsContextProviderProps) => {
  const initialState = React.useMemo(
    () => ({
      id: id ?? "indicator",
      active: value,
      orientation,
      isInitial: true,
      appliedAnimation: {
        initial: {},
        unmount: {},
        mount: {},
      },
      indicatorProps: undefined,
    }),
    [id, value, orientation],
  );

  const [state, dispatch] = React.useReducer(reducer, initialState);
  const contextValue = React.useMemo(() => ({ state, dispatch }), [state]);

  return <TabsContext.Provider value={contextValue}>{children}</TabsContext.Provider>;
};

export const setId = (dispatch: (arg: object) => void, value: id) =>
  dispatch({ type: "SET_ID", value });
export const setActive = (dispatch: (arg: object) => void, value: valueType) =>
  dispatch({ type: "SET_ACTIVE", value });
export const setAnimation = (dispatch: (arg: object) => void, value: animate) =>
  dispatch({ type: "SET_ANIMATION", value });
export const setIndicator = (dispatch: (arg: object) => void, value: indicatorProps) =>
  dispatch({ type: "SET_INDICATOR", value });
export const setIsInitial = (dispatch: (arg: object) => void, value: isInitial) =>
  dispatch({ type: "SET_IS_INITIAL", value });
export const setOrientation = (dispatch: (arg: object) => void, value: orientation) =>
  dispatch({ type: "SET_ORIENTATION", value });

TabsContextProvider.propTypes = {
  id: propTypesId,
  value: propTypesValue,
  orientation: propTypesOrientation,
  children: propTypesChildren,
};

TabsContextProvider.displayName = "MaterialTailwind.TabsContextProvider";
