// packages/material-tailwind-solid/src/components/Tabs/TabsHeader.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { useTabs } from "./TabsContext";

// types
import type { JSX, ParentComponent } from "solid-js";
import { createEffect, createMemo, mergeProps, splitProps } from "solid-js";
import type { children, indicatorProps } from "../../types/components/tabs";

export interface TabsHeaderProps {
  indicatorProps?: indicatorProps;
  children: children;
}

export const TabsHeader: ParentComponent<JSX.HTMLAttributes<HTMLUListElement> & TabsHeaderProps> = (
  props,
) => {
  // = React.forwardRef<HTMLUListElement, TabsHeaderProps>(
  //   ({ indicatorProps, className, children, ...rest }, ref) => {
  // 1. init
  const theme = useTheme();
  const [state, { setIndicator }] = useTabs();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().tabsHeader.defaultProps, props);
  const [headerProps, rest] = splitProps(mergedProps, ["indicatorProps", "class", "children"]);

  createEffect(() => {
    setIndicator(headerProps.indicatorProps);
  });

  // 3. set styles
  const styles = createMemo(() => {
    const { styles } = theme().tabsHeader;
    const orientation = state.orientation;
    const tabsHeaderClasses = twMerge(
      classnames(objectsToString(styles.base), {
        [styles[orientation] && objectsToString(styles[orientation])]: orientation,
      }),
      headerProps.class,
    );
    return { tabsHeaderClasses };
  });

  // 4. return
  return (
    <nav>
      <ul {...rest} role="tablist" class={styles().tabsHeaderClasses}>
        {headerProps.children}
      </ul>
    </nav>
  );
};

export default TabsHeader;

// packages/material-tailwind-react/src/components/Tabs/TabsHeader.tsx
import React from "react";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { useTabs, setIndicator } from "./TabsContext";

// types
import type { indicatorProps, className, children } from "../../types/components/tabs";
import {
  propTypesIndicator,
  propTypesClassName,
  propTypesChildren,
} from "../../types/components/tabs";

export interface TabsHeaderProps extends React.ComponentProps<"ul"> {
  indicatorProps?: indicatorProps;
  className?: className;
  children: children;
}

export const TabsHeader = React.forwardRef<HTMLUListElement, TabsHeaderProps>(
  ({ indicatorProps, className, children, ...rest }, ref) => {
    // 1. init
    const { tabsHeader } = useTheme();
    const { defaultProps, styles } = tabsHeader;
    const { state, dispatch } = useTabs();
    const { orientation } = state;

    React.useEffect(() => {
      setIndicator(dispatch, indicatorProps);
    }, [dispatch, indicatorProps]);

    // 2. set default props
    className = twMerge(defaultProps.className || "", className);

    // 3. set styles
    const tabsHeaderClasses = twMerge(
      classnames(objectsToString(styles.base), {
        [styles[orientation] && objectsToString(styles[orientation])]: orientation,
      }),
      className,
    );

    // 4. return
    return (
      <nav>
        <ul {...rest} ref={ref} role="tablist" className={tabsHeaderClasses}>
          {children}
        </ul>
      </nav>
    );
  },
);

TabsHeader.propTypes = {
  indicatorProps: propTypesIndicator,
  className: propTypesClassName,
  children: propTypesChildren,
};

TabsHeader.displayName = "MaterialTailwind.TabsHeader";

export default TabsHeader;
