// packages/material-tailwind-solid/src/components/Switch/index.tsx
// utils
import classnames from "classnames";
import Ripple from "material-ripple-effects";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { JSX, ParentComponent } from "solid-js";
import { Show, createMemo, mergeProps, splitProps } from "solid-js";
import type { color, disabled, label, objectType, ripple } from "../../types/components/checkbox";

export interface SwitchProps {
  color?: color;
  label?: label;
  ripple?: ripple;
  disabled?: disabled;
  containerProps?: objectType;
  labelProps?: objectType;
  circleProps?: objectType;
  containerRef?: HTMLDivElement;
}

export const Switch: ParentComponent<JSX.InputHTMLAttributes<HTMLInputElement> & SwitchProps> = (
  props,
) => {
  // = React.forwardRef<HTMLInputElement, SwitchProps>(
  //   (
  //     {
  //       color,
  //       label,
  //       ripple,
  //       className,
  //       disabled,
  //       containerProps,
  //       circleProps,
  //       labelProps,
  //       inputRef,
  //       ...rest
  //     },
  //     ref,
  //   ) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().switch.defaultProps, props);
  const [switchProps, rest] = splitProps(mergedProps, [
    "color",
    "label",
    "ripple",
    "class",
    "disabled",
    "containerProps",
    "circleProps",
    "labelProps",
    "containerRef",
  ]);

  // 3. set ripple effect instance
  const rippleEffect = new Ripple();

  // 4. set styles
  const styles = createMemo(() => {
    const { valid, styles } = theme().switch;
    const { base, colors } = styles;
    const rootClasses = classnames(objectsToString(base.root), {
      [objectsToString(base.disabled)]: switchProps.disabled,
    });
    const containerClasses = twMerge(
      classnames(objectsToString(base.container)),
      switchProps.containerProps?.class,
    );
    const inputClasses = twMerge(
      classnames(
        objectsToString(base.input),
        objectsToString(colors[findMatch(valid.colors, switchProps.color, "blue")]),
      ),
      switchProps.class,
    );
    const circleClasses = twMerge(
      classnames(
        objectsToString(base.circle),
        colors[findMatch(valid.colors, switchProps.color, "blue")].circle,
        colors[findMatch(valid.colors, switchProps.color, "blue")].before,
      ),
      switchProps.circleProps?.class,
    );
    const rippleClasses = classnames(objectsToString(base.ripple));
    const labelClasses = twMerge(
      classnames(objectsToString(base.label)),
      switchProps.labelProps?.class,
    );
    return {
      rootClasses,
      containerClasses,
      inputClasses,
      circleClasses,
      rippleClasses,
      labelClasses,
    };
  });
  // 4. return
  return (
    <div ref={switchProps.containerRef} class={styles().rootClasses}>
      <div {...switchProps.containerProps} class={styles().containerClasses}>
        <input
          {...rest}
          type="checkbox"
          disabled={switchProps.disabled}
          id={rest.id || "switch"}
          class={styles().inputClasses}
        />
        <label
          {...switchProps.circleProps}
          for={rest.id || "switch"}
          class={styles().circleClasses}
        >
          <Show when={switchProps.ripple}>
            <div
              class={styles().rippleClasses}
              onMouseDown={(e) => {
                const onMouseDown = switchProps.containerProps?.onMouseDown;

                if (switchProps.ripple) {
                  rippleEffect.create(e, "dark");
                }

                return typeof onMouseDown === "function" && onMouseDown(e);
              }}
            />
          </Show>
        </label>
      </div>
      <Show when={!!switchProps.label}>
        <label {...switchProps.labelProps} for={rest.id || "switch"} class={styles().labelClasses}>
          {switchProps.label}
        </label>
      </Show>
    </div>
  );
};

export default Switch;

// packages/material-tailwind-react/src/components/Switch/index.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import Ripple from "material-ripple-effects";
import classnames from "classnames";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

const Switch = forwardRef(
  ({ color, label, ripple, className, containerProps, circleProps, labelProps, ...rest }, ref) => {
    // 1. init
    const { switch: toggle } = useTheme();
    const { defaultProps, valid, styles } = toggle;
    const { base, colors } = styles;

    // 2. set default props
    color = color ?? defaultProps.color;
    ripple = ripple ?? defaultProps.ripple;
    className = className ?? defaultProps.className;

    // 3. set ripple effect instance
    const rippleEffect = ripple !== undefined && new Ripple();

    // 4. set styles
    const rootClasses = classnames(objectsToString(base.root));
    const containerClasses = classnames(objectsToString(base.container), containerProps?.className);
    const inputClasses = classnames(
      objectsToString(base.input),
      objectsToString(colors[findMatch(valid.colors, color, "light-blue")]),
      className,
    );
    const circleClasses = classnames(
      objectsToString(base.circle),
      colors[findMatch(valid.colors, color, "light-blue")].circle,
      colors[findMatch(valid.colors, color, "light-blue")].before,
      circleProps?.className,
    );
    const rippleClasses = classnames(objectsToString(base.ripple));
    const labelClasses = classnames(objectsToString(base.label), labelProps?.className);

    // 4. return
    return (
      <div ref={ref} className={rootClasses}>
        <div {...containerProps} htmlFor={rest.id || "switch"} className={containerClasses}>
          <input {...rest} type="checkbox" id={rest.id || "switch"} className={inputClasses} />
          <label {...circleProps} htmlFor={rest.id || "switch"} className={circleClasses}>
            {ripple && (
              <div
                className={rippleClasses}
                onMouseDown={(e) => {
                  const onMouseDown = containerProps?.onMouseDown;

                  if (ripple) {
                    rippleEffect.create(e, "dark");
                  }

                  return typeof onMouseDown === "function" && onMouseDown();
                }}
              />
            )}
          </label>
        </div>
        {label && (
          <label {...labelProps} htmlFor={rest.id || "switch"} className={labelClasses}>
            {label}
          </label>
        )}
      </div>
    );
  },
);

Switch.propTypes = {
  color: PropTypes.oneOf([
    "blue-grey",
    "grey",
    "brown",
    "deep-orange",
    "orange",
    "amber",
    "yellow",
    "lime",
    "light-green",
    "green",
    "teal",
    "cyan",
    "light-blue",
    "blue",
    "indigo",
    "deep-purple",
    "purple",
    "pink",
    "red",
  ]),
  label: PropTypes.string,
  ripple: PropTypes.bool,
  className: PropTypes.string,
  containerProps: PropTypes.instanceOf(Object),
  circleProps: PropTypes.instanceOf(Object),
  labelProps: PropTypes.instanceOf(Object),
};

Switch.displayName = "Switch";

export { Switch };
export default Switch;
