// packages/material-tailwind-solid/src/components/Avatar/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { Component, JSX } from "solid-js";
import { createMemo, mergeProps, splitProps } from "solid-js";
import type { size, variant } from "../../types/components/avatar";
export interface AvatarProps {
  variant?: variant;
  size?: size;
}

export const Avatar: Component<JSX.ImgHTMLAttributes<HTMLImageElement> & AvatarProps> = (props) => {
  // 1. init
  const theme = useTheme();
  const [avatarProps, rest] = splitProps(props, ["variant", "size", "class"]);

  const defaultProps = mergeProps(() => theme().avatar.defaultProps, avatarProps);

  // 3. set styles
  const avatarVariant = createMemo(() =>
    objectsToString(
      theme().avatar.styles.variants[
        findMatch(theme().avatar.valid.variants, defaultProps.variant, "rounded")
      ],
    ),
  );

  const avatarSize = createMemo(() => {
    const size = findMatch(theme().avatar.valid.sizes, defaultProps.size, "md");
    const styleSize = theme().avatar.styles.sizes[size];
    return objectsToString(styleSize);
  });

  const classes = createMemo(() =>
    twMerge(
      classnames(objectsToString(theme().avatar.styles.base), avatarVariant(), avatarSize()),
      defaultProps.class,
    ),
  );

  // 4. return
  return <img {...rest} class={classes()} />;
};

// Avatar.propTypes = {
//   variant: PropTypes.oneOf(propTypesVariant),
//   size: PropTypes.oneOf(propTypesSize),
//   className: propTypesClassName,
// };

// Avatar.displayName = "MaterialTailwind.Avatar";

export default Avatar;

// packages/react/src/components/avatar.tsx
import * as React from "react";

// @utils
import { twMerge } from "tailwind-merge";

// @hooks
import { useTheme } from "@context";

// @theme
import { avatarTheme } from "@theme";

// @types
import type { Props } from "@types";

export interface AvatarProps extends Props<"img" | any> {
  as?: React.ElementType;
  src: string;
  alt?: string;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  variant?: "circular" | "rounded" | "square";
  className?: string;
}

/**
 * @remarks
 * [Documentation](http://www.material-tailwind.com/docs/react/button) •
 * [Props Definition](https://www.material-tailwind.com/docs/react/button#button-props) •
 * [Theming Guide](https://www.material-tailwind.com/docs/react/button#button-theme)
 *
 * @example
 * ```tsx
 * import { Button } from "@material-tailwind/react";
 *
 * export default function Example() {
 *  return <Button>Button</Button>;
 * }
 * ```
 */
export const Avatar = React.forwardRef<
  HTMLImageElement | HTMLElement,
  AvatarProps
>(({ as, src, alt, variant, size, className, ...rest }, ref) => {
  const Element = as ?? "img";
  const contextTheme = useTheme();
  const theme = contextTheme?.avatar ?? avatarTheme;
  const defaultProps = theme?.defaultProps;

  size ??= (defaultProps?.size as AvatarProps["size"]) ?? "md";
  variant ??= (defaultProps?.variant as AvatarProps["variant"]) ?? "circular";

  const styles = twMerge(
    theme.baseStyle,
    theme["size"][size],
    theme["variant"][variant],
    className,
  );

  return <Element {...rest} ref={ref} src={src} alt={alt} className={styles} />;
});

Avatar.displayName = "MaterialTailwind.Avatar";

export default Avatar;
