// packages/material-tailwind-solid/src/components/ButtonGroup/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { Accessor, JSX, ParentComponent } from "solid-js";
import { createContext, createMemo, mergeProps, splitProps, useContext } from "solid-js";
import type { color, fullWidth, ripple, size, variant } from "../../types/components/button";

export interface ButtonGroupProps {
  variant?: variant;
  size?: size;
  color?: color;
  fullWidth?: fullWidth;
  ripple?: ripple;
  class?: string;
}

/**
 * Context
 */
export const ButtonGroupContext = createContext<Accessor<ButtonGroupProps | undefined>>(
  () => undefined,
);
export const useButtonGroupContext = () => useContext(ButtonGroupContext);

/**
 * ButtonGroupComponent
 */
export const ButtonGroup: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & ButtonGroupProps> = (
  props,
) => {
  // ({ variant, size, color, fullWidth, ripple, class, children, ...rest }, ref) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().buttonGroup.defaultProps, props);
  const [buttonGroupProps, rest] = splitProps(
    mergedProps,

    ["variant", "size", "color", "fullWidth", "ripple"],
  );

  // 4. set styles
  const classes = createMemo(() => {
    return twMerge(
      classnames(objectsToString(theme().buttonGroup.styles.base.initial), {
        [objectsToString(theme().buttonGroup.styles.base.fullWidth)]: mergedProps.fullWidth,
        "divide-x": mergedProps.variant !== "outlined",
        [objectsToString(
          theme().buttonGroup.styles.dividerColor[
            findMatch(theme().buttonGroup.valid.colors, mergedProps.color, "blue")
          ],
        )]: mergedProps.variant !== "outlined",
      }),
      mergedProps.class,
    );
  });

  // 5. return
  return (
    <div
      {...rest}
      class={twMerge(
        classnames(
          classes(),
          "[&>*:not(:last-child)]:rounded-r-none",
          "[&>*:not(:last-child)]:border-r-0",
          "[&>*:not(:first-child)]:rounded-l-none",
        ),
      )}
    >
      <ButtonGroupContext.Provider value={() => buttonGroupProps}>
        {props.children}
      </ButtonGroupContext.Provider>
    </div>
  );
};

export default ButtonGroup;

// packages/react/src/components/button-group.tsx
import React from "react";

// @utils
import { twMerge } from "tailwind-merge";

// @context
import { useTheme } from "@context";

// @theme
import { buttonGroupTheme } from "@theme";

// @types
import type { BaseComponent } from "@types";
import type { ButtonProps } from "@components";

export interface ButtonGroupProps extends BaseComponent<"div"> {
  ripple?: boolean;
  rounded?: boolean;
  fullWidth?: boolean;
  className?: string;
  orientation?: "horizontal" | "vertical";
  children: React.ReactNode;
}

/**
 * @remarks
 * [Documentation](http://www.material-tailwind.com/docs/react/button-group) •
 * [Props Definition](https://www.material-tailwind.com/docs/react/button-group#button-group-props) •
 * [Theming Guide](https://www.material-tailwind.com/docs/react/button-group#button-group-theme)
 *
 * @example
 * ```tsx
 * import { ButtonGroup } from "@material-tailwind/react";
 *
 * export default function Example() {
 *  return (
 *    <ButtonGroup>
 *      <Button>Button</Button>
 *      <Button>Button</Button>
 *      <Button>Button</Button>
 *    </ButtonGroup>
 *  );
 * }
 * ```
 */
export const ButtonGroup = React.forwardRef<HTMLDivElement, ButtonGroupProps>(
  (
    {
      color,
      variant,
      size,
      ripple,
      rounded,
      fullWidth,
      className,
      orientation,
      children,
      ...rest
    },
    ref,
  ) => {
    const contextTheme = useTheme();
    const theme = contextTheme?.buttonGroup ?? buttonGroupTheme;
    const defaultProps = contextTheme?.buttonGroup?.defaultProps;

    size ??= (defaultProps?.size as ButtonGroupProps["size"]) ?? "md";
    ripple ??= (defaultProps?.ripple as ButtonGroupProps["ripple"]) ?? true;
    color ??= (defaultProps?.color as ButtonGroupProps["color"]) ?? "primary";
    variant ??=
      (defaultProps?.variant as ButtonGroupProps["variant"]) ?? "solid";
    orientation ??=
      (defaultProps?.orientation as ButtonGroupProps["orientation"]) ??
      "horizontal";
    fullWidth ??=
      (defaultProps?.fullWidth as ButtonGroupProps["fullWidth"]) ?? false;

    const isGhost = variant === "ghost";
    const isVertical = orientation === "vertical";
    const isHorizontal = orientation === "horizontal";

    const styles = twMerge(
      theme.baseStyle,
      isVertical && theme["vertical"],
      isHorizontal && theme["horizontal"],
      isVertical && !isGhost && theme["verticalAppearance"],
      isHorizontal && !isGhost && theme["horizontalAppearance"],
      fullWidth && theme["fullWidth"],
      className,
    );

    return (
      <div {...rest} ref={ref} className={styles}>
        {React.Children.map(
          children,
          (child) =>
            React.isValidElement(child) &&
            React.cloneElement(child, {
              variant,
              size,
              color,
              ripple,
              rounded,
              fullWidth,
              ...child.props,
            } as ButtonProps),
        )}
      </div>
    );
  },
);

ButtonGroup.displayName = "MaterialTailwind.ButtonGroup";

export default ButtonGroup;
