// packages/material-tailwind-solid/src/components/Radio/index.tsx
// utils
import classnames from "classnames";
import Ripple from "material-ripple-effects";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { Component, JSX } from "solid-js";
import { Show, createMemo, mergeProps, splitProps } from "solid-js";
import type {
  color,
  disabled,
  icon,
  label,
  objectType,
  ripple,
} from "../../types/components/checkbox";

export interface RadioProps {
  color?: color;
  label?: label;
  icon?: icon;
  ripple?: ripple;
  class?: string;
  disabled?: disabled;
  containerProps?: objectType;
  labelProps?: objectType;
  iconProps?: objectType;
  containerRef?: HTMLDivElement;
}

export const Radio: Component<JSX.InputHTMLAttributes<HTMLInputElement> & RadioProps> = (props) => {
  // 1. init
  const theme = useTheme();
  // 2. set default props
  const mergedProps = mergeProps(() => theme().radio.defaultProps, props);

  // 3. set ripple effect instance
  const rippleEffect = new Ripple();
  const [radioProps, rest] = splitProps(mergedProps, [
    "color",
    "label",
    "icon",
    "ripple",
    "class",
    "disabled",
    "containerProps",
    "labelProps",
    "iconProps",
    "containerRef",
  ]);
  // 4. set styles
  const cProps = createMemo(() => {
    const { valid, styles } = theme().radio;
    const { base, colors } = styles;
    const rootClasses = classnames(objectsToString(base.root), {
      [objectsToString(base.disabled)]: radioProps.disabled,
    });
    const containerClasses = twMerge(
      classnames(objectsToString(base.container)),
      radioProps.containerProps?.className,
    );
    const inputClasses = twMerge(
      classnames(
        objectsToString(base.input),
        objectsToString(colors[findMatch(valid.colors, radioProps.color, "blue")]),
      ),
      radioProps.class,
    );
    const labelClasses = twMerge(
      classnames(objectsToString(base.label)),
      radioProps.labelProps?.className,
    );
    const radioIconClasses = classnames(
      classnames(objectsToString(base.icon)),
      colors[findMatch(valid.colors, radioProps.color, "blue")].color,
      radioProps.iconProps?.className,
    );
    return { radioIconClasses, rootClasses, containerClasses, inputClasses, labelClasses };
  });

  return (
    <div ref={radioProps.containerRef} class={cProps().rootClasses}>
      <label
        {...radioProps.containerProps}
        class={cProps().containerClasses}
        for={rest.id || "radio"}
        onMouseDown={(e) => {
          const onMouseDown = radioProps.containerProps?.onMouseDown;

          if (radioProps.ripple) {
            rippleEffect.create(e, "dark");
          }

          return typeof onMouseDown === "function" && onMouseDown(e);
        }}
      >
        <input
          {...rest}
          type="radio"
          disabled={radioProps.disabled}
          class={cProps().inputClasses}
          id={rest.id || "radio"}
        />
        <span class={cProps().radioIconClasses}>
          <Show
            when={radioProps.icon}
            fallback={
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-3.5 w-3.5"
                viewBox="0 0 16 16"
                fill="currentColor"
              >
                <circle data-name="ellipse" cx="8" cy="8" r="8" />
              </svg>
            }
          >
            {radioProps.icon}
          </Show>
        </span>
      </label>
      <Show when={radioProps.label}>
        <label {...radioProps.labelProps} class={cProps().labelClasses} for={rest.id || "radio"}>
          {radioProps.label}
        </label>
      </Show>
    </div>
  );
};

export default Radio;

// packages/react/src/components/radio.tsx
import React from "react";

// @utils
import { twMerge } from "tailwind-merge";

// @hooks
import { useTheme } from "@context";

// @theme
import { radioTheme } from "@theme";

// @types
import type { BaseComponent } from "@types";

export interface RadioProps extends BaseComponent<"input"> {
  as?: React.ElementType;
  icon?: React.ReactNode;
  className?: string;
  baseClassName?: string;
  iconClassName?: string;
  inputRef?: React.RefObject<HTMLInputElement>;
  iconRef?: React.RefObject<HTMLSpanElement>;
}

/**
 * @remarks
 * [Documentation](http://www.material-tailwind.com/docs/react/radio) •
 * [Props Definition](https://www.material-tailwind.com/docs/react/radio#radio-props) •
 * [Theming Guide](https://www.material-tailwind.com/docs/react/radio#radio-theme)
 *
 * @example
 * ```tsx
 * import { Radio, Typography } from "@material-tailwind/react";
 *
 * export default function Example() {
 *  return (
 *    <div className="flex gap-10">
 *      <div className="flex items-center gap-2">
 *        <Radio id="html" name="type" />
 *        <Typography as="label" htmlFor="html" className="text-gray-500 dark:text-gray-400">
 *          HTML
 *        </Typography>
 *      </div>
 *      <div className="flex items-center gap-2">
 *        <Radio id="react" name="type" />
 *        <Typography as="label" htmlFor="react" className="text-gray-500 dark:text-gray-400">
 *          React
 *        </Typography>
 *      </div>
 *    </div>
 *  )
 * }
 * ```
 */
export const Radio = React.forwardRef<HTMLDivElement, RadioProps>(
  (
    {
      as,
      color,
      icon,
      className,
      baseClassName,
      iconClassName,
      inputRef,
      iconRef,
      ...rest
    },
    ref,
  ) => {
    const Element = as ?? "div";
    const innerID = React.useId();
    const contextTheme = useTheme();
    const theme = contextTheme?.radio ?? radioTheme;
    const defaultProps = contextTheme?.radio?.defaultProps;

    icon ??= (defaultProps?.icon as RadioProps["icon"]) ?? (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        className="h-2 w-2"
        viewBox="0 0 16 16"
        fill="currentColor"
      >
        <circle data-name="ellipse" cx="8" cy="8" r="8" />
      </svg>
    );
    color ??= (defaultProps?.color as RadioProps["color"]) ?? "primary";

    const baseStyles = twMerge(theme.baseStyle, baseClassName);

    const inputStyles = twMerge(
      theme.inputStyle,
      theme.inputColor[color],
      className,
    );

    const iconStyles = twMerge(
      theme.iconStyle,
      theme.iconColor[color],
      iconClassName,
    );

    return (
      <Element ref={ref} className={baseStyles}>
        <input
          {...rest}
          ref={inputRef}
          type="radio"
          className={inputStyles}
          id={rest?.id || innerID}
        />
        <span ref={iconRef} className={iconStyles}>
          {icon}
        </span>
      </Element>
    );
  },
);

Radio.displayName = "MaterialTailwind.Radio";

export default Radio;
