// packages/material-tailwind-react/src/components/Tooltip/index.tsx
import React from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  offset as fuiOffset,
  flip,
  shift,
  autoUpdate,
  useFloating,
  useInteractions,
  useRole,
  useDismiss,
  useClick,
  useHover,
  useFocus,
  FloatingPortal,
  useMergeRefs,
} from "@floating-ui/react";

// framer-motion
import {AnimatePresence, m} from "framer-motion";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import merge from "deepmerge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { NewAnimatePresenceProps } from "../../types/generic";
import type {
  open,
  handler,
  content,
  interactive,
  placement,
  offset,
  dismiss,
  animate,
  className,
  children,
} from "../../types/components/popover";
import {
  propTypesOpen,
  propTypesHandler,
  propTypesContent,
  propTypesInteractive,
  propTypesPlacement,
  propTypesOffset,
  propTypesDismiss,
  propTypesAnimate,
  propTypesClassName,
  propTypesChildren,
} from "../../types/components/popover";

// @ts-ignore
export interface TooltipProps extends React.ComponentProps<"div"> {
  open?: open;
  handler?: handler;
  content?: content;
  interactive?: interactive;
  placement?: placement;
  offset?: offset;
  dismiss?: dismiss;
  animate?: animate;
  className?: className;
  children: children | React.ComponentProps<any>;
}

export const Tooltip = React.forwardRef<HTMLDivElement, TooltipProps>(
  (
    {
      open,
      handler,
      content,
      interactive,
      placement,
      offset,
      dismiss,
      animate,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    // 1. init
    const { tooltip } = useTheme();
    const {
      defaultProps,
      styles: { base },
    } = tooltip;
    const [internalOpen, setInternalOpen] = React.useState(false);

    // 2. set default props
    open = open ?? internalOpen;
    handler = handler ?? setInternalOpen;
    interactive = interactive ?? defaultProps.interactive;
    placement = placement ?? defaultProps.placement;
    offset = offset ?? defaultProps.offset;
    dismiss = dismiss ?? defaultProps.dismiss;
    animate = animate ?? defaultProps.animate;
    className = className ?? defaultProps.className;

    // 3. set styles
    const tooltipClasses = twMerge(classnames(objectsToString(base)), className);

    // 4. set animation
    const animation = {
      unmount: {
        opacity: 0,
      },
      mount: {
        opacity: 1,
      },
    };
    const appliedAnimation = merge(animation, animate);

    // 5. set @floating-ui
    const { x, y, reference, floating, strategy, refs, update, context } = useFloating({
      open,
      onOpenChange: handler,
      middleware: [fuiOffset(offset), flip(), shift()],
      placement,
    });

    const { getReferenceProps, getFloatingProps } = useInteractions([
      useClick(context, {
        enabled: interactive,
      }),
      useFocus(context),
      useHover(context),
      useRole(context, { role: "tooltip" }),
      useDismiss(context, dismiss),
    ]);

    React.useEffect(() => {
      if (refs.reference.current && refs.floating.current && open) {
        return autoUpdate(refs.reference.current, refs.floating.current, update);
      }
    }, [open, update, refs.reference, refs.floating]);

    const mergedRef = useMergeRefs([ref, floating]);
    const childMergedRef = useMergeRefs([ref, reference]);

    // 6. Create an instance of AnimatePresence because of the types issue with the children
    const NewAnimatePresence: React.FC<NewAnimatePresenceProps> = AnimatePresence;

    // 7. return
    return (
      <>
        {typeof children === "string" ? (
          <span
            {...getReferenceProps({
              ref: childMergedRef,
            })}
          >
            {children}
          </span>
        ) : (
          React.cloneElement(children, {
            ...getReferenceProps({
              ...children?.props,
              ref: childMergedRef,
            }),
          })
        )}
        <FloatingPortal>
          <NewAnimatePresence>
            {open && (
              <m.div
                {...getFloatingProps({
                  ...rest,
                  ref: mergedRef,
                  className: tooltipClasses,
                  style: {
                    position: strategy,
                    top: y ?? "",
                    left: x ?? "",
                  },
                })}
                initial="unmount"
                exit="unmount"
                animate={open ? "mount" : "unmount"}
                variants={appliedAnimation}
              >
                {content}
              </m.div>
            )}
          </NewAnimatePresence>
        </FloatingPortal>
      </>
    );
  },
);

Tooltip.propTypes = {
  open: propTypesOpen,
  handler: propTypesHandler,
  content: propTypesContent,
  interactive: propTypesInteractive,
  placement: PropTypes.oneOf(propTypesPlacement),
  offset: propTypesOffset,
  dismiss: propTypesDismiss,
  animate: propTypesAnimate,
  className: propTypesClassName,
  children: propTypesChildren,
};

Tooltip.displayName = "MaterialTailwind.Tooltip";

export default Tooltip;

// packages/material-tailwind-solid/src/components/Tooltip/index.tsx
// @floating-ui

// framer-motion

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import { autoUpdate, flip, offset as fuiOffset, shift } from "@floating-ui/dom";
import { Motion } from "@motionone/solid";
import { useFloating } from "solid-floating-ui";
import type { JSX, JSXElement, ParentComponent } from "solid-js";
import { Show, createMemo, createSignal, mergeProps, splitProps } from "solid-js";
import type {
  animate,
  content,
  dismiss,
  handler,
  interactive,
  offset,
  open,
  placement,
} from "../../types/components/popover";

export interface TooltipProps {
  open?: open;
  handler?: handler;
  content?: content;
  interactive?: interactive;
  placement?: placement;
  offset?: offset;
  dismiss?: dismiss;
  animate?: animate;
  children: JSXElement;
}

export const Tooltip: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & TooltipProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();
  const [internalOpen, setInternalOpen] = createSignal(false);
  const [reference, setReference] = createSignal<HTMLElement>();
  const [floating, setFloating] = createSignal<HTMLElement>();

  // 2. set animation
  const defaultAnimation = {
    unmount: {
      opacity: 0,
    },
    mount: {
      opacity: 1,
    },
  };

  // 3. set default props
  const mergedProps = mergeProps(
    () => theme().popover.defaultProps,
    { animate: defaultAnimation, handler: setInternalOpen, open: internalOpen },
    props,
  );

  const [tooltipProps, rest] = splitProps(mergedProps, [
    "open",
    "handler",
    "content",
    "interactive",
    "placement",
    "offset",
    "dismiss",
    "animate",
    "children",
    "class",
  ]);

  // 3. set styles
  const styles = createMemo(() => {
    const {
      styles: { base },
    } = theme().tooltip;
    const tooltipClasses = twMerge(classnames(objectsToString(base)), tooltipProps.class);
    return { tooltipClasses };
  });

  // 5. set @floating-ui
  const position = useFloating(reference, floating, {
    placement: mergedProps.placement,
    strategy: "absolute",
    whileElementsMounted: autoUpdate,
    middleware: [flip(), shift(), fuiOffset(mergedProps.offset)],
  });

  // const { x, y, reference, floating, strategy, refs, update, context } = useFloating({
  //   open,
  //   onOpenChange: handler,
  //   middleware: [fuiOffset(offset), flip(), shift()],
  //   placement,
  // });

  // const { getReferenceProps, getFloatingProps } = useInteractions([
  //   useClick(context, {
  //     enabled: interactive,
  //   }),
  //   useFocus(context),
  //   useHover(context),
  //   useRole(context, { role: "tooltip" }),
  //   useDismiss(context, dismiss),
  // ]);

  // React.useEffect(() => {
  //   if (refs.reference.current && refs.floating.current && open) {
  //     return autoUpdate(refs.reference.current, refs.floating.current, update);
  //   }
  // }, [open, update, refs.reference, refs.floating]);

  // const mergedRef = useMergeRefs([ref, floating]);
  // const childMergedRef = useMergeRefs([ref, reference]);

  // 6. Create an instance of AnimatePresence because of the types issue with the children
  const animate = createMemo(() =>
    tooltipProps.open() ? mergedProps.animate.mount : mergedProps.animate.unmount,
  );

  // 7. return
  return (
    <>
      <span
        ref={setReference}
        onMouseEnter={() => tooltipProps.handler(true)}
        onMouseLeave={() => tooltipProps.handler(false)}
        //toDo add Close on keydown
      >
        {tooltipProps.children}
      </span>

      <Show when={tooltipProps.open()}>
        <Motion.div
          {...rest}
          ref={setFloating}
          style={{
            position: position?.strategy,
            width: "max-content",
            top: position?.y + "px" ?? 0,
            left: position?.x + "px" ?? 0,
            "z-index": 9999,
          }}
          class={styles().tooltipClasses}
          initial={tooltipProps.animate.unmount}
          exit={tooltipProps.animate.unmount}
          animate={animate()}
        >
          {tooltipProps.content}
        </Motion.div>
      </Show>
    </>
  );
};
export default Tooltip;
