// packages/material-tailwind-react/src/components/Checkbox/index.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import Ripple from "material-ripple-effects";
import classnames from "classnames";
import findMatch from "utils/findMatch";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const Checkbox = forwardRef(
  ({ color, label, icon, ripple, className, containerProps, labelProps, ...rest }, ref) => {
    // 1. init
    const { checkbox } = useTheme();
    const { defaultProps, valid, styles } = checkbox;
    const { base, colors } = styles;

    // 2. set default props
    color = color ?? defaultProps.color;
    ripple = ripple ?? defaultProps.ripple;
    className = className ?? defaultProps.className;

    // 3. set ripple effect instance
    const rippleEffect = ripple !== undefined && new Ripple();

    // 4. set styles
    const rootClasses = classnames(objectsToString(base.root));
    const containerClasses = classnames(objectsToString(base.container), containerProps?.className);
    const inputClasses = classnames(
      objectsToString(base.input),
      objectsToString(colors[findMatch(valid.colors, color, "light-blue")]),
      className,
    );
    const labelClasses = classnames(objectsToString(base.label), labelProps?.className);

    return (
      <div ref={ref} className={rootClasses}>
        <label
          {...containerProps}
          className={containerClasses}
          htmlFor={rest.id || "checkbox"}
          onMouseDown={(e) => {
            const onMouseDown = containerProps?.onMouseDown;

            if (ripple) {
              rippleEffect.create(e, "dark");
            }

            return typeof onMouseDown === "function" && onMouseDown();
          }}
        >
          <input {...rest} type="checkbox" className={inputClasses} id={rest.id || "checkbox"} />
          <div className="text-white absolute top-2/4 left-2/4 -translate-y-2/4 -translate-x-2/4 pointer-events-none opacity-0 peer-checked:opacity-100 transition-opacity">
            {icon || (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-3.5 w-3.5"
                viewBox="0 0 20 20"
                fill="currentColor"
                stroke="currentColor"
                strokeWidth={1}
              >
                <path
                  fillRule="evenodd"
                  d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                  clipRule="evenodd"
                />
              </svg>
            )}
          </div>
        </label>
        {label && (
          <label {...labelProps} className={labelClasses} htmlFor={rest.id || "checkbox"}>
            {label}
          </label>
        )}
      </div>
    );
  },
);

Checkbox.propTypes = {
  color: PropTypes.oneOf([
    "blue-grey",
    "grey",
    "brown",
    "deep-orange",
    "orange",
    "amber",
    "yellow",
    "lime",
    "light-green",
    "green",
    "teal",
    "cyan",
    "light-blue",
    "blue",
    "indigo",
    "deep-purple",
    "purple",
    "pink",
    "red",
  ]),
  label: PropTypes.string,
  icon: PropTypes.node,
  ripple: PropTypes.bool,
  className: PropTypes.string,
  containerProps: PropTypes.instanceOf(Object),
  labelProps: PropTypes.instanceOf(Object),
};

Checkbox.displayName = "Checkbox";

export { Checkbox };
export default Checkbox;

// packages/material-tailwind-solid/src/components/Checkbox/index.tsx
// utils
import Ripple from "material-ripple-effects";
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type {
  color,
  label,
  icon,
  ripple,
  disabled,
  objectType,
} from "../../types/components/checkbox";
import type { JSX, Component } from "solid-js";
import { mergeProps, splitProps, createMemo, Show } from "solid-js";

export interface CheckboxProps {
  color?: color;
  label?: label;
  icon?: icon;
  ripple?: ripple;
  disabled?: disabled;
  containerProps?: objectType;
  labelProps?: objectType;
  iconProps?: objectType;
  containerRef?: HTMLDivElement;
}

export const Checkbox: Component<JSX.InputHTMLAttributes<HTMLInputElement> & CheckboxProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props

  const mergedProps = mergeProps(() => theme().checkbox.defaultProps, props);
  const [checkboxProps, rest] = splitProps(mergedProps, [
    "color",
    "label",
    "icon",
    "ripple",
    "disabled",
    "containerProps",
    "labelProps",
    "iconProps",
    "containerRef",
    "class",
  ]);
  // 3. set ripple effect instance
  const rippleEffect = new Ripple();

  // 4. set styles
  const cProps = createMemo(() => {
    const { valid, styles } = theme().checkbox;
    const { base, colors } = styles;
    const rootClasses = classnames(objectsToString(styles.base.root), {
      [objectsToString(styles.base.disabled)]: checkboxProps.disabled,
    });

    const containerClasses = twMerge(
      classnames(objectsToString(styles.base.container)),
      checkboxProps.containerProps?.class,
    );

    const inputClasses = twMerge(
      classnames(
        objectsToString(base),
        objectsToString(colors[findMatch(valid.colors, checkboxProps.color, "blue")]),
      ),
      checkboxProps.class,
    );

    const labelClasses = twMerge(
      classnames(objectsToString(styles.base.label)),
      checkboxProps.labelProps?.class,
    );

    const iconContainerClasses = twMerge(
      classnames(objectsToString(styles.base.icon)),
      checkboxProps.iconProps?.class,
    );

    return { iconContainerClasses, labelClasses, inputClasses, containerClasses, rootClasses };
  });
  return (
    <div ref={props.containerRef} class={cProps().rootClasses}>
      <label
        {...checkboxProps.containerProps}
        class={cProps().containerClasses}
        for={rest.id || "checkbox"}
        onMouseDown={(e) => {
          const onMouseDown = checkboxProps.containerProps?.onMouseDown;

          if (checkboxProps.ripple) {
            rippleEffect.create(e, "dark");
          }

          return typeof onMouseDown === "function" && onMouseDown(e);
        }}
      >
        <input
          {...rest}
          type="checkbox"
          disabled={checkboxProps.disabled}
          class={cProps().inputClasses}
          id={rest.id || "checkbox"}
        />
        <span class={cProps().iconContainerClasses}>
          <Show when={!checkboxProps.icon} fallback={<>{checkboxProps.icon}</>}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-3.5 w-3.5"
              viewBox="0 0 20 20"
              fill="currentColor"
              stroke="currentColor"
              stroke-width={1}
            >
              <path
                fill-rule="evenodd"
                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                clip-rule="evenodd"
              />
            </svg>
          </Show>
        </span>
      </label>
      <Show when={!!checkboxProps.label}>
        <label
          {...checkboxProps.labelProps}
          class={cProps().labelClasses}
          for={rest.id || "checkbox"}
        >
          {checkboxProps.label as string}
        </label>
      </Show>
    </div>
  );
};

export default Checkbox;
