// packages/material-tailwind-solid/src/context/theme.tsx
import { deepmerge } from "deepmerge-ts";
import theme from "../theme/index";
import combineMerge from "../utils/combineMerge";
import { createContext, createMemo, useContext } from "solid-js";
import type { ParentComponent } from "solid-js";
export type Theme = typeof theme;
const MaterialTailwindTheme = createContext(theme);

const ThemeProvider: ParentComponent<IThemeProvider> = (props) => {
  const mergedValue = createMemo(() =>
    props.value ? deepmerge(theme, props.value, { arrayMerge: combineMerge }) : theme,
  );

  return (
    <MaterialTailwindTheme.Provider value={mergedValue()}>
      {props.children}
    </MaterialTailwindTheme.Provider>
  );
};

const useTheme = () => useContext(MaterialTailwindTheme);

interface IThemeProvider {
  value?: typeof theme;
}

export { MaterialTailwindTheme, ThemeProvider, useTheme };

// packages/material-tailwind-react/src/context/theme.js
import React, { createContext, useContext } from "react";
import PropTypes from "prop-types";
import merge from "deepmerge";
import theme from "../theme/index";
import combineMerge from "../utils/combineMerge";

const MaterialTailwindTheme = createContext(theme);

MaterialTailwindTheme.displayName = "MaterialTailwindThemeProvider";

function ThemeProvider({ value = theme, children }) {
  const mergedValue = React.useMemo(() => merge(theme, value, { arrayMerge: combineMerge }), [value]);

  return (
    <MaterialTailwindTheme.Provider value={mergedValue}>{children}</MaterialTailwindTheme.Provider>
  );
}

const useTheme = () => useContext(MaterialTailwindTheme);

ThemeProvider.propTypes = {
  value: PropTypes.instanceOf(Object),
  children: PropTypes.node.isRequired,
};

export { MaterialTailwindTheme, ThemeProvider, useTheme };
