// packages/material-tailwind-react/src/components/Navbar/index.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import findMatch from "utils/findMatch";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const Navbar = forwardRef(
  ({ variant, color, shadow, blurred, fullWidth, className, children, ...rest }, ref) => {
    // 1. init
    const { navbar } = useTheme();
    const { defaultProps, valid, styles } = navbar;
    const { base, variants } = styles;

    // 2. set default props
    variant = variant ?? defaultProps.variant;
    color = color ?? defaultProps.color;
    shadow = shadow ?? defaultProps.shadow;
    blurred = blurred ?? defaultProps.blurred;
    fullWidth = fullWidth ?? defaultProps.fullWidth;
    className = className ?? defaultProps.className;

    // 3. set styles
    const navbarRoot = classnames(objectsToString(base.initial), {
      [objectsToString(base.shadow)]: shadow,
      [objectsToString(base.blurred)]: blurred && color === "white",
      [objectsToString(base.fullWidth)]: fullWidth,
    });
    const navbarVariant = classnames(
      objectsToString(
        variants[findMatch(valid.variants, variant, "filled")][
          findMatch(valid.colors, color, "white")
        ],
      ),
    );
    const navbarClasses = classnames(navbarRoot, navbarVariant, className);

    // 4. return
    return (
      <nav {...rest} ref={ref} className={navbarClasses}>
        {children}
      </nav>
    );
  },
);

Navbar.propTypes = {
  variant: PropTypes.oneOf(["filled", "gradient"]),
  color: PropTypes.oneOf([
    "transparent",
    "white",
    "blue-grey",
    "grey",
    "brown",
    "deep-orange",
    "orange",
    "amber",
    "yellow",
    "lime",
    "light-green",
    "green",
    "teal",
    "cyan",
    "light-blue",
    "blue",
    "indigo",
    "deep-purple",
    "purple",
    "pink",
    "red",
  ]),
  shadow: PropTypes.bool,
  blurred: PropTypes.bool,
  fullWidth: PropTypes.bool,
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Navbar.displayName = "Navbar";

export { Navbar };
export default Navbar;

// packages/material-tailwind-solid/src/components/Navbar/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { JSX, ParentComponent } from "solid-js";
import { createMemo, mergeProps, splitProps } from "solid-js";
import type {
  blurred,
  children,
  color,
  fullWidth,
  shadow,
  variant,
} from "../../types/components/navbar";

export interface NavbarProps {
  variant?: variant;
  color?: color;
  shadow?: shadow;
  blurred?: blurred;
  fullWidth?: fullWidth;
  children: children;
}

export const Navbar: ParentComponent<JSX.HTMLAttributes<HTMLElement> & NavbarProps> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().navbar.defaultProps, props);
  const [navbarProps, rest] = splitProps(mergedProps, [
    "variant",
    "color",
    "shadow",
    "blurred",
    "fullWidth",
    "class",
    "children",
  ]);

  // 3. set styles
  const cProps = createMemo(() => {
    const { valid, styles } = theme().navbar;
    const { base, variants } = styles;
    const navbarRoot = classnames(objectsToString(base.navbar.initial), {
      [objectsToString(base.navbar.shadow)]: navbarProps.shadow,
      [objectsToString(base.navbar.blurred)]: navbarProps.blurred && navbarProps.color === "white",
      [objectsToString(base.navbar.fullWidth)]: navbarProps.fullWidth,
    });
    const navbarVariant = classnames(
      objectsToString(
        variants[findMatch(valid.variants, navbarProps.variant, "filled")][
          findMatch(valid.colors, navbarProps.color, "white")
        ],
      ),
    );
    const navbarClasses = twMerge(classnames(navbarRoot, navbarVariant), navbarProps.class);

    return { navbarRoot, navbarVariant, navbarClasses };
  });
  // 4. return
  return (
    <nav {...rest} class={cProps().navbarClasses}>
      {props.children}
    </nav>
  );
};

export default Navbar;
