// packages/react/src/components/navbar.tsx
"use client";

import * as React from "react";

// @context
import { useTheme } from "@context";

// @types
import type { BaseComponent } from "@types";

// @utils
import { twMerge } from "tailwind-merge";

// @theme
import { navbarTheme } from "@theme";

// card root
export interface NavbarProps
  extends Omit<BaseComponent<HTMLElement>, "size" | "color"> {
  as?: React.ElementType;
  className?: string;
  color?: "default" | BaseComponent<HTMLElement>["color"];
  children?: React.ReactNode;
}

/**
 * @remarks
 * [Documentation](http://www.material-tailwind.com/docs/react/navbar) •
 * [Props Definition](https://www.material-tailwind.com/docs/react/navbar#navbar-props) •
 * [Theming Guide](https://www.material-tailwind.com/docs/react/navbar#navbar-theme)
 */

export const Navbar = React.forwardRef<HTMLElement, NavbarProps>(
  ({ as, color, variant, className, children, ...rest }, ref) => {
    const Element = as || "nav";
    const contextTheme = useTheme();
    const theme = contextTheme.navbar || navbarTheme;
    const defaultProps = theme.defaultProps;

    color ??= (defaultProps?.color as NavbarProps["color"]) ?? "default";
    variant ??= (defaultProps?.variant as NavbarProps["variant"]) ?? "solid";

    const styles = twMerge(
      theme.baseStyle,
      theme.variant[variant][color],
      className,
    );

    return (
      <Element {...rest} ref={ref} className={styles}>
        {children}
      </Element>
    );
  },
);

Navbar.displayName = "MaterialTailwind.Navbar";

export default Navbar;

// packages/material-tailwind-solid/src/components/Navbar/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { JSX, ParentComponent } from "solid-js";
import { createMemo, mergeProps, splitProps } from "solid-js";
import type {
  blurred,
  children,
  color,
  fullWidth,
  shadow,
  variant,
} from "../../types/components/navbar";

export interface NavbarProps {
  variant?: variant;
  color?: color;
  shadow?: shadow;
  blurred?: blurred;
  fullWidth?: fullWidth;
  children: children;
}

export const Navbar: ParentComponent<JSX.HTMLAttributes<HTMLElement> & NavbarProps> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().navbar.defaultProps, props);
  const [navbarProps, rest] = splitProps(mergedProps, [
    "variant",
    "color",
    "shadow",
    "blurred",
    "fullWidth",
    "class",
    "children",
  ]);

  // 3. set styles
  const cProps = createMemo(() => {
    const { valid, styles } = theme().navbar;
    const { base, variants } = styles;
    const navbarRoot = classnames(objectsToString(base.navbar.initial), {
      [objectsToString(base.navbar.shadow)]: navbarProps.shadow,
      [objectsToString(base.navbar.blurred)]: navbarProps.blurred && navbarProps.color === "white",
      [objectsToString(base.navbar.fullWidth)]: navbarProps.fullWidth,
    });
    const navbarVariant = classnames(
      objectsToString(
        variants[findMatch(valid.variants, navbarProps.variant, "filled")][
          findMatch(valid.colors, navbarProps.color, "white")
        ],
      ),
    );
    const navbarClasses = twMerge(classnames(navbarRoot, navbarVariant), navbarProps.class);

    return { navbarRoot, navbarVariant, navbarClasses };
  });
  // 4. return
  return (
    <nav {...rest} class={cProps().navbarClasses}>
      {props.children}
    </nav>
  );
};

export default Navbar;
