// packages/material-tailwind-solid/src/components/Breadcrumbs/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { separator, fullWidth } from "../../types/components/breadcrumbs";

import { For, Show, children, createMemo, mergeProps, splitProps } from "solid-js";
import type { ParentComponent, JSX } from "solid-js";

export interface BreadcrumbsProps {
  separator?: separator;
  fullWidth?: fullWidth;
}

export const Breadcrumbs: ParentComponent<
  JSX.OlHTMLAttributes<HTMLOListElement> & BreadcrumbsProps
> = (props) => {
  // ({ separator, fullWidth, className, children, ...rest }, ref) => {
  // 1. init
  const theme = useTheme();
  const [breadcrumbProps, rest] = splitProps(props, ["separator", "fullWidth", "class"]);
  const defaultProps = mergeProps(() => theme().breadcrumbs.defaultProps, breadcrumbProps);
  // const {
  //   defaultProps,
  //   styles: { base },
  // } = breadcrumbs;
  // 2. set default props
  // separator = separator ?? defaultProps.separator;
  // fullWidth = fullWidth ?? defaultProps.fullWidth;
  // className = className ?? defaultProps.className;

  // 3. set styles
  const breadcrumbsRootClasses = createMemo(() =>
    classnames(objectsToString(theme().breadcrumbs.styles.base.root.initial), {
      [objectsToString(theme().breadcrumbs.styles.base.root.fullWidth)]: defaultProps.fullWidth,
    }),
  );
  const breadcrumbsListClasses = createMemo(() =>
    twMerge(classnames(objectsToString(theme().breadcrumbs.styles.base.list)), defaultProps.class),
  );
  const breadcrumbsItemClasses = createMemo(() =>
    classnames(objectsToString(theme().breadcrumbs.styles.base.item.initial)),
  );
  const breadcrumbsSeparatorClasses = createMemo(() =>
    classnames(objectsToString(theme().breadcrumbs.styles.base.separator)),
  );

  const listItems = children(() => props.children);
  // 4. return
  return (
    <nav aria-label="breadcrumb" class={breadcrumbsRootClasses()}>
      <ol {...rest} class={breadcrumbsListClasses()}>
        <For each={listItems.toArray()}>
          {(item, index) => {
            return (
              <li
                class={classnames(breadcrumbsItemClasses(), {
                  [objectsToString(theme().breadcrumbs.styles.base.item.disabled)]:
                    //@ts-ignore --> disabled does not exist on type string, number,...
                    item?.disabled,
                })}
              >
                {item}
                <Show when={index() !== listItems.toArray().length - 1}>
                  <span class={breadcrumbsSeparatorClasses()}>{defaultProps.separator}</span>
                </Show>
              </li>
            );
          }}
        </For>
      </ol>
    </nav>
  );
};

// Breadcrumbs.propTypes = {
//   separator: propTypesSeparator,
//   fullWidth: propTypesFullWidth,
//   className: propTypesClassName,
//   children: propTypesChildren,
// };

// Breadcrumbs.displayName = "MaterialTailwind.Breacrumbs";

export default Breadcrumbs;

// packages/material-tailwind-react/src/components/Breadcrumbs/index.js
import { forwardRef, isValidElement, Children } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import objectsToString from "utils/objectsToString";

// context
import { useTheme } from "context/theme";

const Breadcrumbs = forwardRef(({ separator, fullWidth, className, children, ...rest }, ref) => {
  // 1. init
  const { breadcrumbs } = useTheme();
  const {
    defaultProps,
    styles: { base },
  } = breadcrumbs;

  // 2. set default props
  separator = separator ?? defaultProps.separator;
  fullWidth = fullWidth ?? defaultProps.fullWidth;
  className = className ?? defaultProps.className;

  // 3. set styles
  const breadcrumbsRootClasses = classnames(objectsToString(base.root.initial), {
    [objectsToString(base.root.fullWidth)]: fullWidth,
  });
  const breadcrumbsListClasses = classnames(objectsToString(base.list), className);
  const breadcrumbsItemClasses = classnames(objectsToString(base.item.initial));
  const breadcrumbsSeparatorClasses = classnames(objectsToString(base.separator));

  // 4. return
  return (
    <nav aria-label="breadcrumb" className={breadcrumbsRootClasses}>
      <ol {...rest} ref={ref} className={breadcrumbsListClasses}>
        {Children.map(children, (child, index) => {
          if (isValidElement(child)) {
            return (
              <li
                className={classnames(breadcrumbsItemClasses, {
                  [objectsToString(base.item.disabled)]: child?.props?.disabled,
                })}
                disabled={child?.props?.disabled}
              >
                {child}
                {index !== Children.count(children) - 1 && (
                  <span aria-hidden="true" className={breadcrumbsSeparatorClasses}>
                    {separator}
                  </span>
                )}
              </li>
            );
          }
          return null;
        })}
      </ol>
    </nav>
  );
});

Breadcrumbs.propTypes = {
  separator: PropTypes.node,
  fullWidth: PropTypes.bool,
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

Breadcrumbs.displayName = "Breacrumb";

export default Breadcrumbs;
