// packages/material-tailwind-solid/src/components/Popover/index.tsx
// @floating-ui
// import {
//   autoUpdate,
//   flip,
//   offset as fuiOffset,
//   shift,
//   useClick,
//   useDismiss,
//   useFloating,
//   useId,
//   useInteractions,
//   useRole,
// } from "@floating-ui/react";

// utils

// context
import { useTheme } from "../../context/theme";
import { PopoverContextProvider, usePopover } from "./PopoverContext";

// types
import type {
  animate,
  children,
  dismiss,
  handler,
  offset as offsetType,
  open,
  placement,
} from "../../types/components/popover";

// popover components
import { autoUpdate, flip, offset, shift } from "@floating-ui/dom";
import { useFloating } from "solid-floating-ui";
import type { ParentComponent } from "solid-js";
import { createMemo, createSignal, createUniqueId, mergeProps } from "solid-js";
import type { PopoverContentProps } from "./PopoverContent";
import { PopoverContent } from "./PopoverContent";
import type { PopoverHandlerProps } from "./PopoverHandler";
import { PopoverHandler } from "./PopoverHandler";

export interface PopoverProps {
  open?: open;
  handler?: handler;
  placement?: placement;
  offset?: offsetType;
  dismiss?: dismiss;
  animate?: animate;
  children: children;
}

const Popover: ParentComponent<PopoverProps> = (props) => {
  // = ({
  //   open,
  //   handler,
  //   placement,
  //   offset,
  //   dismiss,
  //   animate,
  //   children,
  // }: PopoverProps) => {
  // 1. init
  const theme = useTheme();

  const [internalOpen, setInternalOpen] = createSignal(false);
  const [reference, setReference] = createSignal<HTMLElement>();
  const [floating, setFloating] = createSignal<HTMLElement>();

  const defaultAnimation = {
    unmount: {
      opacity: 0,
    },
    mount: {
      opacity: 1,
    },
  };
  const mergedProps = mergeProps(
    () => theme().popover.defaultProps,
    { animate: defaultAnimation, handler: setInternalOpen, open: internalOpen },
    props,
  );

  // 5. set @floating-ui
  const position = useFloating(reference, floating, {
    placement: mergedProps.placement,
    strategy: "absolute",
    whileElementsMounted: autoUpdate,
    middleware: [flip(), shift(), offset(mergedProps.offset)],
  });

  const id = createUniqueId();

  const contextValue = createMemo(() => ({
    open: mergedProps.open,
    handler: mergedProps.handler,
    position,
    reference,
    setReference,
    floating,
    setFloating,
    appliedAnimation: mergedProps.animate,
    labelId: `${id}-label`,
    descriptionId: `${id}-description`,
  }));

  // 6. return
  return (
    <PopoverContextProvider value={contextValue}>{mergedProps.children}</PopoverContextProvider>
  );
};

export type { PopoverHandlerProps, PopoverContentProps };
export { Popover, PopoverHandler, PopoverContent, usePopover };
export default Object.assign(Popover, { Handler: PopoverHandler, Content: PopoverContent });

// legacy/material-tailwind-react/src/components/Popover/index.tsx
import React from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  offset as fuiOffset,
  flip,
  shift,
  autoUpdate,
  useFloating,
  useInteractions,
  useRole,
  useDismiss,
  useId,
  useClick,
} from "@floating-ui/react";

// utils
import merge from "deepmerge";

// context
import { useTheme } from "../../context/theme";
import { PopoverContextProvider, usePopover } from "./PopoverContext";

// types
import type {
  open,
  handler,
  placement,
  offset,
  dismiss,
  animate,
  children,
} from "../../types/components/popover";
import {
  propTypesOpen,
  propTypesHandler,
  propTypesPlacement,
  propTypesOffset,
  propTypesDismiss,
  propTypesAnimate,
  propTypesChildren,
} from "../../types/components/popover";

// popover components
import { PopoverHandler, PopoverHandlerProps } from "./PopoverHandler";
import { PopoverContent, PopoverContentProps } from "./PopoverContent";

export interface PopoverProps {
  open?: open;
  handler?: handler;
  placement?: placement;
  offset?: offset;
  dismiss?: dismiss;
  animate?: animate;
  children: children;
}

const Popover = ({
  open,
  handler,
  placement,
  offset,
  dismiss,
  animate,
  children,
}: PopoverProps) => {
  // 1. init
  const { popover } = useTheme();
  const { defaultProps } = popover;
  const [internalOpen, setInternalOpen] = React.useState(false);

  // 2. set default props
  open = open ?? internalOpen;
  handler = handler ?? setInternalOpen;
  placement = placement ?? defaultProps.placement;
  offset = offset ?? defaultProps.offset;
  dismiss = dismiss ?? defaultProps.dismiss;
  animate = animate ?? defaultProps.animate;

  // 4. set animation
  const animation = {
    unmount: {
      opacity: 0,
    },
    mount: {
      opacity: 1,
    },
  };
  const appliedAnimation = merge(animation, animate);

  // 5. set @floating-ui
  const { x, y, reference, floating, strategy, refs, update, context } = useFloating({
    open,
    onOpenChange: handler,
    middleware: [fuiOffset(offset), flip(), shift()],
    placement,
  });

  const id = useId();
  const labelId = `${id}-label`;
  const descriptionId = `${id}-description`;

  const { getReferenceProps, getFloatingProps } = useInteractions([
    useClick(context),
    useRole(context),
    useDismiss(context, dismiss),
  ]);

  React.useEffect(() => {
    if (refs.reference.current && refs.floating.current && open) {
      return autoUpdate(refs.reference.current, refs.floating.current, update);
    }
  }, [open, update, refs.reference, refs.floating]);

  const contextValue = React.useMemo(
    () => ({
      open,
      strategy,
      x,
      y,
      context,
      reference,
      floating,
      getReferenceProps,
      getFloatingProps,
      appliedAnimation,
      labelId,
      descriptionId,
    }),
    [
      open,
      strategy,
      x,
      y,
      context,
      reference,
      floating,
      getFloatingProps,
      getReferenceProps,
      appliedAnimation,
      labelId,
      descriptionId,
    ],
  );

  // 6. return
  return <PopoverContextProvider value={contextValue}>{children}</PopoverContextProvider>;
};

Popover.propTypes = {
  open: propTypesOpen,
  handler: propTypesHandler,
  placement: PropTypes.oneOf(propTypesPlacement),
  offset: propTypesOffset,
  dismiss: propTypesDismiss,
  animate: propTypesAnimate,
  children: propTypesChildren,
};

Popover.displayName = "MaterialTailwind.Popover";

export type { PopoverHandlerProps, PopoverContentProps };
export { Popover, PopoverHandler, PopoverContent, usePopover };
export default Object.assign(Popover, { Handler: PopoverHandler, Content: PopoverContent });
