// packages/material-tailwind-react/src/components/Menu/MenuList.tsx
import React from "react";

// framer-motion
import { FloatingPortal, FloatingOverlay, FloatingFocusManager } from "@floating-ui/react";
import { AnimatePresence, motion } from "framer-motion";

// utils
import mergeRefs from "react-merge-refs";
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { useMenu } from "./MenuContext";

// types
import type { NewAnimatePresenceProps } from "../../types/generic";
import type { className, children } from "../../types/components/menu";
import { propTypesClassName, propTypesChildren } from "../../types/components/menu";

export interface MenuListProps extends React.ComponentProps<"ul"> {
  className?: className;
  children: children;
}

export const MenuList = React.forwardRef<HTMLUListElement, MenuListProps>(
  ({ children, className, ...rest }, ref) => {
    // 1. init
    const { menu } = useTheme();
    const {
      styles: { base },
    } = menu;
    const {
      open,
      handler,
      setInternalOpen,
      strategy,
      x,
      y,
      floating,
      listItemsRef,
      getFloatingProps,
      getItemProps,
      appliedAnimation,
      lockScroll,
      context,
    } = useMenu();

    // 2. set default props
    className = className ?? "";

    // 3. set styles
    const menuClasses = twMerge(classnames(objectsToString(base.menu)), className);

    // 4. set refs
    const mergedRef = React.useMemo(() => mergeRefs([ref, floating]), [ref, floating]);

    // 5. create an instance of AnimatePresence because of the types issue with the children
    const NewAnimatePresence: React.FC<NewAnimatePresenceProps> = AnimatePresence;

    // 6. menu component
    const menuComponent = (
      <motion.ul
        {...getFloatingProps({
          ...rest,
          ref: mergedRef,
          className: menuClasses,
          style: {
            position: strategy,
            top: y ?? "",
            left: x ?? "",
          },
        })}
        initial="unmount"
        exit="unmount"
        animate={open ? "mount" : "unmount"}
        variants={appliedAnimation}
      >
        {React.Children.map(
          children,
          (child, index) =>
            React.isValidElement(child) &&
            React.cloneElement(
              child,
              getItemProps({
                ...child.props,
                onClick: (e) => {
                  const onClickFunction = child.props?.onClick;

                  if (typeof onClickFunction === "function" && handler) {
                    onClickFunction(e);
                  } else if (typeof onClickFunction === "function") {
                    setInternalOpen(false);
                    onClickFunction(e);
                  }

                  setInternalOpen(false);
                },
                ref(nodeElement) {
                  listItemsRef.current[index] = nodeElement;
                },
              }),
            ),
        )}
      </motion.ul>
    );

    // 7. return
    return (
      <FloatingPortal>
        <NewAnimatePresence>
          {open && (
            <>
              {lockScroll ? (
                <FloatingOverlay lockScroll>
                  <FloatingFocusManager context={context}>{menuComponent}</FloatingFocusManager>
                </FloatingOverlay>
              ) : (
                <FloatingFocusManager context={context}>{menuComponent}</FloatingFocusManager>
              )}
            </>
          )}
        </NewAnimatePresence>
      </FloatingPortal>
    );
  },
);

MenuList.propTypes = {
  className: propTypesClassName,
  children: propTypesChildren,
};

MenuList.displayName = "MaterialTailwind.MenuList";

export default MenuList;

// packages/material-tailwind-solid/src/components/Menu/MenuList.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { useMenu } from "./MenuContext";

// types
import { Motion } from "@motionone/solid";
import type { JSX, ParentComponent } from "solid-js";
import { Show, createMemo, createUniqueId, mergeProps } from "solid-js";
import type { children } from "../../types/components/menu";

export interface MenuListProps {
  dismissible?: boolean;
  children: children;
}

export const MenuList: ParentComponent<JSX.HTMLAttributes<HTMLUListElement> & MenuListProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();
  const context = useMenu();
  // 2. set default props
  const mergedProps = mergeProps(() => theme().menu.defaultProps, props);

  // 3. set styles
  const menuClasses = createMemo(() =>
    twMerge(classnames(objectsToString(theme().menu.styles.base.menu)), mergedProps.class),
  );

  // 5. create an instance of AnimatePresence because of the types issue with the children
  const id = createUniqueId();

  // 6. menu component
  return (
    <div
      id={mergedProps.id ?? id}
      ref={(el) => context()?.setFloating(el)}
      style={{
        position: context()?.position?.strategy,
        width: "max-content",
        top: context()?.position?.y + "px" ?? 0,
        left: context()?.position?.x + "px" ?? 0,
      }}
      aria-hidden={!context()?.open()}
      data-floating-menu-list
    >
      <Show
        when={
          context()?.open() &&
          (!context()?.nested ||
            (context()?.nested && context()?.parentContext()?.activeItem() === context()?.parentID))
        }
      >
        <Motion.ul
          {...mergedProps}
          class={menuClasses()}
          initial={mergedProps.animate.unmount}
          exit={mergedProps.animate.unmount}
          animate={context()?.open() ? mergedProps.animate.mount : mergedProps.animate.unmount}
        >
          {props.children}
        </Motion.ul>
      </Show>
    </div>
  );
};
export default MenuList;
