// packages/material-tailwind-solid/src/components/Menu/MenuContext.tsx
// types
import type { Accessor, ParentComponent } from "solid-js";
import { createContext, useContext } from "solid-js";
import type { children, contextValue } from "../../types/components/menu";
type ContextAccessor = Accessor<null | contextValue>;
export interface MenuContextProviderProps {
  value: ContextAccessor;
  children: children;
}

export const MenuContext = createContext<ContextAccessor>(() => null);

export function useMenu() {
  const context = useContext(MenuContext);

  if (!context()) {
    throw new Error(
      "useMenu() must be used within a Menu. It happens when you use MenuCore, MenuHandler, MenuItem or MenuList components outside the Menu component.",
    );
  }

  return context;
}
export function useIsNestedMenu() {
  const context = useContext(MenuContext);
  if (!context()) return false;
  return true;
}
export function useParentContext() {
  const context = useContext(MenuContext);
  if (!context())
    return {
      parentContext: () => undefined,
    };
  return {
    parentContext: () => context(),
  };
}
export const MenuContextProvider: ParentComponent<MenuContextProviderProps> = (props) => {
  return <MenuContext.Provider {...props}>{props.children}</MenuContext.Provider>;
};

export function getRootContext(ctx: ContextAccessor): ContextAccessor {
  if (ctx()?.parentContext() && ctx()?.parentContext)
    return getRootContext(ctx()!.parentContext as ContextAccessor);
  return ctx;
}

// packages/material-tailwind-react/src/components/Menu/MenuContext.tsx
import React from "react";

// types
import type { contextValue, children } from "../../types/components/menu";
import { propTypesContextValue, propTypesChildren } from "../../types/components/menu";

export interface MenuContextProviderProps {
  value: contextValue;
  children: children;
}

export const MenuContext = React.createContext<null | contextValue>(null);
MenuContext.displayName = "MaterialTailwind.MenuContext";

export function useMenu() {
  const context = React.useContext(MenuContext);

  if (!context) {
    throw new Error(
      "useMenu() must be used within a Menu. It happens when you use MenuCore, MenuHandler, MenuItem or MenuList components outside the Menu component.",
    );
  }

  return context;
}

export const MenuContextProvider = ({ value, children }: MenuContextProviderProps) => {
  return <MenuContext.Provider value={value}>{children}</MenuContext.Provider>;
};

MenuContextProvider.prototypes = {
  value: propTypesContextValue,
  children: propTypesChildren,
};

MenuContextProvider.displayName = "MaterialTailwind.MenuContextProvider";
