// packages/material-tailwind-solid/src/components/Menu/MenuCore.tsx
// context
import { useTheme } from "../../context/theme";
import { MenuContext, useIsNestedMenu, useParentContext } from "./MenuContext";

// types
import { autoUpdate, flip, offset, shift } from "@floating-ui/dom";
import { clearAllBodyScrollLocks, disableBodyScroll } from "body-scroll-lock";
import { useFloating } from "solid-floating-ui";
import type { Accessor, JSX, ParentComponent } from "solid-js";
import {
  createEffect,
  createMemo,
  createSignal,
  createUniqueId,
  mergeProps,
  onCleanup,
  onMount,
} from "solid-js";
import type {
  animate,
  children,
  contextValue,
  dismiss,
  handler,
  lockScroll,
  offset as offsetType,
  open,
  placement,
  treeRefType,
} from "../../types/components/menu";
import type { animation } from "../../types/generic";

export interface MenuProps {
  open?: open;
  handler?: handler;
  placement?: placement;
  offset?: offsetType;
  dismiss?: dismiss;
  animate?: animate;
  lockScroll?: lockScroll;
  children: children;
  allowHover?: boolean;
}

export const MenuCore: ParentComponent<JSX.ButtonHTMLAttributes<HTMLButtonElement> & MenuProps> = (
  props,
) => {
  let clickOutsideRef!: HTMLDivElement;

  // 1. init
  const theme = useTheme();
  const nested = useIsNestedMenu();
  const parentCtx = useParentContext();
  const [activeItem, setActiveItem] = createSignal<string>("");
  const [internalOpen, setInternalOpen] = createSignal(false);
  const [tree, setTree] = createSignal<treeRefType[]>([]);
  const [menuHandlerId, setMenuHandlerId] = createSignal<string>();
  const [reference, setReference] = createSignal<HTMLElement>();
  const [floating, setFloating] = createSignal<HTMLElement>();
  const id = createUniqueId();
  // 3. set animation
  const defaultAnimation: animation = {
    unmount: {
      opacity: 0,
      transformOrigin: "top",
      transform: "scale(0.95)",
      transition: { duration: 0.2, easing: [0.4, 0, 0.2, 1] },
    },
    mount: {
      opacity: 1,
      transformOrigin: "top",
      transform: "scale(1)",
      transition: { duration: 0.2, easing: [0.4, 0, 0.2, 1] },
    },
  };

  const mergedProps = mergeProps(
    () => theme().menu.defaultProps,
    { animate: defaultAnimation },
    props,
  );

  const position = useFloating(reference, floating, {
    placement: mergedProps.placement,
    strategy: "absolute",
    whileElementsMounted: autoUpdate,
    middleware: [flip(), shift(), offset(mergedProps.offset)],
  });

  onMount(() => {
    //close  menu when click outside
    window.addEventListener("click", function (e) {
      if (!clickOutsideRef.contains(e.target as Node)) {
        ctx().handler(false);
      }
    });
  });
  createEffect(() => {
    if (!props.lockScroll) return;
    //disable scroll if lockScroll
    if (open() && !nested) disableBodyScroll(clickOutsideRef);
    //enable scroll when menu is closed
    if (!open() && !nested) clearAllBodyScrollLocks();
  });
  onCleanup(() => {
    window.removeEventListener("click", () => undefined);
    if (props.lockScroll) clearAllBodyScrollLocks();
  });

  const open = createMemo(() => mergedProps.open ?? internalOpen());
  const ctx: Accessor<contextValue> = createMemo(() => ({
    open,
    handler: mergedProps.handler ?? setInternalOpen,
    parentID: id,
    reference,
    setReference,
    setFloating,
    position,
    parentRef: reference,
    nested,
    allowHover: mergedProps.allowHover ?? nested,
    activeItem,
    setActiveItem,
    tree,
    addToTree: (el: treeRefType) => setTree((prev) => [...prev, el]),
    removeFromTree: (id: string) => setTree((prev) => prev.filter((el) => el.id !== id)),
    menuHandlerId,
    setMenuHandlerId,
    parentContext: parentCtx.parentContext,
  }));
  // 5. return
  return (
    <MenuContext.Provider value={ctx}>
      <div ref={clickOutsideRef} tabIndex={-1} aria-labelledby="menuwrapper">
        {mergedProps.children}
      </div>
    </MenuContext.Provider>
  );
};
export default MenuCore;

// packages/material-tailwind-react/src/components/Menu/MenuCore.tsx
import React from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  useFloating,
  useFloatingTree,
  useFloatingNodeId,
  useFloatingParentNodeId,
  FloatingNode,
  useInteractions,
  offset as fuiOffset,
  flip,
  shift,
  useHover,
  useClick,
  useRole,
  useDismiss,
  safePolygon,
  useListNavigation,
  useTypeahead,
  useMergeRefs,
  autoUpdate,
} from "@floating-ui/react";

// utils
import merge from "deepmerge";

// context
import { useTheme } from "../../context/theme";
import { MenuContextProvider } from "./MenuContext";

// types
import type {
  open,
  handler,
  placement,
  offset,
  dismiss,
  animate,
  lockScroll,
  children,
} from "../../types/components/menu";
import {
  propTypesOpen,
  propTypesHandler,
  propTypesPlacement,
  propTypesOffset,
  propTypesDismiss,
  propTypesAnimate,
  propTypesLockScroll,
  propTypesChildren,
} from "../../types/components/menu";

export interface MenuProps {
  open?: open;
  handler?: handler;
  placement?: placement;
  offset?: offset;
  dismiss?: dismiss;
  animate?: animate;
  lockScroll?: lockScroll;
  children: children;
}

export const MenuCore = React.forwardRef<
  HTMLButtonElement,
  MenuProps & React.HTMLProps<HTMLButtonElement>
>(({ open, handler, placement, offset, dismiss, animate, lockScroll, children }, ref) => {
  // 1. init
  const { menu } = useTheme();
  const { defaultProps } = menu;
  const [internalOpen, setInternalOpen] = React.useState(false);

  // 2. set default props
  open = open ?? internalOpen;
  handler = handler ?? setInternalOpen;
  placement = placement ?? defaultProps.placement;
  offset = offset ?? defaultProps.offset;
  dismiss = dismiss ?? defaultProps.dismiss;
  animate = animate ?? defaultProps.animate;
  lockScroll = lockScroll ?? defaultProps.lockScroll;

  // 3. set animation
  const animation = {
    unmount: {
      opacity: 0,
      transformOrigin: "top",
      transform: "scale(0.95)",
      transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
    },
    mount: {
      opacity: 1,
      transformOrigin: "top",
      transform: "scale(1)",
      transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
    },
  };
  const appliedAnimation = merge(animation, animate);

  // 4. set @floating-ui
  const [activeIndex, setActiveIndex] = React.useState<number | null>(null);
  const [allowHover, setAllowHover] = React.useState(false);
  const listItemsRef = React.useRef<Array<HTMLButtonElement | null>>([]);
  const listContentRef = React.useRef(
    React.Children.map(children, (child) =>
      React.isValidElement(child) ? child.props.label : null,
    ) as Array<string | null>,
  );

  const tree = useFloatingTree();
  const nodeId = useFloatingNodeId();
  const parentId = useFloatingParentNodeId();
  const nested = parentId != null;

  const { x, y, strategy, refs, context } = useFloating<HTMLButtonElement>({
    open,
    nodeId,
    placement,
    onOpenChange: handler,
    middleware: [fuiOffset(offset), flip(), shift()],
    whileElementsMounted: autoUpdate,
  });

  const { getReferenceProps, getFloatingProps, getItemProps } = useInteractions([
    useHover(context, {
      handleClose: safePolygon({
        restMs: 25,
        blockPointerEvents: true,
      }),
      enabled: nested && allowHover,
      delay: { open: 75 },
    }),
    useClick(context, {
      toggle: !nested || !allowHover,
      event: "mousedown",
      ignoreMouse: nested,
    }),
    useRole(context, { role: "menu" }),
    useDismiss(context),
    useListNavigation(context, {
      listRef: listItemsRef,
      activeIndex,
      nested,
      onNavigate: setActiveIndex,
    }),
    useTypeahead(context, {
      listRef: listContentRef,
      onMatch: open ? setActiveIndex : undefined,
      activeIndex,
    }),
  ]);

  React.useEffect(() => {
    function handleTreeClick() {
      handler(false);
    }

    function onSubMenuOpen(event: { nodeId: string; parentId: string }) {
      if (event.nodeId !== nodeId && event.parentId === parentId) {
        handler(false);
      }
    }

    tree?.events.on("click", handleTreeClick);
    tree?.events.on("menuopen", onSubMenuOpen);

    return () => {
      tree?.events.off("click", handleTreeClick);
      tree?.events.off("menuopen", onSubMenuOpen);
    };
  }, [tree, nodeId, parentId]);

  React.useEffect(() => {
    if (open) {
      tree?.events.emit("menuopen", {
        parentId,
        nodeId,
      });
    }
  }, [tree, open, nodeId, parentId]);

  React.useEffect(() => {
    function onPointerMove({ pointerType }: PointerEvent) {
      if (pointerType !== "touch") {
        setAllowHover(true);
      }
    }

    function onKeyDown() {
      setAllowHover(false);
    }

    window.addEventListener("pointermove", onPointerMove, {
      once: true,
      capture: true,
    });

    window.addEventListener("keydown", onKeyDown, true);
    return () => {
      window.removeEventListener("pointermove", onPointerMove, {
        capture: true,
      });

      window.removeEventListener("keydown", onKeyDown, true);
    };
  }, [allowHover]);

  const referenceRef = useMergeRefs([refs.setReference, ref]);

  const contextValue = React.useMemo(
    () => ({
      open,
      handler,
      setInternalOpen,
      strategy,
      x,
      y,
      reference: referenceRef,
      floating: refs.setFloating,
      listItemsRef,
      getReferenceProps,
      getFloatingProps,
      getItemProps,
      appliedAnimation,
      lockScroll,
      context,
      activeIndex,
      tree,
      allowHover,
      nested,
      setActiveIndex,
    }),
    [
      open,
      handler,
      setInternalOpen,
      strategy,
      x,
      y,
      referenceRef,
      refs,
      getReferenceProps,
      getFloatingProps,
      getItemProps,
      appliedAnimation,
      lockScroll,
      context,
      activeIndex,
      tree,
      allowHover,
      nested,
      setActiveIndex,
    ],
  );

  // 5. return
  return (
    <MenuContextProvider value={contextValue}>
      <FloatingNode id={nodeId}>{children}</FloatingNode>
    </MenuContextProvider>
  );
});

MenuCore.propTypes = {
  open: propTypesOpen,
  handler: propTypesHandler,
  placement: PropTypes.oneOf(propTypesPlacement),
  offset: propTypesOffset,
  dismiss: propTypesDismiss,
  animate: propTypesAnimate,
  lockScroll: propTypesLockScroll,
  children: propTypesChildren,
};

MenuCore.displayName = "MaterialTailwind.MenuCore";

export default MenuCore;
