// packages/material-tailwind-react/src/components/Tabs/index.tsx
import React from "react";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { TabsContextProvider, useTabs } from "./TabsContext";

// tabs components
import { Tab, TabProps } from "./Tab";
import { TabsBody, TabsBodyProps } from "./TabsBody";
import { TabsHeader, TabsHeaderProps } from "./TabsHeader";
import { TabPanel, TabPanelProps } from "./TabPanel";

// types
import type { id, value, className, orientation, children } from "../../types/components/tabs";
import {
  propTypesId,
  propTypesValue,
  propTypesClassName,
  propTypesOrientation,
  propTypesChildren,
} from "../../types/components/tabs";

export interface TabsProps extends React.ComponentProps<"div" | any> {
  id: id;
  value: value;
  orientation?: orientation;
  className?: className;
  children: children;
}

const Tabs = React.forwardRef<HTMLDivElement, TabsProps>(
  ({ id, value, className, orientation, children, ...rest }, ref) => {
    // 1. init
    const { tabs } = useTheme();
    const { defaultProps, styles } = tabs;

    // 2. set default props
    className = className ?? defaultProps.className;
    orientation = orientation ?? defaultProps.orientation;

    // 3. set styles
    const tabsClasses = twMerge(
      classnames(objectsToString(styles.base), {
        [styles[orientation] && objectsToString(styles[orientation])]: orientation,
      }),
      className,
    );

    // 4. return
    return (
      <TabsContextProvider id={id} value={value} orientation={orientation}>
        <div {...rest} ref={ref} className={tabsClasses}>
          {children}
        </div>
      </TabsContextProvider>
    );
  },
);

Tabs.propTypes = {
  id: propTypesId,
  value: propTypesValue,
  className: propTypesClassName,
  orientation: propTypesOrientation,
  children: propTypesChildren,
};

Tabs.displayName = "MaterialTailwind.Tabs";

export type { TabProps, TabsBodyProps, TabsHeaderProps, TabPanelProps };
export { Tabs, Tab, TabsBody, TabsHeader, TabPanel, useTabs };
export default Object.assign(Tabs, { Tab, Body: TabsBody, Header: TabsHeader, Panel: TabPanel });

// packages/material-tailwind-solid/src/components/Tabs/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { TabsContextProvider, useTabs } from "./TabsContext";

// tabs components
import type { TabProps } from "./Tab";
import { Tab } from "./Tab";
import type { TabPanelProps } from "./TabPanel";
import { TabPanel } from "./TabPanel";
import type { TabsBodyProps } from "./TabsBody";
import { TabsBody } from "./TabsBody";
import type { TabsHeaderProps } from "./TabsHeader";
import { TabsHeader } from "./TabsHeader";

// types
import type { JSX, ParentComponent } from "solid-js";
import { createMemo, mergeProps, splitProps } from "solid-js";
import type { children, id, orientation, value } from "../../types/components/tabs";

export interface TabsProps {
  id: id;
  value: value;
  orientation?: orientation;
  children: children;
}

const Tabs: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & TabsProps> = (props) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(() => theme().tabs.defaultProps, props);
  const [tabProps, rest] = splitProps(mergedProps, [
    "id",
    "value",
    "orientation",
    "children",
    "class",
  ]);

  // 3. set styles
  const styles = createMemo(() => {
    const { styles } = theme().tabs;
    const tabsClasses = twMerge(
      classnames(objectsToString(styles.base), {
        [styles[tabProps.orientation] && objectsToString(styles[tabProps.orientation])]:
          tabProps.orientation,
      }),
      tabProps.class,
    );
    return { tabsClasses };
  });

  // 4. return
  return (
    <TabsContextProvider
      id={tabProps.id}
      defaultValue={tabProps.value}
      orientation={tabProps.orientation}
    >
      <div {...rest} class={styles().tabsClasses}>
        {tabProps.children}
      </div>
    </TabsContextProvider>
  );
};

export type { TabProps, TabsBodyProps, TabsHeaderProps, TabPanelProps };
export { Tabs, Tab, TabsBody, TabsHeader, TabPanel, useTabs };
export default Object.assign(Tabs, { Tab, Body: TabsBody, Header: TabsHeader, Panel: TabPanel });
