// packages/material-tailwind-react/src/components/Tabs/TabsBody.js
import React, { forwardRef } from "react";
import PropTypes from "prop-types";

// utils
import classnames from "classnames";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

const TabsBody = forwardRef(({ className, children, ...rest }, ref) => {
  // 1. init
  const { tabsBody } = useTheme();
  const {
    defaultProps,
    styles: { base },
  } = tabsBody;

  // 2. set default props
  className = className ?? defaultProps.className;

  // 3. set styles
  const tabsBodyClasses = classnames(objectsToString(base), className);

  // 4. return
  return (
    <div {...rest} ref={ref} className={tabsBodyClasses}>
      {children}
    </div>
  );
});

TabsBody.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

TabsBody.displayName = "TabsBody";

export default TabsBody;

// packages/material-tailwind-solid/src/components/Tabs/TabsBody.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { useTabs } from "./TabsContext";

// types
import type { JSX, ParentComponent } from "solid-js";
import { createEffect, createMemo, mergeProps, splitProps } from "solid-js";
import type { animate, children } from "../../types/components/tabs";

export interface TabsBodyProps {
  animate?: animate;
  children: children;
}

export const TabsBody: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & TabsBodyProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();

  // 2. set default props
  const mergedProps = mergeProps(
    () => theme().tabsBody.defaultProps,
    { animate: mainAnimation },
    props,
  );
  const [tabProps, rest] = splitProps(mergedProps, ["animate", "children", "class"]);
  const [, { setAnimation }] = useTabs();

  // 3. set styles
  const styles = createMemo(() => {
    const {
      styles: { base },
    } = theme().tabsBody;
    const tabsBodyClasses = twMerge(classnames(objectsToString(base)), tabProps.class);
    return { tabsBodyClasses };
  });

  // 4. set animation
  createEffect(() => {
    setAnimation(tabProps.animate);
  });

  // 5. return
  return (
    <div {...rest} class={styles().tabsBodyClasses}>
      {tabProps.children}
    </div>
  );
};

export default TabsBody;

const mainAnimation = {
  initial: {
    opacity: 0,
    position: "absolute",
    top: "0",
    left: "0",
    zIndex: 1,
    transition: { duration: 0 },
  },
  unmount: {
    opacity: 0,
    position: "absolute",
    top: "0",
    left: "0",
    zIndex: 1,
    transition: { duration: 0.5, times: [0.4, 0, 0.2, 1] },
  },
  mount: {
    opacity: 1,
    position: "relative",
    zIndex: 2,
    transition: { duration: 0.5, times: [0.4, 0, 0.2, 1] },
  },
};
