// packages/material-tailwind-react/src/components/Select/index.tsx
import React from "react";
import PropTypes from "prop-types";

// @floating-ui
import {
  useFloating,
  offset as fuiOffset,
  flip,
  useListNavigation,
  useTypeahead,
  useInteractions,
  useRole,
  useClick,
  useDismiss,
  FloatingFocusManager,
  autoUpdate,
  size as fuiSize,
  FloatingOverlay,
} from "@floating-ui/react";

// framer-motion
import { AnimatePresence, m, useIsomorphicLayoutEffect } from "framer-motion";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import merge from "deepmerge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { SelectContextProvider, usePrevious, useSelect } from "./SelectContext";

// types
import type { NewAnimatePresenceProps } from "../../types/generic";
import type {
  variant,
  color,
  size,
  label,
  error,
  success,
  arrow,
  value,
  onChange,
  selected,
  offset,
  dismiss,
  animate,
  lockScroll,
  labelProps,
  menuProps,
  className,
  disabled,
  name,
  children,
  containerProps,
} from "../../types/components/select";
import {
  propTypesVariant,
  propTypesColor,
  propTypesSize,
  propTypesLabel,
  propTypesError,
  propTypesSuccess,
  propTypesArrow,
  propTypesValue,
  propTypesOnChange,
  propTypesSelected,
  propTypesOffset,
  propTypesDismiss,
  propTypesAnimate,
  propTypesLockScroll,
  propTypesLabelProps,
  propTypesMenuProps,
  propTypesClassName,
  propTypesDisabled,
  propTypesName,
  propTypesChildren,
  propTypesContainerProps,
} from "../../types/components/select";

// select components
import { SelectOption, SelectOptionProps } from "./SelectOption";

export interface SelectProps extends Omit<React.ComponentProps<"div">, "value" | "onChange"> {
  variant?: variant;
  color?: color;
  size?: size;
  label?: label;
  error?: error;
  success?: success;
  arrow?: arrow;
  value?: value;
  onChange?: onChange;
  selected?: selected;
  offset?: offset;
  dismiss?: dismiss;
  animate?: animate;
  lockScroll?: lockScroll;
  labelProps?: labelProps;
  menuProps?: menuProps;
  className?: className;
  disabled?: disabled;
  name?: name;
  children: children;
  containerProps?: containerProps;
}

const Select = React.forwardRef<HTMLDivElement, SelectProps>(
  (
    {
      variant,
      color,
      size,
      label,
      error,
      success,
      arrow,
      value,
      onChange,
      selected,
      offset,
      dismiss,
      animate,
      lockScroll,
      labelProps,
      menuProps,
      className,
      disabled,
      name,
      children,
      containerProps,
      ...rest
    },
    ref,
  ) => {
    // 1. init
    const { select } = useTheme();
    const { defaultProps, valid, styles } = select;
    const { base, variants } = styles;
    const [state, setState] = React.useState<string>("close");

    // 2. set default props
    variant = variant ?? defaultProps.variant;
    color = color ?? defaultProps.color;
    size = size ?? defaultProps.size;
    label = label ?? defaultProps.label;
    error = error ?? defaultProps.error;
    success = success ?? defaultProps.success;
    arrow = arrow ?? defaultProps.arrow;
    value = value ?? defaultProps.value;
    onChange = onChange ?? defaultProps.onChange;
    selected = selected ?? defaultProps.selected;
    offset = offset ?? defaultProps.offset;
    dismiss = dismiss ?? defaultProps.dismiss;
    animate = animate ?? defaultProps.animate;
    labelProps = labelProps ?? defaultProps.labelProps;
    menuProps = menuProps ?? defaultProps.menuProps;
    containerProps =
      merge(containerProps, defaultProps?.containerProps || {}) ?? defaultProps.containerProps;
    className = className ?? defaultProps.className;

    // 3. @floating-ui
    const listItemsRef = React.useRef<Array<HTMLLIElement | null>>([]);
    const listContentRef = React.useRef([
      ...(React.Children.map(children, (child) => {
        const { props }: any = child;
        return props?.value;
      }) ?? []),
    ]);
    const [open, setOpen] = React.useState(false);
    const [activeIndex, setActiveIndex] = React.useState<number | null>(null);
    const [selectedIndex, setSelectedIndex] = React.useState(0);
    const [controlledScrolling, setControlledScrolling] = React.useState(false);
    const prevActiveIndex = usePrevious<number | null>(activeIndex);

    const { x, y, strategy, refs, context } = useFloating({
      placement: "bottom-start",
      open,
      onOpenChange: setOpen,
      whileElementsMounted: autoUpdate,
      middleware: [
        fuiOffset(5),
        flip({ padding: 10 }),
        fuiSize({
          apply({ rects, elements }: any) {
            Object.assign(elements?.floating?.style, {
              width: `${rects?.reference?.width}px`,
              zIndex: 99,
            });
          },
          padding: 20,
        }),
      ],
    });

    React.useEffect(() => {
      setSelectedIndex(Math.max(0, listContentRef.current.indexOf(value) + 1));
    }, [value]);

    const floatingRef = refs.floating;

    const { getReferenceProps, getFloatingProps, getItemProps } = useInteractions([
      useClick(context),
      useRole(context, { role: "listbox" }),
      useDismiss(context, { ...dismiss }),
      useListNavigation(context, {
        listRef: listItemsRef,
        activeIndex,
        selectedIndex,
        onNavigate: setActiveIndex,
        loop: true,
      }),
      useTypeahead(context, {
        listRef: listContentRef,
        activeIndex,
        selectedIndex,
        onMatch: open ? setActiveIndex : setSelectedIndex,
      }),
    ]);

    useIsomorphicLayoutEffect(() => {
      const floating = floatingRef.current;

      if (open && controlledScrolling && floating) {
        const item =
          activeIndex != null
            ? listItemsRef.current[activeIndex]
            : selectedIndex != null
            ? listItemsRef.current[selectedIndex]
            : null;

        if (item && prevActiveIndex != null) {
          const itemHeight = listItemsRef.current[prevActiveIndex]?.offsetHeight ?? 0;
          const floatingHeight = floating.offsetHeight;
          const top = item.offsetTop;
          const bottom = top + itemHeight;

          if (top < floating.scrollTop) {
            floating.scrollTop -= floating.scrollTop - top + 5;
          } else if (bottom > floatingHeight + floating.scrollTop) {
            floating.scrollTop += bottom - floatingHeight - floating.scrollTop + 5;
          }
        }
      }
    }, [open, controlledScrolling, prevActiveIndex, activeIndex]);

    const contextValue = React.useMemo(
      () => ({
        selectedIndex,
        setSelectedIndex,
        listRef: listItemsRef,
        setOpen,
        onChange: onChange || (() => {}),
        activeIndex,
        setActiveIndex,
        getItemProps,
        dataRef: context.dataRef,
      }),
      [selectedIndex, onChange, activeIndex, getItemProps, context.dataRef],
    );

    React.useEffect(() => {
      if (open) {
        setState("open");
      } else if ((!open && selectedIndex) || (!open && value)) {
        setState("withValue");
      } else {
        setState("close");
      }
    }, [open, value, selectedIndex, selected]);

    // 4. set styles
    const selectVariant = variants[findMatch(valid.variants, variant, "outlined")];
    const selectSize = selectVariant.sizes[findMatch(valid.sizes, size, "md")];
    const selectError = selectVariant.error.select;
    const selectSuccess = selectVariant.success.select;
    const selectColor = selectVariant.colors.select[findMatch(valid.colors, color, "blue")];
    const labelError = selectVariant.error.label;
    const labelSuccess = selectVariant.success.label;
    const labelColor = selectVariant.colors.label[findMatch(valid.colors, color, "blue")];
    const stateClasses = selectVariant.states[state];
    const containerClasses = classnames(
      objectsToString(base.container),
      objectsToString(selectSize.container),
      containerProps?.className,
    );
    const selectClasses = twMerge(
      classnames(
        objectsToString(base.select),
        objectsToString(selectVariant.base.select),
        objectsToString(stateClasses.select),
        objectsToString(selectSize.select),
        { [objectsToString(selectColor[state])]: !error && !success },
        { [objectsToString(selectError.initial)]: error },
        { [objectsToString(selectError.states[state])]: error },
        { [objectsToString(selectSuccess.initial)]: success },
        { [objectsToString(selectSuccess.states[state])]: success },
      ),
      className,
    );
    const labelClasses = twMerge(
      classnames(
        objectsToString(base.label),
        objectsToString(selectVariant.base.label),
        objectsToString(stateClasses.label),
        objectsToString(selectSize.label.initial),
        objectsToString(selectSize.label.states[state]),
        { [objectsToString(labelColor[state])]: !error && !success },
        { [objectsToString(labelError.initial)]: error },
        { [objectsToString(labelError.states[state])]: error },
        { [objectsToString(labelSuccess.initial)]: success },
        { [objectsToString(labelSuccess.states[state])]: success },
      ),
      labelProps.className ?? "",
    );
    const arrowClasses = classnames(objectsToString(base.arrow.initial), {
      [objectsToString(base.arrow.active)]: open,
    });
    const menuClasses = twMerge(classnames(objectsToString(base.menu)), menuProps.className ?? "");
    const buttonContentClasses = classnames(
      "absolute top-2/4 -translate-y-2/4",
      variant === "outlined" ? "left-3 pt-0.5" : "left-0 pt-3",
    );

    // 5. set animation
    const animation = {
      unmount: {
        opacity: 0,
        transformOrigin: "top",
        transform: "scale(0.95)",
        transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
      },
      mount: {
        opacity: 1,
        transformOrigin: "top",
        transform: "scale(1)",
        transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
      },
    };
    const appliedAnimation = merge(animation, animate);

    // 6. create an instance of AnimatePresence because of the types issue with the children
    const NewAnimatePresence: React.FC<NewAnimatePresenceProps> = AnimatePresence;

    // 7. validate the controlled and uncontrolled select
    React.useEffect(() => {
      if (value && !onChange) {
        console.error(
          "Warning: You provided a `value` prop to a select component without an `onChange` handler. This will render a read-only select. If the field should be mutable use `onChange` handler with `value` together.",
        );
      }
    }, [value, onChange]);

    // 8. select menu
    const selectMenu = (
      <FloatingFocusManager context={context} modal={false}>
        <m.ul
          {...getFloatingProps({
            ...menuProps,
            ref: refs.setFloating,
            role: "listbox",
            className: menuClasses,
            style: {
              position: strategy,
              top: y ?? 0,
              left: x ?? 0,
              overflow: "auto",
            },
            onPointerEnter(e) {
              const onPointerEnter = menuProps?.onPointerEnter;
              if (typeof onPointerEnter === "function") {
                onPointerEnter(e);
                setControlledScrolling(false);
              }
              setControlledScrolling(false);
            },
            onPointerMove(e) {
              const onPointerMove = menuProps?.onPointerMove;
              if (typeof onPointerMove === "function") {
                onPointerMove(e);
                setControlledScrolling(false);
              }
              setControlledScrolling(false);
            },
            onKeyDown(e) {
              const onKeyDown = menuProps?.onKeyDown;
              if (typeof onKeyDown === "function") {
                onKeyDown(e);
                setControlledScrolling(true);
              }
              setControlledScrolling(true);
            },
          })}
          initial="unmount"
          exit="unmount"
          animate={open ? "mount" : "unmount"}
          variants={appliedAnimation}
        >
          {React.Children.map(
            children,
            (child, index) =>
              React.isValidElement(child) &&
              React.cloneElement(child, {
                ...child.props,
                index: child.props?.index || index + 1,
                id: `material-tailwind-select-${index}`,
              }),
          )}
        </m.ul>
      </FloatingFocusManager>
    );

    // 9. return
    return (
      <SelectContextProvider value={contextValue}>
        <div {...containerProps} ref={ref} className={containerClasses}>
          <button
            type="button"
            {...getReferenceProps({
              ...rest,
              ref: refs.setReference,
              className: selectClasses,
              disabled: disabled,
              name: name,
            })}
          >
            {typeof selected === "function" ? (
              <span className={buttonContentClasses}>
                {selected(children[selectedIndex - 1], selectedIndex - 1)}
              </span>
            ) : value && !onChange ? (
              <span className={buttonContentClasses}>{value}</span>
            ) : (
              <span {...children[selectedIndex - 1]?.props} className={buttonContentClasses} />
            )}
            <div className={arrowClasses}>
              {arrow ?? (
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                  <path
                    fillRule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clipRule="evenodd"
                  />
                </svg>
              )}
            </div>
          </button>
          <label {...labelProps} className={labelClasses}>
            {label}
          </label>
          <NewAnimatePresence>
            {open && (
              <>
                {lockScroll ? (
                  <FloatingOverlay lockScroll>{selectMenu}</FloatingOverlay>
                ) : (
                  selectMenu
                )}
              </>
            )}
          </NewAnimatePresence>
        </div>
      </SelectContextProvider>
    );
  },
);

Select.propTypes = {
  variant: PropTypes.oneOf(propTypesVariant),
  color: PropTypes.oneOf(propTypesColor),
  size: PropTypes.oneOf(propTypesSize),
  label: propTypesLabel,
  error: propTypesError,
  success: propTypesSuccess,
  arrow: propTypesArrow,
  value: propTypesValue,
  onChange: propTypesOnChange,
  selected: propTypesSelected,
  offset: propTypesOffset,
  dismiss: propTypesDismiss,
  animate: propTypesAnimate,
  lockScroll: propTypesLockScroll,
  labelProps: propTypesLabelProps,
  menuProps: propTypesMenuProps,
  className: propTypesClassName,
  disabled: propTypesDisabled,
  name: propTypesName,
  children: propTypesChildren,
  containerProps: propTypesContainerProps,
};

Select.displayName = "MaterialTailwind.Select";

export type { SelectOptionProps };
export { Select, SelectOption as Option, useSelect, usePrevious };
export default Object.assign(Select, { Option: SelectOption });

// packages/material-tailwind-solid/src/components/Select/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";
import { SelectContextProvider, usePrevious, useSelect } from "./SelectContext";

// types

import type { animate, offset } from "../../types/components/select";
import type {
  arrow,
  color,
  containerProps,
  disabled,
  dismiss,
  error,
  label,
  labelProps,
  lockScroll,
  menuProps,
  name,
  onChange,
  selected,
  size,
  success,
  value,
  variant,
} from "../../types/components/select";

// select components
import type { JSX, ParentComponent } from "solid-js";
import { onCleanup, onMount, Match, Show, Switch } from "solid-js";

import { autoUpdate, flip, offset as fuiOffset, shift } from "@floating-ui/dom";
import { Motion } from "@motionone/solid";

import { useFloating } from "solid-floating-ui";
import { createEffect, createMemo, createSignal, mergeProps, splitProps } from "solid-js";
import type { SelectOptionProps } from "./SelectOption";
import { SelectOption } from "./SelectOption";
import { mergeRefs } from "@solid-primitives/refs";
import { clearAllBodyScrollLocks, disableBodyScroll } from "body-scroll-lock";

export interface SelectProps {
  variant?: variant;
  color?: color;
  size?: size;
  label?: label;
  error?: error;
  success?: success;
  arrow?: arrow;
  value?: value;
  onChange?: onChange;
  selected?: selected;
  offset?: offset;
  dismiss?: dismiss;
  animate?: animate;
  lockScroll?: lockScroll;
  labelProps?: labelProps;
  menuProps?: menuProps;
  disabled?: disabled;
  name?: name;
  containerProps?: containerProps;
}

const Select: ParentComponent<JSX.ButtonHTMLAttributes<HTMLButtonElement> & SelectProps> = (
  props,
) => {
  // 1. init
  const theme = useTheme();

  const animation = {
    unmount: {
      opacity: 0,
      transformOrigin: "top",
      transform: "scale(0.95)",
      transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
    },
    mount: {
      opacity: 1,
      transformOrigin: "top",
      transform: "scale(1)",
      transition: { duration: 0.2, times: [0.4, 0, 0.2, 1] },
    },
  };

  const mergedProps = mergeProps(() => theme().select.defaultProps, { animate: animation }, props);

  // 2. set default props

  const [selectProps, rest] = splitProps(mergedProps, [
    "variant",
    "color",
    "size",
    "label",
    "error",
    "success",
    "arrow",
    "value",
    "onChange",
    "selected",
    "offset",
    "dismiss",
    "animate",
    "lockScroll",
    "labelProps",
    "menuProps",
    "disabled",
    "name",
    "children",
    "containerProps",
    "class",
  ]);
  // 3. @floating-ui
  const listItemsRef: HTMLLIElement[] = [];
  const [open, setOpen] = createSignal(false);
  const [activeIndex, setIndex] = createSignal<HTMLLIElement | null>(null);
  const [prevActiveIndex, setPrevActiveIndex] = createSignal<HTMLLIElement | null>(null);
  const [selectedIndex, setSelectedIndex] = createSignal<HTMLLIElement | null>(null);
  const setActiveIndex = (v: HTMLLIElement | null) => {
    setIndex((prev) => {
      setPrevActiveIndex(prev);
      return v;
    });
  };
  // const [controlledScrolling, setControlledScrolling] = createSignal(false);
  const [reference, setReference] = createSignal<HTMLElement>();
  const [floating, setFloating] = createSignal<HTMLUListElement>();
  let containerRef!: HTMLDivElement;
  const position = useFloating(reference, floating, {
    placement: "bottom-start",
    strategy: "absolute",
    whileElementsMounted: autoUpdate,
    middleware: [flip({ padding: 5 }), shift(), fuiOffset(selectProps.offset || 5)],
  });

  const contextValue = createMemo(() => ({
    selectedIndex,
    setSelectedIndex,
    listRef: listItemsRef,
    open,
    setOpen,
    onChange: mergedProps.onChange,
    activeIndex,
    setActiveIndex,
    prevActiveIndex,
    position,
  }));

  const state = createMemo(() => {
    if (open()) return "open";
    if ((!open() && contextValue().selectedIndex()) || (!open() && selectProps.value))
      return "withValue";
    return "close";
  });

  // 4. set styles
  const cProps = createMemo(() => {
    const { valid, styles } = theme().select;
    const { base, variants } = styles;
    const selectVariant = variants[findMatch(valid.variants, selectProps.variant, "outlined")];
    const selectSize = selectVariant.sizes[findMatch(valid.sizes, selectProps.size, "md")];
    const selectError = selectVariant.error.select;
    const selectSuccess = selectVariant.success.select;
    const selectColor =
      selectVariant.colors.select[findMatch(valid.colors, selectProps.color, "blue")];
    const labelError = selectVariant.error.label;
    const labelSuccess = selectVariant.success.label;
    const labelColor =
      selectVariant.colors.label[findMatch(valid.colors, selectProps.color, "blue")];
    const stateClasses = selectVariant.states[state()];
    const containerClasses = classnames(
      objectsToString(base.container),
      objectsToString(selectSize.container),
      selectProps.containerProps?.class,
    );
    const selectClasses = twMerge(
      classnames(
        objectsToString(base.select),
        objectsToString(selectVariant.base.select),
        objectsToString(stateClasses.select),
        objectsToString(selectSize.select),
        { [objectsToString(selectColor[state()])]: !selectProps.error && !selectProps.success },
        { [objectsToString(selectError.initial)]: selectProps.error },
        { [objectsToString(selectError.states[state()])]: selectProps.error },
        { [objectsToString(selectSuccess.initial)]: selectProps.success },
        { [objectsToString(selectSuccess.states[state()])]: selectProps.success },
      ),
      selectProps.class,
    );
    const labelClasses = twMerge(
      classnames(
        objectsToString(base.label),
        objectsToString(selectVariant.base.label),
        objectsToString(stateClasses.label),
        objectsToString(selectSize.label.initial),
        objectsToString(selectSize.label.states[state()]),
        { [objectsToString(labelColor[state()])]: !selectProps.error && !selectProps.success },
        { [objectsToString(labelError.initial)]: selectProps.error },
        { [objectsToString(labelError.states[state()])]: selectProps.error },
        { [objectsToString(labelSuccess.initial)]: selectProps.success },
        { [objectsToString(labelSuccess.states[state()])]: selectProps.success },
      ),
      selectProps.labelProps.class ?? "",
    );
    const arrowClasses = classnames(objectsToString(base.arrow.initial), {
      [objectsToString(base.arrow.active)]: open(),
    });
    const menuClasses = twMerge(
      classnames(objectsToString(base.menu)),
      selectProps.menuProps.class ?? "",
    );
    const buttonContentClasses = classnames(
      "absolute top-2/4 -translate-y-2/4",
      selectProps.variant === "outlined" ? "left-3 pt-0.5" : "left-0 pt-3",
    );
    return {
      buttonContentClasses,
      containerClasses,
      selectClasses,
      labelClasses,
      arrowClasses,
      menuClasses,
      selectVariant,
      selectSize,
      selectError,
      selectSuccess,
      selectColor,
      labelError,
      labelSuccess,
      labelColor,
      stateClasses,
    };
  });

  // 7. validate the controlled and uncontrolled select
  createEffect(() => {
    if (selectProps.value && !props.onChange) {
      console.error(
        "Warning: You provided a `value` prop to a select component without an `onChange` handler. This will render a read-only select. If the field should be mutable use `onChange` handler with `value` together.",
      );
    }
  });

  onMount(() => {
    //close  menu when click outside
    window.addEventListener("click", function (e) {
      if (!containerRef.contains(e.target as Node)) {
        setOpen(false);
      }
    });
  });
  createEffect(() => {
    if (!props.lockScroll) return;
    //disable scroll if lockScroll
    if (open()) disableBodyScroll(containerRef);
    //enable scroll when menu is closed
    if (!open()) clearAllBodyScrollLocks();
  });
  onCleanup(() => {
    window.removeEventListener("click", () => undefined);
    if (props.lockScroll) clearAllBodyScrollLocks();
  });
  // 9. return
  return (
    <SelectContextProvider value={contextValue}>
      <div
        {...selectProps.containerProps}
        class={cProps().containerClasses}
        ref={mergeRefs((el) => {
          if (selectProps.containerProps?.ref) selectProps.containerProps.ref = el;
          containerRef = el;
        })}
      >
        <button
          type="button"
          {...rest}
          disabled={selectProps.disabled}
          class={cProps().selectClasses}
          ref={mergeRefs((el) => setReference(el), rest.ref)}
          onClick={() => setOpen(!open())}
          value={selectProps.value || selectedIndex()?.value + ""}
          name={selectProps.name}
        >
          <Switch
            fallback={
              <span class={cProps().buttonContentClasses}>{selectedIndex()?.innerHTML}</span>
            }
          >
            <Match when={selectProps.selected() !== undefined}>
              <span class={cProps().buttonContentClasses}>
                {selectProps.selected!(selectedIndex(), selectedIndex()?.value + "")}
              </span>
            </Match>
            <Match when={props.value && !props.onChange}>
              <span class={cProps().buttonContentClasses}>{props.value}</span>
            </Match>
          </Switch>

          <Show when={!selectProps.arrow} fallback={selectProps.arrow}>
            <div class={cProps().arrowClasses}>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <path
                  fill-rule="evenodd"
                  d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                  clip-rule="evenodd"
                />
              </svg>
            </div>
          </Show>
        </button>
        <label {...selectProps.labelProps} class={cProps().labelClasses}>
          {selectProps.label}
        </label>

        <Motion.ul
          {...selectProps.menuProps}
          ref={(el) => setFloating(el)}
          role="listbox"
          class={cProps().menuClasses}
          style={{
            position: position.strategy,
            top: position.y + "px" ?? 0,
            left: position.x + "px" ?? 0,
            overflow: "auto",
          }}
          aria-hidden={!open()}
          hidden={!open()}
          // onPointerEnter={(e: PointerEvent) => {
          //   const onPointerEnter = selectProps.menuProps?.onPointerEnter;
          //   if (typeof onPointerEnter === "function") {
          //     onPointerEnter(e);
          //   }
          //   setControlledScrolling(false);
          // }}
          // onPointerMove={(e) => {
          //   const onPointerMove = selectProps.menuProps?.onPointerMove;
          //   if (typeof onPointerMove === "function") {
          //     onPointerMove(e);
          //   }
          //   setControlledScrolling(false);
          // }}
          // onKeyDown={(e) => {
          //   const onKeyDown = selectProps.menuProps?.onKeyDown;
          //   if (typeof onKeyDown === "function") {
          //     onKeyDown(e);
          //     setControlledScrolling(true);
          //   }
          //   setControlledScrolling(true);
          // }}
          initial={selectProps.animate.unmount}
          exit={selectProps.animate.unmount}
          animate={open() ? selectProps.animate.mount : selectProps.animate.unmount}
        >
          {selectProps.children}
        </Motion.ul>
      </div>
    </SelectContextProvider>
  );
};

export type { SelectOptionProps };
export { Select, SelectOption as Option, useSelect, usePrevious };
export default Object.assign(Select, { Option: SelectOption });
