// packages/material-tailwind-solid/src/components/Carousel/index.tsx
// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import { Motion } from "@motionone/solid";
import type { JSX, ParentComponent } from "solid-js";
import {
  For,
  Show,
  children,
  createEffect,
  createMemo,
  createSignal,
  mergeProps,
  onCleanup,
  onMount,
  splitProps,
} from "solid-js";

import type {
  autoplay,
  autoplayDelay,
  loop,
  navigation,
  nextArrow,
  prevArrow,
  slideRef,
  transition,
} from "../../types/components/carousel";

export interface CarouselProps {
  prevArrow?: prevArrow;
  nextArrow?: nextArrow;
  navigation?: navigation;
  autoplay?: autoplay;
  autoplayDelay?: autoplayDelay;
  transition?: transition;
  loop?: loop;
  slideRef?: slideRef;
}

export const Carousel: ParentComponent<JSX.HTMLAttributes<HTMLDivElement> & CarouselProps> = (
  props,
) => {
  // 1. init
  let containerRef!: HTMLDivElement;
  const theme = useTheme();

  const [index, setIndex] = createSignal(1);
  const [prev, setPrev] = createSignal<number | undefined>(undefined);

  const [width, setWidth] = createSignal(0);

  // 2. set default props

  const mergedProps = mergeProps(() => theme().carousel.defaultProps, props);
  const childrens = children(() => props.children);
  const childs = children(() => props.children);
  const childsLength = createMemo(() => childrens.toArray().length);
  const firstIndex = 1;
  const lastIndex = createMemo(() => childsLength() + 1);

  const [motionProps, rest] = splitProps(mergedProps, [
    "prevArrow",
    "nextArrow",
    "navigation",
    "autoplay",
    "autoplayDelay",
    "transition",
    "loop",
    "class",
    "slideRef",
  ]);

  // 3. set styles
  const carouselClasses = createMemo(() =>
    twMerge(classnames(objectsToString(theme().carousel.styles.base.carousel)), motionProps.class),
  );
  const slideClasses = createMemo(() =>
    twMerge(classnames(objectsToString(theme().carousel.styles.base.slide))),
  );

  // 4. set carousel functions

  const handleNext = () => {
    const nextIndex = index() < lastIndex() ? index() + 1 : index();
    setPrev(index());
    setIndex(nextIndex);
  };

  const handlePrev = () => {
    const nextIndex = index() > 0 ? index() - 1 : index();
    setPrev(index());
    setIndex(nextIndex);
  };

  const handleResize = () => {
    setPrev(undefined); //prevent animation on resize
    setWidth(containerRef?.clientWidth);
  };

  onMount(() => window.addEventListener("resize", handleResize));

  onCleanup(() => window.removeEventListener("resize", handleResize));

  createEffect(() => {
    if (!motionProps.autoplay) return;
    const timer = setInterval(() => handleNext(), motionProps.autoplayDelay);
    onCleanup(() => clearInterval(timer));
  });

  // 5. return
  return (
    <div {...rest} ref={containerRef} class={carouselClasses()}>
      <Motion.div
        class="flex"
        ref={motionProps.slideRef}
        animate={{ x: -index() * (width() || containerRef.clientWidth || 0) }}
        transition={{
          ...motionProps.transition,
          duration:
            (index() === childsLength() && prev() === 0) ||
            (index() === 1 && prev() === childsLength() + 1) ||
            !prev()
              ? 0
              : motionProps.transition?.duration,
        }}
        onMotionComplete={() => {
          if (!motionProps.loop) return;
          //Jump to first
          if (index() === childsLength() + 1 && prev() === childsLength()) {
            setPrev(index());
            setIndex(1);
          }
          //Jump to last
          if (index() === 0 && prev() === 1) {
            setPrev(index());
            setIndex(childsLength());
          }
        }}
      >
        <div class={slideClasses()}>{childs.toArray()[childs.toArray().length - 1]}</div>
        <For each={childrens.toArray()}>{(child) => <div class={slideClasses()}>{child}</div>}</For>
        <div class={slideClasses()}>{childs.toArray()[0]}</div>
      </Motion.div>

      {/* arrows */}
      <Show when={!!mergedProps.prevArrow}>
        {mergedProps.prevArrow({
          loop: mergedProps.loop,
          handlePrev,
          activeIndex: index(),
          firstIndex: index() === firstIndex,
        })}
      </Show>
      <Show when={!!mergedProps.nextArrow}>
        {mergedProps.nextArrow({
          loop: mergedProps.loop,
          handleNext,
          activeIndex: index(),
          lastIndex: index() === childsLength(),
        })}
      </Show>
      {/* navigation */}
      <Show when={!!mergedProps.navigation}>
        {mergedProps.navigation({
          setActiveIndex: setIndex,
          activeIndex: index(),
          length: childsLength(),
        })}
      </Show>
    </div>
  );
};

// Carousel.propTypes = {
//   className: propTypesClassName,
//   children: propTypesChildren,
//   nextArrow: propTypesNextArrow,
//   prevArrow: propTypesPrevArrow,
//   navigation: propTypesNavigation,
//   autoplay: propTypesAutoplay,
//   autoplayDelay: propTypesAutoplayDelay,
//   transition: propTypesTransition,
//   loop: propTypesLoop,
//   slideRef: propTypesSlideRef,
// };

// Carousel.displayName = "MaterialTailwind.Carousel";

export default Carousel;

// packages/material-tailwind-react/src/components/Carousel/index.tsx
import React from "react";

// framer-motion
import { animate, m, useMotionValue } from "framer-motion";

// @floating-ui
import { useMergeRefs } from "@floating-ui/react";

// utils
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import {
  children,
  prevArrow,
  nextArrow,
  navigation,
  autoplay,
  autoplayDelay,
  transition,
  loop,
  className,
  slideRef,
  propTypesChildren,
  propTypesClassName,
  propTypesNextArrow,
  propTypesPrevArrow,
  propTypesNavigation,
  propTypesAutoplay,
  propTypesAutoplayDelay,
  propTypesTransition,
  propTypesLoop,
  propTypesSlideRef,
} from "../../types/components/carousel";

export interface CarouselProps extends React.ComponentProps<"div"> {
  children: children;
  prevArrow?: prevArrow;
  nextArrow?: nextArrow;
  navigation?: navigation;
  autoplay?: autoplay;
  autoplayDelay?: autoplayDelay;
  transition?: transition;
  loop?: loop;
  className?: className;
  slideRef?: slideRef;
}

export const Carousel = React.forwardRef<HTMLDivElement, CarouselProps>(
  (
    {
      children,
      prevArrow,
      nextArrow,
      navigation,
      autoplay,
      autoplayDelay,
      transition,
      loop,
      className,
      slideRef,
      ...rest
    },
    ref,
  ) => {
    // 1. init
    const { carousel } = useTheme();
    const {
      defaultProps,
      styles: { base },
    } = carousel;
    const x = useMotionValue(0);
    const containerRef = React.useRef<HTMLDivElement>(null);
    const [index, setIndex] = React.useState(0);
    const childrens: any = React.Children.toArray(children);

    // 2. set default props
    className = className ?? defaultProps.className;
    prevArrow = prevArrow ?? defaultProps.prevArrow;
    nextArrow = nextArrow ?? defaultProps.nextArrow;
    navigation = navigation ?? defaultProps.navigation;
    autoplay = autoplay ?? defaultProps.autoplay;
    autoplayDelay = autoplayDelay ?? defaultProps.autoplayDelay;
    transition = transition ?? defaultProps.transition;
    loop = loop ?? defaultProps.loop;

    // 3. set styles
    const carouselClasses = twMerge(classnames(objectsToString(base.carousel)), className);
    const slideClasses = twMerge(classnames(objectsToString(base.slide)));

    // 4. set carousel functions
    const calculateNewX = React.useCallback(
      () => -index * (containerRef.current?.clientWidth || 0),
      [index],
    );

    const handleNext = React.useCallback(() => {
      const idx = loop ? 0 : index;
      setIndex(index + 1 === childrens.length ? idx : index + 1);
    }, [index, loop, childrens.length]);

    const handlePrev = () => {
      const idx = loop ? childrens.length - 1 : 0;
      setIndex(index - 1 < 0 ? idx : index - 1);
    };

    React.useEffect(() => {
      const controls = animate(x, calculateNewX(), transition);

      return controls.stop;
    }, [calculateNewX, index, x, transition]);

    React.useEffect(() => {
      window.addEventListener("resize", () => {
        animate(x, calculateNewX(), transition);
      });
    }, [calculateNewX, transition, x]);

    React.useEffect(() => {
      if (!autoplay) {
        return;
      }

      const timer = setInterval(() => handleNext(), autoplayDelay);

      return () => clearInterval(timer);
    }, [autoplay, handleNext, autoplayDelay]);

    const mergedRefs = useMergeRefs([containerRef, ref]);

    // 5. return
    return (
      <div {...rest} ref={mergedRefs} className={carouselClasses}>
        {childrens.map((child, i) => (
          <m.div
            key={i}
            ref={slideRef}
            className={slideClasses}
            style={{
              x,
              left: `${i * 100}%`,
              right: `${i * 100}%`,
            }}
          >
            {child}
          </m.div>
        ))}

        {/* arrows */}
        {prevArrow && prevArrow({ loop, handlePrev, activeIndex: index, firstIndex: index === 0 })}
        {nextArrow &&
          nextArrow({
            loop,
            handleNext,
            activeIndex: index,
            lastIndex: index === childrens.length - 1,
          })}

        {/* navigation */}
        {navigation &&
          navigation({ setActiveIndex: setIndex, activeIndex: index, length: childrens.length })}
      </div>
    );
  },
);

Carousel.propTypes = {
  className: propTypesClassName,
  children: propTypesChildren,
  nextArrow: propTypesNextArrow,
  prevArrow: propTypesPrevArrow,
  navigation: propTypesNavigation,
  autoplay: propTypesAutoplay,
  autoplayDelay: propTypesAutoplayDelay,
  transition: propTypesTransition,
  loop: propTypesLoop,
  slideRef: propTypesSlideRef,
};

Carousel.displayName = "MaterialTailwind.Carousel";

export default Carousel;
