// packages/react/src/components/button.tsx
import React from "react";

// @utils
import { twMerge } from "tailwind-merge";
import Ripple from "material-ripple-effects";

// @context
import { useTheme } from "src/context";

// @theme
import { buttonTheme } from "src/theme";

// @types
import type { BaseComponent } from "@types";

export interface ButtonProps extends BaseComponent<"button"> {
  ripple?: boolean;
  rounded?: boolean;
  fullWidth?: boolean;
  className?: string;
  children: React.ReactNode;
}

/**
 * @remarks
 * [Documentation](http://www.material-tailwind.com/docs/react/button) •
 * [Props Definition](https://www.material-tailwind.com/docs/react/button#button-props) •
 * [Theming Guide](https://www.material-tailwind.com/docs/react/button#button-theme)
 *
 * @example
 * ```tsx
 * import { Button } from "@material-tailwind/react";
 *
 * export default function Example() {
 *  return <Button>Button</Button>;
 * }
 * ```
 */
export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      color,
      variant,
      size,
      ripple,
      rounded,
      fullWidth,
      className,
      children,
      ...rest
    },
    ref,
  ) => {
    const contextTheme = useTheme();
    const theme = contextTheme?.button ?? buttonTheme;
    const defaultProps = contextTheme?.button?.defaultProps;

    size ??= (defaultProps?.size as ButtonProps["size"]) ?? "md";
    ripple ??= (defaultProps?.ripple as ButtonProps["ripple"]) ?? true;
    color ??= (defaultProps?.color as ButtonProps["color"]) ?? "primary";
    variant ??= (defaultProps?.variant as ButtonProps["variant"]) ?? "solid";
    fullWidth ??=
      (defaultProps?.fullWidth as ButtonProps["fullWidth"]) ?? false;

    const rippleEffect = ripple !== undefined && new Ripple();

    const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
      const onClick = rest?.onClick;
      const isDarkRipple =
        variant === "ghost" || color === "secondary" || color === "warning";

      if (ripple) {
        rippleEffect.create(e, isDarkRipple ? "dark" : "light");
      }

      return typeof onClick === "function" && onClick(e);
    };

    const styles = twMerge(
      theme.baseStyle,
      theme["size"][size],
      theme["variant"][variant][color],
      rounded && theme["rounded"],
      fullWidth && theme["fullWidth"],
      className,
    );

    return (
      <button ref={ref} className={styles} onClick={handleClick}>
        {children}
      </button>
    );
  },
);

Button.displayName = "MaterialTailwind.Button";

export default Button;

// packages/material-tailwind-solid/src/components/Button/index.tsx
import { createMemo, mergeProps, splitProps } from "solid-js";
import type { JSX, ParentComponent } from "solid-js";

// utils
import Ripple from "material-ripple-effects";
import classnames from "classnames";
import { twMerge } from "tailwind-merge";
import findMatch from "../../utils/findMatch";
import objectsToString from "../../utils/objectsToString";

// context
import { useTheme } from "../../context/theme";

// types
import type { variant, size, color, fullWidth, ripple } from "../../types/components/button";
// import {
//   propTypesVariant,
//   propTypesSize,
//   propTypesColor,
//   propTypesFullWidth,
//   propTypesRipple,
//   propTypesClassName,
//   propTypesChildren,
// } from "../../types/components/button";

export interface ButtonProps {
  variant?: variant;
  size?: size;
  color?: color;
  fullWidth?: fullWidth;
  ripple?: ripple;
}

export const Button: ParentComponent<ButtonProps & JSX.ButtonHTMLAttributes<HTMLButtonElement>> = (
  props,
) => {
  // 1. init
  const { button } = useTheme();
  // 2. set default props
  const mergedProps = mergeProps(button.defaultProps, props);
  const [defaultProps, rest] = splitProps(mergedProps, [
    "variant",
    "size",
    "color",
    "fullWidth",
    "ripple",
  ]);

  // 3. set ripple effect instance
  const rippleEffect = createMemo(() => defaultProps.ripple !== undefined && new Ripple());

  // 4. set styles
  const buttonBase = objectsToString(button.styles.base.initial);

  const buttonVariant = createMemo(() => {
    const fColor = findMatch(button.valid.colors, defaultProps.color, "blue");
    const fVariant = findMatch(button.valid.variants, defaultProps.variant, "filled");
    const variants = button.styles.variants;
    return objectsToString(variants[fVariant][fColor]);
  });

  const buttonSize = createMemo(() =>
    objectsToString(button.styles.sizes[findMatch(button.valid.sizes, defaultProps.size, "md")]),
  );

  const classes = createMemo(() =>
    twMerge(
      classnames(buttonBase, buttonSize(), buttonVariant(), {
        [objectsToString(button.styles.base.fullWidth)]: defaultProps.fullWidth,
      }),
      props.class,
    ),
  );

  // 5. return
  return (
    <button
      {...rest}
      class={classes()}
      type={props.type || "button"}
      onMouseDown={(e) => {
        const onMouseDown = props.onMouseDown;

        if (defaultProps.ripple) {
          rippleEffect().create(
            e,
            defaultProps.variant === "filled" || defaultProps.variant === "gradient"
              ? "light"
              : "dark",
          );
        }

        return typeof onMouseDown === "function" && onMouseDown(e);
      }}
    >
      {props.children}
    </button>
  );
};

// Button.propTypes = {
//   variant: PropTypes.oneOf(propTypesVariant),
//   size: PropTypes.oneOf(propTypesSize),
//   color: PropTypes.oneOf(propTypesColor),
//   fullWidth: propTypesFullWidth,
//   ripple: propTypesRipple,
//   className: propTypesClassName,
//   children: propTypesChildren,
// };

// Button.displayName = "MaterialTailwind.Button";

export default Button;
